### ISSUE TITLE
Using internal links will delete preceding white space. 

### ISSUE THREAD

**Issue by adamjohndaly** [Automattic/simplenote-electron#3172] opened 2023-12-19 23:04 UTC
I can reproduce this issue on Simplenote web. 

> Suppose I open a note in simplenote, and I write “Weekly Journal”, and I want to add an internal link to the right: “Weekly Journal [Monday](simplenote://1234567)”
> 
> Once I create that link, it suddenly eats a whitespace to the left: “Weekly Journal[Monday](simplenote://1234567)”
> 
> I then manually have to go back and re-add the whitespace. This is on Simplenote for Web. Wondering if this is reproduceable and hopefully fixable?

### Expected

White space between the text and the link is not deleted. 

### Observed

The whitespace is removed. 

### Reproduced

1. Use app.simplenote.com
2. Type text and then spacebar
3. Use an opening bracket `[` and then select another note
4. Note that the space between the text and the link is removed. 

<img width="899" alt="Screenshot 2023-12-19 at 4 03 54 PM" src="https://github.com/Automattic/simplenote-electron/assets/18173779/2d600e53-76de-4a46-bf3b-1098c03355dc">

### Where did you see the bug

- System Make: macOS
- System Model:
- OS: macOS 14.2
- OS version: 
- Browser (if applicable): Chrome
- Browser version (if applicable): Version 120.0.6099.109 (Official Build) (arm64)
- Simplenote app version: 
https://forums.simplenote.com/forums/topic/internal-notes-problem-creating-note-eats-whitespace-character-to-the-left/?view=all

**Comment by codebykat** [comment] 2024-05-09 20:46
Probably duplicate of #2771

**Closed as not planned by codebykat** 2024-05-09 20:46 UTC
Labels: bug, [feature] editor
