### ISSUE TITLE
User Requests Easier Editing - Feature Request

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/simplenote-electron#758] opened 2018-04-29 13:09 UTC
> * WYSIWIG interface instead of or in addition to markup 
> * Global setting for font, especially availability of a fixed-width one

#1118368-zen

**Comment by mirka** [comment] 2018-10-19 22:36
Closing as duplicate of #352 and #274

**Closed by mirka** 2018-10-19 22:36 UTC
Labels: feature request
