### ISSUE TITLE
Some of my existing notes simply disappeared, and yet they can still be downloaded in a backup.

### ISSUE THREAD

**Issue by JohnnyBGoode-59** [Automattic/simplenote-electron#3056] opened 2021-12-16 16:39 UTC
Yesterday when I was looking for some of my notes on my Android Pixel2 phone I noticed that a lot of my notes were missing, even though I had not deleted them. Today I started my research to figure out how to restore those notes by using a Windows 10 PC to download a backup of my notes that I could compare with an older backup. Imagine my surprise when I found that all of those notes are in the backup. So next I looked on the PC and sure enough it too cannot see those notes using the web based app.  So the notes are there, but hidden from me using both of the methods I tend to use to try to see them.

Attached is that backup file. I would expect that you could create a whole new test account, import those notes, and reproduce the problem.  Maybe not, but I would think so.

Meanwhile I need to get this working for me so I will try some things with my account so that I can access those notes again.

### Expected
I expected to find notes that I entered long ago still visible in the app.
When I did not see them, I figured they somehow were deleted from the cloud.

### Observed
Those notes are not visible, from either Android or Windows web, and yet are still contained within a backup file I created after witnessing the problem.

### Reproduced
I do not know how I got to this point, but I would think that the backup file might make it reproducible.

### Where did you see the bug

The following were provided in a log report sent by the app from my phone to my email:
Device: Google Pixel 2 (walleye)
System: Android 11 (30)
App: Simplenote 2.23 (148)

- System Make: Dell 
- System Model: Inspiron 5567
- OS: Microsoft Windows
- OS version: 10 Home
- Browser (if applicable): Fixfox
- Browser version (if applicable): 95.0 (64 bit)

**Comment by JohnnyBGoode-59** [comment] 2021-12-16 16:58
I was wrong.  I created a new account, uploaded the json file added to this report, and all my notes appear to be restored.

Should I just remove the previous account and call it a day?  Or do you want to try to figure this out using that older account?

**Comment by codebykat** [comment] 2021-12-24 03:04
Hi @JohnAndJanita, I'm glad you were able to fix the problem.

As a first order of business: **This GitHub is public**, and your notes backup contained a great deal of sensitive information. I've redacted it, but you should assume that any information contained in those notes may have been seen by anyone in the world. Data uploaded to GitHub is visible to anyone at all (not only Automattic employees).

Please **immediately change any passwords or PINs that were contained in that backup**, and be on the alert for any misuses of the other information that was contained there (some personally-identifiable information which seems innocuous on its face can still be used to impersonate you and/or attempt identity theft). I have only skimmed the information in the notes, but you may want to consider monitoring your credit reports closely for the next while (or even placing a fraud alert), and be extra alert for any unusual charges on your bills.

With that out of the way, we could certainly investigate the cause of the issue, but my guess is that it had something to do with the age of the notes/account, and we may well have advised you to fix it the way that you did. If you'd like to drop us a line at support@simplenote.com, we'd be happy to investigate further.

I'll close this for now since we can't debug account-related issues on the public GitHub.

**Closed as completed by codebykat** 2021-12-24 03:04 UTC
Labels: bug
