### ISSUE TITLE
Display Settings not scrollable in mobile web browser, some devices

### ISSUE THREAD

**Issue by cameronvoell** [Automattic/simplenote-electron#1637] opened 2019-10-08 18:01 UTC
### Expected
User visits the Simplenote web app on mobile in Chrome, Firefox, or Safari. After visiting Settings => Display, they can then scroll down to properties that do not fit in initial screen.

### Observed
On certain devices (listed below), when you visit Settings => Display, the device only shows some properties and you can not scroll. To exit you can tap the thin margin on the left or right, but otherwise you seem stuck. 

### Reproduced
 1. In a mobile browser, viewing the Simplenote Web App , click Settings
 2. Tap Display
 3. Notice you can not scroll (See screenshots below from Chrome and Firefox on Android, and Safari on iOS)

![Screenshot_2019-10-08-10-24-58](https://user-images.githubusercontent.com/1103838/66418470-08f3e780-e9b7-11e9-82ea-829029554cd8.png)
![Screenshot_2019-10-08-10-25-27](https://user-images.githubusercontent.com/1103838/66418488-101af580-e9b7-11e9-9400-23b5025fd58f.png)
![Screenshot 2019-10-08 at 10 49 04 AM](https://user-images.githubusercontent.com/1103838/66419725-6e48d800-e9b9-11e9-9dd0-8261beb42216.png)

This was reproduced in the web app on the following platforms:

Android - Samsung Note 2, Android 4.4.2 - Chrome, Firefox
Samsung Galaxy Note8 model #SM-N950U Android 4.4.153
iOS - iPhone 7, iOS version 13.1.2 - Safari

**Comment by cameronvoell** [comment] 2019-10-08 18:02
First reported in zendesk: 2405279

**Comment by belcherj** [comment] 2019-11-26 17:39
Duplicate of: https://github.com/Automattic/simplenote-electron/issues/1268

**Closed by belcherj** 2019-11-26 17:39 UTC
Labels: [priority] low, bug
