### ISSUE TITLE
Mac beta: New line at bottom of note hidden until one types

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-electron#582] opened 2017-07-08 13:32 UTC
#### Steps to reproduce
1. Create a note and add content until the last line is at the bottom of the screen.
2. Press Return.

#### What I expected
For the cursor to go to a new line, and for text in the note to shift upwards so the new line is visible.

#### What happened instead
Nothing happened when pressing Return. The new line was only revealed once I started typing in it. The new line can also be revealed by manually scrolling up.

#### OS version
Simplenote 1.0.8 on Mac OS 10.12.5

I'll try to replicate on Windows as well and update here if it also happens there.

#### Screenshot / Video
![simp](https://user-images.githubusercontent.com/11873759/27985782-7dd32c5c-63f2-11e7-96be-f5859073ac2b.gif)

Issue was reported via Twitter

**Comment by KokkieH** [comment] 2017-07-10 15:37
Confirmed the same happens on Windows 7.

**Comment by dmsnell** [comment] 2017-07-10 15:45
> Confirmed the same happens on Windows 7.

thanks @KokkieH - just a quick note: if it happens in Linux, Mac Beta, or Windows it's almost 100% surely going to happen in all three.

**Comment by KokkieH** [comment] 2017-07-10 17:47
I assumed it would, but thought I'd make sure :)

**Comment by Topy44** [comment] 2017-08-08 17:38
I was just about to open an issue for this - I can confirm this happens in Windows, and it is annoying.

**Comment by dmsnell** [comment] 2017-08-23 02:07
Closing as a duplicate of #492 where I think we have some more diagnostics information.

**Closed by dmsnell** 2017-08-23 02:07 UTC
Labels: bug, [OS] macOS
