### ISSUE TITLE
Language not accepted: Telugu

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#2187] opened 2020-07-05 21:53 UTC
reported in 3081359-zen

> I am trying to type and save content in Language named "Telugu -తెలుగు" / TE in "Unicode". It is not rendenting / getting
typed properly.

this happens on both Linux and the web app

Linux: Laptop, System76 Oryx Pro, using "Pop OS 20.04" withSimplenote v1.18.0. I am using "Telugu (rts (m17n))" as additional language for keyboard

They note that the Android mobile app works fine with this language.

**Comment by Bey0ndB1nary** [comment] 2020-07-14 12:42
Hi Melissa

i will be more specific with typing issue. What i am able to type in Web app and Android & not able to in Linux App. 

బాగుంది  --->   This is right and able to type exactly in Android app & Web app.
బాగుది     --->   This is wrong and this is how it is getting typed in Linux App. "o" is not getting typed in Linux app wherever required, even with other words where it is needed.

https://www.unicode.org/charts/PDF/U0C00.pdf

UNICODE Character " **0C02** " from above sheet is not getting typed in Linux App.

If required, i am ready to be part of testing and help resolve this issue. 

Thanks.

**Comment by belcherj** [comment] 2020-11-03 01:40
@Bey0ndB1nary Can you give version 2.0.0 a test and let us know if this is still an issue?

**Comment by sandymcfadden** [comment] 2021-01-15 13:49
@Bey0ndB1nary just wanted to check in again to see if this was resolved with one of the newer versions. Latest is 2.4.0 currently.

**Comment by codebykat** [comment] 2021-02-09 21:14
If still happening, this seems probably an IME problem #2522. Closing as a duplicate of that parent issue but please feel free to add further details here.

**Closed as completed by codebykat** 2021-02-09 21:14 UTC
Labels: bug
