### ISSUE TITLE
Editor: Simplenote doesn't display correct fonts for CJK languages, for example Japanese

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#788] opened 2018-07-26 12:41 UTC
This is a report from a user in 1304762-zen. The user pointed out the following issue:

>On windows app with Japanese language, incorrect and mixed fonts are used.
> Text to reproduce:
>"日本語の漢字とひらがな、カタカナ、Alphabet混在サンプルです。"
>That's well known problem CJK language environment.

This may be an Electron issue, rather than something that's specific to the Simplenote app itself. The user helpfully pointed out these two issues that touch on how the Electron app doesn't adequately cater for CJK languages when it comes to font choices:

* https://github.com/Microsoft/vscode/issues/4433
* https://github.com/Microsoft/vscode/issues/5260

The user included the following screenshot as an illustration of their point:

![](http://cld.wthms.co/wz1y2d+)

Unfortunately, I'm not familiar with the correct fonts that _should_ be used for CJK fonts to elaborate on this example.

### OS version

OS: Windows (although this appears to relate to Electron-based Simplenote apps).

### Related issue

This issue is peripherally related to Issue https://github.com/Automattic/simplenote-electron/issues/274

**Comment by mirka** [comment] 2018-11-19 14:18
I confirmed this issue. This happens in Windows Electron when the OS language is not set to Japanese.

![not-japanese-font](https://user-images.githubusercontent.com/555336/48712145-60c71a00-ec50-11e8-813d-4cbf08c4fad6.png)

A temporary workaround is to set the OS language to Japanese.

**Comment by mirka** [comment] 2018-11-19 14:18
For Chrome (inside Electron) to correctly choose language-appropriate fonts, we must ensure one of two things:

- An enclosing HTML tag has the proper `lang` attribute set
- `window.navigator.language` or `window.navigator.languages` includes the correct language

(In a normal Chrome browser, a user can set multiple languages and their priorities in the Language settings.)

Possible ways to fix:

- Use a [language detection library](https://github.com/wooorm/franc) to set an appropriate `lang` attribute to each note.
- See if there is a way to get the OS's "Preferred Languages" settings and set them to `navigator.languages`

**Comment by msilbers** [comment] 2019-05-07 20:25
Simplenote Windows user requests the ability to use a different font in Simplenote, because the chosen Chinese font does not look good. I am not sure if this is closer to this issue or a feature request, but the user wants it to use the default Chinese font on their computer.

#2013229-zen

**Comment by mirka** [comment] 2020-09-24 08:47
Confirmed fixed in 1.21.1. Electron/Chromium now seems to respect the Preferred Languages settings on Windows, and sets the `window.navigator.languages` array correctly. The proper system fonts are used now, i.e. a Japanese font will be used if the Preferred Languages list contains Japanese and not Chinese. (cc @belcherj)

**Closed by mirka** 2020-09-24 08:47 UTC
Labels: [OS] windows, bug, enhancement, i18n
