### ISSUE TITLE
Shortcut to toggle between note/tag editing breaks after removing tag

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2028] opened 2020-04-21 11:19 UTC
### Expected

I expect to always be able to toggle between editing the note content and editing tags using the documented shortcut for "Toggle editing content/tags" (e.g. `CTRL + T` on Windows).

### Observed

The shortcut works as expected in these cases:

* Toggle without making any changes
* Toggle to tag editor after changing note content
* Toggle to note editor after adding a tag

The shortcut doesn't work as expected in this case:

* Toggle to note editor after removing a tag

### Reproduced

Note: The steps below use the Windows keyboard shortcut but the same behavior was observed on macOS as well, using the macOS shortcut.

1. Open a note with a tag.
2. With focus on the tag editor, backspace twice to remove a tag.
3. Type `CTRL + T` to toggle focus to the note editor.
4. Start typing in the note editor and notice that the cursor disappears and the content is not added.

This screencast shows the working scenarios and then the non-working case:

![electron_tag-toggle-shortcut](https://user-images.githubusercontent.com/8658164/79860262-3e4baa00-83ca-11ea-87cc-c84affa53cc3.gif)

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.16.0-beta1
Macbook Pro|macOS|10.15.4|1.16.0-beta1

**Comment by codebykat** [comment] 2020-04-24 05:37
I can't reproduce this on the Mac, either in Electron or Firefox :/

**Comment by codebykat** [comment] 2020-04-24 05:40
Oh, yes I can. Hah. The cursor switches back and I can type a single character, and then focus goes... away? 😕

**Comment by codebykat** [comment] 2020-04-24 05:42
This also happened after just switching back from the tag window after, I'm not sure what. Just adding a tag I think. And once it's in that state you can switch back and forth between the tag editing bar and the note content as much as you want, and every time you switch back to the note content, you can type one more character before it loses focus again.

**Comment by dmsnell** [comment] 2020-04-25 04:33
We're gating on which field has focus, which in certain circumstances doesn't work because neither field is in focus.

I created #2041 to make this more intuitive.

**Comment by codebykat** [comment] 2020-04-30 21:30
Fixed by #2041

**Closed by codebykat** 2020-04-30 21:30 UTC
Labels: bug, keyboard
