### ISSUE TITLE
Double Click markdown view to edit a note

### ISSUE THREAD

**Issue by wisehackermonkey** [Automattic/simplenote-electron#2702] opened 2021-02-28 19:45 UTC
### What

Make double clicking the markdown view open up editing of the note.

### Why

When I'm editing notes I often try to double click the text to edit it, but realize im in markdown mode, and having to click. 
![image](https://user-images.githubusercontent.com/29699356/109431239-51e87980-79ba-11eb-9ea7-243499717b58.png)
![image](https://user-images.githubusercontent.com/29699356/109431242-5a40b480-79ba-11eb-9246-21a20614ef55.png)

### How

I simple solution is to allow for double clicking of the text when in markdown mode to switch to edit mode.
This is a android idium that makes for a smooth switching between edit and view (markdown)
User flow:
![image](https://user-images.githubusercontent.com/29699356/109431109-9de6ee80-79b9-11eb-9ff6-02b6c6ddc5f6.png)

**Comment by wisehackermonkey** [comment] 2021-03-11 15:43
Any thoughts?

**Comment by codebykat** [comment] 2021-03-11 21:15
Hi @wisehackermonkey, I'm not sure about this one because double-clicking is generally not an idiom that is used on the web. I think this would be an unexpected behavior if one is trying to, say, select text (important to note that some OSes and browsers support an interaction of multiple-clicks on text to expand selection).

That being said we always appreciate feedback and we look at all feature requests when planning future work!

I'm going to close this for now since we use GitHub to track only bugs and our immediate roadmap, but please feel free to leave comments if you have any additional thoughts.

**Closed as completed by codebykat** 2021-03-11 21:15 UTC
Labels: feature request

**Comment by wisehackermonkey** [comment] 2021-03-12 19:54
# thanks for the feedback.

### `double-clicking is generally not an idiom that is used on the web` after some thought I have to agree with this. 

# what about doing a shift click or "cmd + right click"?

best,
-oran
