### ISSUE TITLE
Simplenote editor in Chrome on Win 10 and in iOS very slow lately (April 2020)

### ISSUE THREAD

**Issue by JimBobHarris** [Automattic/simplenote-electron#2044] opened 2020-04-27 20:47 UTC
I'm a newbie and don't know how to reply to 

https://github.com/Automattic/simplenote-electron/issues/501

and the items related to it

so please link this however you think is best (or not).

My "contribution": In both (a) the Simplenote app on my iPhone 8 with 45 GB free and the current iOS, and (b) the browser-based editor on Chrome (current) on an "OK" older Win 10 Home box, also patched current and with 20 GB free but "only" 2.5 GB RAM total available because it's 32-bit, I'm seeing _much_ slower performance in the last few months. Also, on the iPhone only, I think, most recently edit delays are so long that I can insert one character in a file of only a couple hundred characters, then move my cursor, and the edit completes in the wrong place. Also, often, dictated text gets inserted twice. None of these problems ever happened to me in the several years I've been using Simplenote in both environments. One possibly relevant fact is that I now have a _lot_ of files, some of them fairly large, but probably none over 500 lines.

Also, please send me a link to instructions for how to add to an existing "discussion" on Github.

Thanks for any help, and thanks for a _great_ product; I recommend it to everyone I help.

Jim Harris

**Comment by dmsnell** [comment] 2020-04-27 20:55
Thanks for the feedback @JimBobHarris.

> please send me a link to instructions for how to add to an existing "discussion" on Github.

If you find an issue that resembles what you want to report you can scroll to the bottom of the page and add a new comment. For example, at an issue like #1456

> Also, often, dictated text gets inserted twice

Recently I saw another performance issue that included a speech component. By any chance are you able to temporarily disable the voice control/dictation and see if that impacts the performance characteristics?

**Comment by JimBobHarris** [comment] 2020-04-28 20:55
Wow, thanks, Dennis, for the quick response, good help, etc.!

Here's a little more info for you, most of which you probably already know:

1. I just now learned why I saw no way to comment: I'm working on my emails
at one of my Windows 10 boxen at the moment, and followed your link to #1456
<https://github.com/Automattic/simplenote-electron/issues/1456> and
scrolled to the bottom and there is the comment adder. However, it's not
there on my iPhone 8 with current software including the Simplenote app, or
on my iPad Mini with kinda current software 😠 , or on my wife's fairly new
iPad with current software.
*====>* Were you aware of this difference?

2. I wondered if my observation was common. It's good to know that "often,
dictated text gets inserted twice" not because of Simplenote or something
I'm doing wrong; thanks!

3. I will try disabling Dictation in Simplenote on my iDevices and see if
that matters, and let you know what I learn. My feeling now is that that is
not the only source of slowdowns, since I often see poor performance and
the "editing location lag" issue when I'm _*not*_ using Dictation. I'm
sorry I'm not better equipped to help.

4. As I mentioned, I have (what I think is) a _lot_ of text in Simplenote,
even though few of my files are over 500 words. Can you e.g. send me a
report of my storage usage in Simplenote, or even better, can you tell me
how to learn that for myself at any time, preferably on each note, sorted
by size or "filename"? I understand that the first line, which appears to
be a "filename" is in fact not the unique identifier, but it would be great
to be able to sort by that too.
*====>* Alternatively, if you can look at my account and tell me that I am
certainly not now causing a performance problem by my amount of text, and
that I probably never will, given that it has taken me something like 10
years to get to this amount, then I withdraw the report request.

*====>* When I learn more and I want to reply to any of these points,
should I just reply to this email thread? If not, please tell me the better
way(s). I am not a software developer and I have no skills on GitHub and I
don't use Git.

Thanks again.

Regards,

Jim Harris

**Comment by dmsnell** [comment] 2020-04-28 22:33
@JimBobHarris there might be some confusion here. I hope we can figure this out.

> 1. …working on my emails…comment adder…aware of this difference?

I can see that you're responding via email to this GitHub issue. That's fine but I'm not actually as familiar with emailing new comments on issues. You might need to login to https://github.com, then follow the link I sent, then look for this box (but it will have your user icon and not mine).

![addComment mov](https://user-images.githubusercontent.com/5431237/80543351-85eeaa80-8963-11ea-91ab-6e40e760bdf6.gif)

> 2. I wondered if my observation was common…

I'm not aware of it being a common issue, but neither is using full speech dictation, relatively speaking. We generally get quick feedback for issues like the cursor lagging behind the keyboard and we haven't had that as far as I'm aware. It's still not likely something you're doing wrong, and we don't really care much about "who's to blame" so much as when something like this happens we have to try and figure out what's causing it so we can try and fix it.

> 3. …since I often see poor performance and
the "editing location lag" issue when I'm _*not*_ using Dictation…

It was just one other issue I've seen where having dictation enabled had caused a problem. We only noticed it because in a screenshot a customer sent us we saw the extra options for speech in the bubble that pops up when you long-press on some text on an iPhone.

That is, I think that _if_ there's a connection here it would probably be a result of having dictation _available_ and not associated with whether or not we're _using_ dictation. Does that make sense? When things like that are activated/enabled/available then they tend to hook into the software at points we may not expect, causing issues.

> 4. …a _lot_ of text in Simplenote…

We don't discuss details about individual accounts in public - you are welcome to email us at support@simplenote.com if you want to discuss your account.

That being said, Simplenote doesn't have any practical limit. I have a test note in my account with the [entire text of Pygmalion](https://www.gutenberg.org/files/3825/3825-h/3825-h.htm) which I use for performance monitoring and it does okay.

There _is_ a note info panel in all the apps/devices that will show you how many words and characters are in each note. We don't have a utility to export this information in bulk though, partially because note size and note count isn't much of a problem typically until we hit some pretty unreasonable limits.

Warmly,
Dennis

**Comment by JimBobHarris** [comment] 2020-04-29 19:06
Wow (again), and thanks (again) for your excellent support, Dennis! Rarely
if ever do I get _all_ points in an email I've sent addressed _at_all_ by
the recipient, let alone as amazingly well as you just did.

So, OK, where we stand now is that I will keep trying to notice "where the
problem is" and "where the problem isn't" etc., and even set up "test
cases" with Dictation mode on and with it off, etc..

I am going in for cancer treatment tomorrow, so may not feel up to doing
much for the next couple weeks.

Even so, I will try to let you know in the next few days any preliminary
results, even if it's "no issues noticed".

Best regards,

Jim Harris

**Comment by JimBobHarris** [comment] 2020-06-23 15:02
Hello again, Dennis.

I'm still trying to capture enough solid data to help analyze this, but I'm
thinking more and more it's due to other factors than your software, e.g
WiFi connection stability/speed, flakey old Win 10 box, Dictation mode (as
observed on other apps than Simplenote), etc..

Also, my cancer is gone and I'm just going in for checkups quarterly then
less frequently, so I will soon be spending more time on my computers and
thus using Simplenote a lot again.

Thanks again for all your great help, including the very clear stuff on
commenting online vs. email. I will try to use the regular channels, not
email, to submit any new info.

Best regards,

Jim

**Comment by dmsnell** [comment] 2020-06-23 17:09
> Also, my cancer is gone

@JimBobHarris congratulations! that's great news and I'm glad to hear it.

It may be worth mentioning before you spend too much time trying to diagnose the computer ailments that I've been working on a major overhaul of how the application works internally and in that change we're switching out the component that handles the text editing. The new version will behave differently; hopefully it will resolve your performance issue but if it doesn't the reproduction steps might change. I hope to have this ready within the next month or so.

Warmly

**Comment by JimBobHarris** [comment] 2020-06-25 11:32
Thanks, Dennis!

Of course, I will follow your advice.

Regards,

Jim

**Comment by dmsnell** [comment] 2020-09-21 22:12
hello @JimBobHarris - we have released the aforementioned update at https://app.simplenote.com and I invite you to try again and see if the performance issue is resolved. you may have to clear your browser cache if nothing seems different.

**Comment by codebykat** [comment] 2020-10-21 04:15
Closing, presumed fixed - @JimBobHarris please do feel free to come back and let us know how it's working out for you, and if you're still having any problems!

**Closed by codebykat** 2020-10-21 04:15 UTC

**Comment by JimBobHarris** [comment] 2020-10-21 13:04
I agree, this item can be closed.

Thanks for making sure I knew what was going on.

I never did try the beta because I have so much in Simplenote and I was afraid that it might lose everything. 

Since the release, I have only recently tried some of the scenarios that gave me so much trouble before, but I agree that the weird cursor movements and very slow response issues have never recurred in my few tests. 

Unfortunately, I cannot exactly duplicate the previous conditions, because I installed 64-bit Windows 10 on the computer that was giving me most of the problems, which then had 32-bit Windows 10. 

Thanks again for your excellent support, and a really excellent cross-platform text editor!

Sincerely,

Jim Harris
