### ISSUE TITLE
Collaboration Feature | Doesn't Work  ..... Please Fix it is my Second Day Using Simple Note :( 

### ISSUE THREAD

**Issue by BaheySaied** [Automattic/simplenote-electron#3111] opened 2022-08-21 13:59 UTC
Collaboration Feature Doesn't Function as Expected,, I Can Add Email Address but simple note Doesn't Sync Changes to Other Collaborator & Vice Versa 

### Expected
  Simple Note Should Sync Any Changes Made By the Note Creator or The Note Collaborators to each other

### Observed
Simple Note Doesn't Sync Changes to other Person I Shared the Note With

### Reproduced

1. Open Simple Note
2. Create New Note
5. Add Collaborator Email Address
6. Type Down any Text & Wait to see if the changes take effect and reach the other collaborators

### Where did you see the bug
- System Make:
- System Model: Lenovo IdeaPad 320
- OS: Windows 10 Pro
- OS version:  21H2
- Browser (if applicable): Chrome
- Browser version (if applicable): 104.0.5112.102
- Simplenote app version: Occurs on all Simple Note Includes :  Windows Store & Standalone App | Andriod Version | Web Version

**Comment by BertSnijckers** [comment] 2022-08-24 11:57
Same here, since a couple of days notes are not syncing anymore between collaborators, in where individual sync (for example between phone and Windows-laptop version) works fine.

**Comment by reginabally** [comment] 2022-08-26 08:38
Hi @BertSnijckers The issue is now fixed. Can you please try again and let us know if the issue persists?

**Comment by BertSnijckers** [comment] 2022-08-26 09:46
Seems to work again. Thanks for that, but still curious on why it broke???

**Comment by reginabally** [comment] 2022-08-26 09:58
Glad to know that it's working again, @BertSnijckers! Our team is still investigating the root cause of it, but we suspect it may be due to server performance issues.

Since this is resolved. I'm closing this report. If you still need help with the app, please reach out to us at support@simplenote.com. Thank you!

**Closed as completed by reginabally** 2022-08-26 09:58 UTC
Labels: bug
