### ISSUE TITLE
PC Application aspect differs from Android App

### ISSUE THREAD

**Issue by AntonioIT** [Automattic/simplenote-electron#338] opened 2016-07-08 13:07 UTC
The aspect of notes shown by SimpleNote application for Windows differs from the same note as shown in Android App.
Android App does not show the note formatted with tags, and the same tags are shown (not good), while the first word of the note is treated as the note title and is shown in bold (good).
Both versions should have the same features : 
1. no need to format the first word, treating it as a title.
2. optional formatting tags should never be visible except when editing a note.
Thank you.

**Comment by roundhill** [comment] 2016-07-13 15:42
An Android app update is coming soon with Markdown support.

And this is also a dupe of #330

**Closed by roundhill** 2016-07-13 15:42 UTC
