### ISSUE TITLE
Linux Desktop: Minimize to tray

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/simplenote-electron#489] opened 2017-01-16 20:00 UTC
Request from user in 3003047-t:

> 1. Make it run in background like Telegram. Instead of exiting it should be minimized in tray. I want this feature because when I keep it minimized & navigate from one app to other it comes in between and that I don't want.
> 
> 2. If you add functionality to minimized it to tray then add option "Add note" from tray.

**Comment by gerv** [comment] 2017-05-16 09:01
Workaround: define a shortcut key like F11 to open the app; that's as quick as clicking a tray icon.

**Comment by dmsnell** [comment] 2018-02-19 04:39
Code in PR in #710!

**Comment by mirka** [comment] 2018-10-19 22:51
Closing as duplicate of #362

**Closed by mirka** 2018-10-19 22:51 UTC
Labels: [OS] linux, enhancement
