### ISSUE TITLE
Automatic hyperlink formatting in Simplenote for Windows & Web

### ISSUE THREAD

**Issue by jgadsby** [Automattic/simplenote-electron#342] opened 2016-07-13 15:28 UTC
Simplenote on Mac and Android automatically highlights URLs, even if the note is not Markdown formatted. This does not happen on Simplenote for Windows, in the desktop or web apps. I have to add markdown formatting and switch the view to Markdown to be able to click on the links. It'd be really great if this feature was brought to Windows.

**Comment by axil** [comment] 2016-08-04 14:19
I second that. It would be a great step forward in usability.

**Comment by drw158** [comment] 2016-09-13 17:04
Dupe of #368

**Closed by drw158** 2016-09-13 17:04 UTC
