### ISSUE TITLE
search words separately instead of as string

### ISSUE THREAD

**Issue by owcz** [Automattic/simplenote-electron#447] opened 2016-11-30 18:01 UTC
#### Steps to reproduce
1. Look for note titled "suggestions from diane & janet" but don't remember the name
2. Search for "suggestions" and a bunch of hits show up
3. Continue typing... "suggestions janet" and there are no hits

#### What I expected
"suggestions janet" should reveal notes titled "suggestions from diane & janet"

#### What happened instead
No results

#### OS version
Linux, latest version of SN, replicates across several OSes

#### Another example
1. Searching "janet " (with a space at the end) removes the note from view. Not expected search behavior.
2. Additionally string search support (with quotation marks, e.g., "diane & janet") would be nice, but that's a separate issue

**Comment by dmsnell** [comment] 2016-11-30 18:05
this sounds like a good idea, thanks for taking the time to write it down @owcz!

we'll check into it at some point but I'm not sure when. we're finishing up some high-priority bug fixes and will then reorganize.

**Comment by dmsnell** [comment] 2017-01-30 02:47
Closing as a duplicate of #333

**Closed by dmsnell** 2017-01-30 02:47 UTC
Labels: enhancement, feature request
