### ISSUE TITLE
Bulleted list not auto-adding bullets

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#2379] opened 2020-10-02 09:10 UTC
Bulleted lists no longer auto- add bullets in the web app when pressing enter after a list item

### Expected

The bullet list should consistently add a bullet point automatically when pressing enter.

### Observed

This isn't happening consistently for some users. 

### Reproduced

@msilbers was able to reproduce this, but I haven't been able to so far:
![list](https://user-images.githubusercontent.com/10325627/94906610-aed91580-0496-11eb-85f9-8bcd53baeec9.gif)

Steps reported by user: 
Steps to reproduce: not-working platform (Simplenote web)
1. Start an unordered list by starting a line with a - or * character, followed by a space.
2. Type a word, such as “one”.
3. Press the Return key to create a new line, which will be prefixed with either - or *, depending on format
4. Press the Tab key
5. Observe that the new line is not indented as it was in the working platform.

They report this working for them in the Electron app 1.21.1 or the MacOS app 2.1.

### Where did you see the bug
- System Make: Mac OS
- System Model:
- OS: macOS 
- OS version: 10.15.5
- Browser (if applicable): Chrome (Melissa) Firefox 81.0 (User)
- Browser version (if applicable): 85.0.4183.121
- Simplenote app version: Simplenote Web 2.0.0-rc5

Reported in 3357474-zen

**Comment by elibud** [comment] 2020-10-22 15:16
We have a similar report for checklists, Windows 10, Microsoft Edge, and Chrome. I have a video, ping me if you need it.

**Comment by azollafox** [comment] 2020-11-17 17:12
In addition to no longer adding a bullet, trying to press enter mid list like this now brings your cursor to the bottom of the list
![](https://d.pr/i/UIeWQQ+)
(Image link: https://d.pr/i/UIeWQQ )

Reported in #3476961-zen

**Comment by codebykat** [comment] 2020-11-21 02:41
That looks like #2336

**Comment by codebykat** [comment] 2020-12-11 23:25
I've fixed one and maybe two of the 2-3 issues reported here. (#2519)  I think there's still some inconsistent bug where hitting enter from a list item does not always create a new list, but I haven't been able to reproduce it so far.

Would appreciate if folks on this thread could try to test and see if there are still problems ❤️

**Comment by codebykat** [comment] 2020-12-23 04:30
Closing as I haven't seen this issue or any reports of it lately.

**Closed as completed by codebykat** 2020-12-23 04:30 UTC
Labels: bug, [feature] editor

**Comment by codebykat** [comment] 2021-01-05 23:16
OMG we were able to reproduce it and fix it (see #2548)

**Comment by pachlava** [comment] 2021-01-20 09:21
Verified on Windows with Electron 2.5.0-beta1
