### ISSUE TITLE
"Remember me" option doesn't seem to work when visiting the web app

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#1156] opened 2019-01-15 07:32 UTC
Seems that when a Windows user visits http://app.simplenote.com/ or http://app.simplenote.com/new , they're prompted to log in again every time they visit it. 

Some cases: 

- 1716750-zen
- 1711021-zen
- 1707895-zen
- 1730973-zen
- 1734761-zen

**How to replicate:**
I wasn't able to replicate it with Firefox 64.0.2 & OSX El Capital 10.11.6 , as seems only happens in Windows, but seems that is just visiting the site, closing the tab, and visiting again so:

1. Visit the URL: http://app.simplenote.com/ 
2. Login
3. Close the window or tab
4. Repeat

Try the same with the URL: http://app.simplenote.com/new/

**Comment by dromero20** [comment] 2019-01-15 08:11
Unable to reproduce in OSX Mojave 10.14.2 + Firefox 64.0 (64-bit) (I tried both URLs + remember me and I can get back without logging again).

**Comment by blazevivan** [comment] 2019-01-15 15:17
I can confirm this. Tested on Windows 10, Chrome v71.0

The issue is with both links. 

The bigger issue is that when I chose to login with WordPress.com account nothing happens, I'm not logged in and it returns me to the Sign In page.

**Comment by mgalbritton** [comment] 2019-01-15 15:36
reported as well in #1711021-zen

Steps to reproduce (from user):
1. Logged in. "Remember Me" selected. "Try it Now". 
2. Closed tab, NOT browser. 
3. Was still logged in. 
4. Closed browser. 
5. Required new login.

**Comment by msilbers** [comment] 2019-01-19 17:33
Based on the report in 1730973-zen I believe this is happening on both versions of the web app for some users. I have had two reports of this on Windows machines for the web app

**Comment by iamgabrielma** [comment] 2019-01-21 07:02
One more 1734761-zen

**Comment by mirka** [comment] 2019-01-21 12:53
@roundhill Did we change anything on the App Engine side that could be causing this?

**Comment by roundhill** [comment] 2019-01-21 19:39
> @roundhill Did we change anything on the App Engine side that could be causing this?

Yes :) I've fixed it for the old web app, still looking for a good solution for the new app as well.

**Comment by iamgabrielma** [comment] 2019-02-20 07:08
1810320-zen

**Comment by iamgabrielma** [comment] 2019-02-20 07:18
1814851-zen

**Comment by iamgabrielma** [comment] 2019-06-18 03:10
2115582-zen

**Comment by belcherj** [comment] 2020-06-04 19:37
Closing as this should no longer be an issue.

**Closed by belcherj** 2020-06-04 19:37 UTC
Labels: [OS] web, [priority] high, bug
