### ISSUE TITLE
Doesn't work behind HTTP proxy

### ISSUE THREAD

**Issue by svbisch** [Automattic/simplenote-electron#265] opened 2016-03-30 11:01 UTC
I'm behind a HTTP proxy at work here (am using the Linux version btw.). When I start the app the window stays white and eventually times out with this error: »connect ETIMEDOUT 72.14.246.169:443«.

I tried launching via command line:

```
https_proxy="http://«my company proxy»:8080/" /usr/share/simplenote/simplenote
```

Same behaviour.

**Comment by hindsholm** [comment] 2016-03-30 11:15
I use the _Windows_ version at work behind a proxy and it works just fine.

**Comment by lemmoner** [comment] 2016-04-03 22:43
It doesn't work for me under Windows 7. When I start simplenote, I see in wireshark a SYN message towards 72.14.246.169:443 which is never responded, hence retransmissions happen.
Is Simplenote Win App re-using Internet Explorer settings? If yes, the communication should work. However, why does simplenote try to access that IP? It belongs to Google (My username is a gmail account), but I don't see why the application should rely on google for authentication proccess.

**Comment by smilingsun** [comment] 2016-04-07 13:36
Hope it can support system proxy or manual proxy in Ubuntu.

**Comment by vobj** [comment] 2016-04-14 14:54
I'm using the Linux (Debian Jessie) version and I also have this issue.

**Comment by irstevenson** [comment] 2016-07-06 23:23
Same problem here with version 1.0.2 on Linux Mint behind a corporate Microsoft NTLM proxy with username and password credentials required. (Have both http_proxy and https_proxy env variables set.)

**Comment by aalbertson** [comment] 2016-08-01 23:09
+1 Simplenote Mac 1.1.6, proxy settings enabled everywhere, but no way to even configure simplenote to read it and it is not picking it up automatically.

**Comment by MicBosi** [comment] 2016-08-04 09:22
A user just reported the same problem on:
iMac, OS X El Capitan 10.11.6
Simplenote.app v1.1.6

**Comment by aalbertson** [comment] 2016-08-04 17:13
I should clarify, my system (browser, terminal, sudoers, etc...) proxy settings are enabled, however simplenote does not seem to pick this up, and I have yet to find a location to configure them for simplenote itself.

**Comment by abaudot** [comment] 2016-10-09 08:09
@aalbertson I second this, I would like a way to configure a proxy for simplenote, or have it use systemwide proxy.

**Comment by xopxe** [comment] 2017-05-05 22:50
1.0.8 here, ubuntu 16.04 behind a plain proxy. No error messages nor any sync. Just stays blank. Created notes on android and webpage, and they work. Nothing goes to/from desktop.

**Comment by isebmo** [comment] 2017-05-10 07:35
Same problem on Windows 7

**Comment by pearlstar** [comment] 2017-10-09 05:52
In case of Ubuntu 16.04.3 LTS : 
Instead of using the application provided by the official debian package in Ubuntu, try using the official **snap package** provided, it works fine behind corporate/institute proxy.
`sudo snap install simplenote`

**Comment by githubusersb** [comment] 2018-03-27 19:33
Google chrome in Windows 7 behind proxy is not working. I can login, but cannot see any note. But I found the same is working in IE11.

**Comment by roundhill** [comment] 2018-04-13 21:30
You might want to check with your system administrator for access to https://api.simperium.com, maybe it's not allowed through your proxy?

**Comment by PhiLhoSoft** [comment] 2018-12-13 16:53
Can we have a detail of what Simplenote does on the network?
In my case, I could log in, I see my notes, but if I do an update at work, the changes don't propagate to the server. I don't see them on my phone, for example. On the other hand, if I make a change on my phone, it is correctly merged with my changes at work, but still in download mode, not in upload direction.

**Comment by Ros-Rain** [comment] 2019-03-01 08:17
Hi!

Linux users can set a proxy config via command line, when starting the App: simplenote --proxy-server=127.0.0.1:1234

It works.

**Comment by mriverodorta** [comment] 2019-05-04 03:42
I'm using Deepin OS, it has an option to configure a system-wide proxy, it works with that option. I also tested the @Ros-Rain way and it worked too.

**Comment by codebykat** [comment] 2020-01-15 20:33
There are a variety of reports here from different OSes and browsers, and many of them are quite old. I'm going to close for now with a request: Can anyone who is still experiencing syncing problems after verifying that api.simperium.com is not blocked please comment with details about your setup (OS, browser, how proxy is configured) and the exact issues caused (not loading, not syncing, etc) so we can get to the bottom of it? Thanks!

**Comment by mattcincotta** [comment] 2020-06-22 00:56
Hi @codebykat

I've tried the Simplenote App on MacOS Mojave and Catalina (currently 10.15.5).
It was my favourite app to use between Windows and Android but I now have a MacBook and at the schools I work at, use a proxy.

Simplenote fails to use any proxy settings on MacOS - this is the ONLY app I've got installed that doesn't work behind a proxy on MacOS. All other apps read the proxy settings with no issues.
Web version works fine.

- Confirmed that api.simperium.com, *.simperium.com, *.simplenote.com is whitelisted on the proxy.
- I've tried with Web Proxy (HTTP), Secure Web Proxy (HTTPS) and Automatic proxy configuration (.pac file). All leading to the point below (continuous loading).
- Sign in works, but after that you get a continuous loading icon on the right side of the new note icon (sync failing to work).
- Ros-Rain's solution is for Linux. The only way I've got Simplenote to sync behind a proxy on MacOS is with another app called Proxifier (tested on the trial version).

Keen to work with you to get this working behind a proxy on MacOS.
Thanks

**Comment by codebykat** [comment] 2020-06-22 20:58
This is so strange because [Electron's docs about the --proxy-server option](https://github.com/electron/electron/blob/master/docs/api/command-line-switches.md#--proxy-serveraddressport) say:

> Use a specified proxy server, which overrides the system setting.

Which sure seems to imply that it should be respecting the system setting by default.

@mattcincotta are you using a system-wide proxy configured via the OSX Proxy settings, or a separate proxy app?

Logging in successfully but then failing to sync data definitely points to an issue connecting to the simperium server (but a successful connection to simplenote.com). That does make me wonder if the proxy configuration is not right somehow.

I kind of wonder if this will be incidentally fixed with an upgrade to the latest Electron (just merged in https://github.com/Automattic/simplenote-electron/pull/2102)

**Comment by mattcincotta** [comment] 2020-06-22 22:59
Hi @codebykat - using a system-wide proxy configured specifically via MacOS System Prefs > Network > Advanced > Proxies > Web Proxy (HTTP) AND/OR Secure Web Proxy (HTTPS) OR Automatic proxy.
Currently using the Automatic proxy (.pac file) as that's what we tend to use at the schools.

When will we see a beta release of the recent changes so I can test?

TIA

**Comment by mattcincotta** [comment] 2020-06-22 23:08
@codebykat just an update - tried the 1.19.0beta1 - this version works with the system proxy settings.
Might need to get that app store version updated :)

Thanks

**Comment by codebykat** [comment] 2020-06-24 08:57
Oh that's beautiful - thank you for testing, @mattcincotta. We were quite a bit behind in our Electron version so I'm honestly not surprised if that was a bug that was fixed somewhere along the line. 1.19 will be released in a few days (June 29th I believe) but no reason you can't continue to use the beta until then!

**Closed by codebykat** 2020-06-24 08:57 UTC
Labels: bug
