### ISSUE TITLE
Search: different results on different clients

### ISSUE THREAD

**Issue by keypey** [Automattic/simplenote-electron#415] opened 2016-10-24 11:22 UTC
#### Steps to reproduce
1. Use Android client /1.5.1
2. Use web (firefox) client
3. Use Linux client /1.0.5
4. Search in "All messages" word: clust

#### What I expected
- this same items on all Simple note clietents

#### What happened instead
- different items: web/android client/Linux client

#### OS version
Firefox 49.00
Linux: Linux3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
Android: 6.0.1
#### Screenshot / Video
https://drive.google.com/open?id=0B6BFQ0vlLSkHbzVBMFEtVnlfZW8
https://drive.google.com/open?id=0B6BFQ0vlLSkHRnlUU2p1Z0NCU0E
https://drive.google.com/open?id=0B6BFQ0vlLSkHcnBpVUd3MHZ0RUE

**Comment by dmsnell** [comment] 2016-10-27 21:12
Thanks for the report @keypey! I'm going to close this as a duplicate of #360, but I would love to hear further from you there.

It looks like you were running the latest 1.0.5 release which surprises me because we cleaned up a few search-related issues in that. Could you confirm for us that all four of the notes in your screenshot exist on the Linux client?

**Closed by dmsnell** 2016-10-27 21:12 UTC
