### ISSUE TITLE
Markdown: URLs aren't linkified in published markdown notes

### ISSUE THREAD

**Issue by AliceAML** [Automattic/simplenote-electron#1990] opened 2020-04-10 10:16 UTC
### Expected
When I look at the preview of a note I can click the links. I expected it to work when the note is published too.

### Observed
I can't click the links when the note is published.

### Reproduced
> 1. Publish a note
> 2. Open the url
> 3. Can't click the links

Preview and published note :
![Capture d’écran de 2020-04-10 12-15-34](https://user-images.githubusercontent.com/7511585/78983716-079da600-7b25-11ea-9e53-f97b7dec510f.png)
![Capture d’écran de 2020-04-10 12-15-02](https://user-images.githubusercontent.com/7511585/78983717-08363c80-7b25-11ea-9944-24ad33a8aa5f.png)

**Comment by rachelmcr** [comment] 2020-04-22 09:33
Thanks for the report! I confirmed I'm seeing the same issue: the link is "linkified" (clickable) when I preview the note, but when I view the published note it isn't linkified.

I tested in VirtualBox VM, Windows 10, Simplenote Electron 1.16.0-beta1.

**Comment by ssent1** [comment] 2020-04-23 19:09
I ran into the same issue as well. The link was not appearing in either of:

- `Share > Publish > PUBLIC LINK` or
- `Info > Public link`

When I went back in to get a screenshot, it was there. It seems that the server is too slow. I'm wondering if a server reconfiguration or code refactoring might be required to get it to work consistently as expected.

**Comment by dmsnell** [comment] 2020-04-23 22:00
@ssent1 I believe that you are seeing a different issue, that there is lag between telling Simplenote to publish your note and getting a public URL to view it. Lag is normal and although we'd like for it to be faster, sometimes it does take a while when the queue fills up.

Concerning the linkification of URLs in the note content itself this is an issue we've had for a while and is a result of having different Markdown renderers on each platform and on the server. We'd like for it to be identical everywhere but that may take a while to reach, nothing in the near future.

For individual links that don't get "linkified" we can see if we can figure out why not, but @AliceAML if you find these popping up and the important thing is getting that link then you can work around the issue with a Markdown note by making the link explicit. (Without more investigation the problem with this one _could_ be that it's a `.fr` as some link pattern matchers look for three or more letters in the domain when that's too-specific and wrong).

```
This presents the URL as a linked version of the URL itself
[https://pixies.fr/classcode-v2/](https://pixies.fr/classcode-v2)

But you can add custom link text…
[Classcode IAI](https://pixies.fr/classcode-v2)
```

Rendered, those would look like this…
---

This presents the URL as a linked version of the URL itself
[https://pixies.fr/classcode-v2/](https://pixies.fr/classcode-v2)

But you can add custom link text…
[Classcode IAI](https://pixies.fr/classcode-v2)

**Comment by codebykat** [comment] 2020-06-08 20:16
I'm going to close this as stale, but if folks have other reports, we can reopen. Having specific examples of links that don't get linkified would be helpful!

**Comment by rachelmcr** [comment] 2020-06-09 08:59
@codebykat It's happening to me with all links when Markdown is enabled. Here's an example of a note I have:

```
Links

https://simplenote.com/

Simplenote: https://simplenote.com/
```

Published note: https://app.simplenote.com/p/Mm2vPw

With Markdown disabled, both of those links are linkified in the published note. With Markdown enabled, both links are linkified in the Markdown preview but _not_ in the published note.

Is it expected that with Markdown enabled you'll need to use Markdown to linkify it?

**Comment by codebykat** [comment] 2020-06-09 23:04
Hmm no, that is a bug. I'll look into it @rachelmcr. Do you happen to know if it was working before the last few days? I was expecting this to be a regression, but I just spot-checked a couple of older versions of the code and I'm not seeing the linkifying on any of them.

**Comment by codebykat** [comment] 2020-06-10 07:24
Ahh okay I see why and I think it has always been like this; we're using the Django `urlize` template filter on plain-text notes, but we can't run that on the Markdown note after parsing Markdown. I'm looking to see if there's any easy fix.

**Comment by rachelmcr** [comment] 2020-06-10 09:31
Yeah, this was the same behavior I saw when I tested it in the 1.16 beta and I wouldn't be surprised if it's always been this way. I'll reopen this issue and update the title so it's clear this is related to Markdown.

**Comment by codebykat** [comment] 2020-06-11 23:13
So in Markdown, you can use "automatic links" by surrounding a URL with angle brackets.

> Automatic Links
> Markdown supports a shortcut style for creating “automatic” links for URLs and email addresses: simply surround the URL or email address with angle brackets. What this means is that if you want to show the actual text of a URL or email address, and also have it be a clickable link, you can do this
> `<http://example.com/>`
>
> Markdown will turn this into:
>
> `<a href="http://example.com/">http://example.com/</a>`

https://daringfireball.net/projects/markdown/syntax#autolink

Trying to support linkifying arbitrary URLs *in addition to the above syntax* would likely be very finicky and error-prone, so I'm inclined to leave this as-is. You can either stick to plain-text and have links be made clickable, or you can be in Markdown mode and be slightly more explicit about when you want a link to be a link.

**Comment by rachelmcr** [comment] 2020-06-12 08:54
Leaving the published note behavior as-is makes sense to me, given the options provided by Markdown.

In that case, though, is there anything we can do to change the Markdown preview behavior in the app to match? (Currently the preview linkifies these links, which adds to the confusion/sense of a bug, since it sets the expectation that the links will be linkified when the note is published.)

**Comment by codebykat** [comment] 2020-06-14 02:08
Ooh I think I was wrong ☝️ 

I think we can try enabling auto-linking for Markdown notes as well and see if it creates problems. I have a fix in the pipeline for it.

**Comment by codebykat** [comment] 2020-06-22 22:12
This should now be fixed in published notes. However it's still a different parser than the one used for note previews so I do expect some inconsistencies.

**Closed by codebykat** 2020-06-22 22:12 UTC
Labels: [feature] publish, bug

**Comment by khaullen** [comment] 2021-12-14 03:33
@dmsnell any update on unifying the Markdown renderers? It's always a bit jarring to see it rendered one way in preview, then differently when published, even when they're both on web.

**Comment by dmsnell** [comment] 2021-12-14 15:52
Unfortunately no @khaullen; no updates here and there probably won't be any time soon. Wish I had more exciting news for you!
