### ISSUE TITLE
search by tag with CTRL + F

### ISSUE THREAD

**Issue by KodeNationFR** [Automattic/simplenote-electron#1250] opened 2019-04-22 05:25 UTC
Hello, it is not possible to affect a search by tag, via the shortcut CTRL + F or simply by the search bar, it would be very useful to be able to do it, it can be a real time saver, when we want to have quick access to a note, which we do not remember the content. I note many things in simple note, for my content creation, and I often need to search for notes by topics, and search through the trackpad, or scroll the tags on my smartphone is not practical, d ' as much, that one can not filter the notes with several tags either. I think simplenote would really win to improve his tag system.
thank you.

#### Steps to reproduce
1. open simplenote
2. do CTRL + F or place the cursor in the search bar
3. type the name of a tag

#### What I expected
i hope to see the notes associated with this tag in the search results

#### What happened instead
no note matches my search

#### Simplenote version
1.5.0 for Linux (.deb) & 1.7.0 for Androîd

#### OS version
Liniux Mint Mate 19.1 & Androïd 8.0.0

#### Screenshot / Video
<p align="center">
  <img src="https://res.cloudinary.com/dogtjmenn/image/upload/v1555910399/tag-blur.png">
</p>
<p align="center">
  <img src="https://res.cloudinary.com/dogtjmenn/image/upload/v1555910399/tag-2.png">
</p>

**Comment by KodeNationFR** [comment] 2019-04-22 05:34
@stephdau  @folletto @koke @beaucollins 

-

**Comment by mirka** [comment] 2019-05-15 17:03
Thanks for the request!

Closing as a duplicate of #895, but in the meantime you can search tags using this syntax: `tag:tag-name`. So if your tag is called `mytag`, you can search for those notes from the search field by typing `tag:mytag`.

**Closed by mirka** 2019-05-15 17:03 UTC

**Comment by KodeNationFR** [comment] 2019-05-16 01:55
ok thank you, it works very well at home. you should put more emphasis on this feature I think it can help a lot of people.
