### ISSUE TITLE
JavaScript Error when closing the window.

### ISSUE THREAD

**Issue by praveenpuglia** [Automattic/simplenote-electron#589] opened 2017-07-14 05:46 UTC
#### Steps to reproduce
1. Try to close the window
2. It pops up a JavaScript Error

```
Uncaught Exception:
TypeError: Cannot read property 'getDisplayMatching' of null
    at updateState (/Applications/Simplenote.app/Contents/Resources/app/node_modules/electron-window-state/index.js:86:33)
    at BrowserWindow.closeHandler (/Applications/Simplenote.app/Contents/Resources/app/node_modules/electron-window-state/index.js:111:5)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)
```

#### What I expected
The window would close without any error.

#### What happened instead
The error popup appeared.

#### OS version
Mac OS Sierra - 10.12.5

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/313363/28199758-c6add99e-6885-11e7-8a32-ddcdffce8d9a.png)

**Comment by dmsnell** [comment] 2017-08-23 02:02
Closing as duplicate of #524

**Closed by dmsnell** 2017-08-23 02:02 UTC
