### ISSUE TITLE
Windows: After typing the text and a newline, typing a full-width space(s) in Japanese will duplicate the previous text

### ISSUE THREAD

**Issue by nekocodeX** [Automattic/simplenote-electron#2502] opened 2020-12-02 04:40 UTC
### Expected
Full-width space(s) in Japanese are entered in a note.
The full-width space(s) in Japanese here refer to this "　".

### Observed
As you can see in the GIF animation below.
<div align="center">
<img src="https://user-images.githubusercontent.com/65624234/100827796-ebc68600-34a0-11eb-9328-db0281d64a04.gif" width="80%">
</div>
1, 2, 4, 8... you can see that the previous text  is increasing.

### Reproduced
1. Create a new note
2. Type any text
3. Type a newline
4. Type full-width space(s) in Japanese

### Where did you see the bug
- OS: Windows 10 Pro
- OS version: 20H2 (Build: 19042.662)
    (It may not be relevant, but the OS language setting is Japanese.)
- Simplenote app version: 2.2.0

**Comment by czhehua** [comment] 2020-12-02 08:05
I also find the same problem when I am using Chinese Pinyin Input Method.
OS: Ubuntu Desktop 20.04 LTS
Simplenote app version: 2.2.0
It was all right in the previous 2.1.0 version.

**Comment by rezzap** [comment] 2020-12-03 11:57
Another report of this in 3532984-zen. 

> When I press the spacebar, it types in on its own! 

Using Windows 10Pro 64bit.
Simplenote 2.2.0

Did not occur in 2.1 version. 

The user has included a screenrecording of the issue which is available in the ticket and can be seen at 1:11. 

They originally reported the issue mentioned in https://github.com/Automattic/simplenote-electron/issues/2501 and then added this one which they discovered on testing. I'm not sure if they are related or not.

**Comment by rossanafmenezes** [comment] 2020-12-07 13:53
> Another report of this in 3532984-zen.
> 
> > When I press the spacebar, it types in on its own!
> 
> Using Windows 10Pro 64bit.
> Simplenote 2.2.0
> 
> Did not occur in 2.1 version.
> 
> The user has included a screenrecording of the issue which is available in the ticket and can be seen at 1:11.
> 
> They originally reported the issue mentioned in #2501 and then added this one which they discovered on testing. I'm not sure if they are related or not.

The user came back with more info:

The trouble occurs also when you enter English or numbers.
It's not clear if this is due to the mixture of Japanese.

**Comment by shizukudrops** [comment] 2020-12-08 16:13
The same issue occurs in my environment with Japanese IME.
Windows 10 Pro 64bit 1909
Simplenote for Windows ver 2.2.0

> The trouble occurs also when you enter English or numbers.
> It's not clear if this is due to the mixture of Japanese.

I guess you are missing the point of this issue. The key is to type a **full-width space** after a new line which follows any text. Inputting English, Japanese or numbers before the newline is irrelevant. When you type Japanese, start a new line, and type a half-width space (equivalent to ascii space), the issue will not be reproduced.

**Comment by reginabally** [comment] 2020-12-13 06:19
Another similar report in 3558612-zen for Chinese input.

> Now whenever I press enter or type quotation marks there is a chance of a duplication of previous passages.

OS: Linux Mint 19.3 Tricia 
App version: 2.2.0 ( Simplenote-linux-2.2.0-amd64)
Input software: fcitx-rime v1.2.9 (Chinese), but the problem exists as well while using English alone.

A video recording can be found in the ticket.

**Comment by kamektx** [comment] 2020-12-20 02:30
Also in my environment.

OS: Windows 10 Home 20H2 64bit
Version: 2.2.0 (Installed via Microsoft Store)
IME: Google Japanese Input

It seems there's no relevance to the type of IME.
There is also a bug that inline input in IME fails from the time the application is launched until the window is redisplayed in some way. Simplenote App is now very awkward for users who use IME such as Japanese and Chinese...

**Comment by reginabally** [comment] 2020-12-21 05:43
Another report in 3574944-zen. Windows 10 (64-bit), Simple app version 2.3, Chinese IME (Full Pinyin, Simplified Chinese). A screen recording can be found in the ticket.

**Comment by codebykat** [comment] 2020-12-21 21:51
Closing to track in #2522

**Closed as completed by codebykat** 2020-12-21 21:51 UTC
Labels: bug
