### ISSUE TITLE
In note Preview, cursor selecting/highlighting always selects the whole document.

### ISSUE THREAD

**Issue by m-e-h** [Automattic/simplenote-electron#615] opened 2017-08-24 17:38 UTC
#### What I expected
Expected to select a line of text for copying from a markdown code block.

#### What happened instead
The whole note is highlighted/selected.

#### OS version
Ubuntu 16.04

#### Screenshot
![snselect](https://user-images.githubusercontent.com/3585901/29679903-ebc0de1e-88d0-11e7-959b-2fc7239c9613.gif)

**Comment by dmsnell** [comment] 2017-08-24 17:41
Thanks for reporting @m-e-h - this is actually a duplicate of another already reported issue - #511 I think - and should be resolved already here in the code. Keep an eye out for the upcoming v1.1.0 release where it should be fixed for you!

**Closed by dmsnell** 2017-08-24 17:41 UTC

**Comment by m-e-h** [comment] 2017-08-24 17:54
Oh cool thanks! 
And sorry about the duplicate. I did a search through the issues but didn't find anything.

**Comment by dmsnell** [comment] 2017-08-24 17:59
Yeah it was unfortunate timing because I recently closed out that issue :wink:
