### ISSUE TITLE
AutoHotKey not inserting text

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-electron#334] opened 2016-07-05 17:41 UTC
#### Steps to reproduce

I have an AutoHotkey script that lets me type some useful characters and their sequences with my custom keyboard shortcuts, e.g.:

Shift 9 — brackets (), both at once
Alt Shift 9 — “” (typographic quotes)
Alt E — € (euro sign)
Ctrl \ — HTML tag 
#### What I expected/What happened instead

All these shortcuts work system-wide, i.e. I use them in any application that receives text typing, including text editors, Web interfaces, MS Office, and Evernote. Unfortunately the AutoHotkey script doesn’t work in Simplenote. It is a critical constraint for me, for I cannot abandon using my hotkeys.
#### OS version

Windows 10

(user-submitted issue)

**Comment by Arty2** [comment] 2016-11-15 22:54
Confirming this issue. Very disappointed about this; Atom doesn't seem to have the same issue.

**Comment by sstil** [comment] 2017-05-27 05:45
Confirming it's still the same, none of my shortcuts (mostly Win + some other key) work. Like Arty I've also tried other Electron apps (Slack, Headset), they work just fine.

I can imagine the need for a deep keyboard hook (maybe for overriding the Tab handling or something like that) but disabling the other handlers and hooks is just bad form in my view.

**Comment by mirka** [comment] 2019-02-25 11:13
Closing since I can't reproduce on the current version of Simplenote. AutoHotKey seems to be working fine. Let us know if there are particular key combos or scripts that aren't working.

**Closed by mirka** 2019-02-25 11:13 UTC
Labels: bug
