### ISSUE TITLE
Windows: Can't select all text in a note using Ctrl + A

### ISSUE THREAD

**Issue by nekocodeX** [Automattic/simplenote-electron#2432] opened 2020-10-29 03:58 UTC
### How to reproduce
1. Create a new note
2. Type a longer sentence
3. Press <kbd>Ctrl</kbd> + <kbd>A</kbd>

### Expected
All text in the note will be selected.

### Observed
As you can see in this screenshot, only a certain amount of text will be selected.

<div align="center">
<img src="https://user-images.githubusercontent.com/65624234/97522654-9e5b8280-19e3-11eb-8915-c2f798b9f122.png" width="80%">
</div>

Press <kbd>Ctrl</kbd> + <kbd>A</kbd> twice to increase the amount of text to be selected, but not all of it.
<div align="center">
<img src="https://user-images.githubusercontent.com/65624234/97522672-a61b2700-19e3-11eb-980b-ab20908a0bed.png" width="80%">
</div>

### Where did you see the bug
- OS: Windows 10 Pro
- OS version: 20H2 (Build: 19042.608)
    (It may not be relevant, but the OS language setting is Japanese.)
- Simplenote app version: 2.0.0

**Comment by codebykat** [comment] 2020-10-29 04:16
Hi @nekocodeX, thanks for the report. Are you able to select all text from the top menu with Edit -> Select All, or does that have the same problem?

**Comment by nekocodeX** [comment] 2020-10-29 05:43
Hi @codebykat, thank you for your prompt reply!

`Edit` -> `Select All` worked fine.
It only seems to be reproduced when using the <kbd>Ctrl</kbd> + <kbd>A</kbd> shortcut key.

**Comment by djordjeandrejevic** [comment] 2020-10-29 09:24
Happens in Ubuntu 18.04 LTS too.

**Comment by codebykat** [comment] 2020-10-30 02:52
Yeah, whatever's wrong with keyboard shortcuts seems to be going on in both Windows and Linux. I think they may have the same root cause. I'm investigating.

**Comment by chromer030** [comment] 2020-11-11 16:19
same here on Linux client. (Arch Linux)

**Comment by rezzap** [comment] 2020-11-13 13:40
Another user reported this in 3485930-zen 

> The number of lines selected seems depends on window width.

> Selecting menu item “select All” will always work. Only keyboard shortcut is out of order.

On: TOSHIBA dynabook RZ63/CS OS Microsoft Windows 10 Home version 10.0.18363 build 18363
Simple note 2.0.0

**Comment by codebykat** [comment] 2020-11-25 18:47
Will be fixed in 2.2 #2490

**Closed as completed by codebykat** 2020-11-25 18:47 UTC
Labels: bug
