### ISSUE TITLE
Windows installer issue

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#2251] opened 2020-07-29 16:25 UTC
We currently have several reports of folks trying to install Simplenote Windows 1.20 from Github directly, and the installer hangs and never finishes.

> The installation program initializes and gets about halfway through then never goes any further. I have restarted my machine but with no effect. 

> However, each time I download and attempt to install, the execution of the installation hangs (see image below). I will also add that it hangs at this exact point of the installation each time I attempt. 

>  I accidentally uninstalled it from my laptop (Windows 10), and then I tried re-installing it, and the installer is just stuck at 40% loading forever.

![1595946746269blob](https://user-images.githubusercontent.com/31680407/88826304-94cd3f00-d196-11ea-8877-8465fc5aa672.jpg)

One user was able to figure out a workaround, which is downloading directly from the Windows Store:

> I actually managed to overcome the problem.
Basically, for some reason downloading the installer from your website caused this problem.
I discovered that you're also on Microsoft Store, and I managed to successfully download & install it from there.

3158572-zen
3172432-zen
3180109-zen

**Comment by Scapior** [comment] 2020-08-06 13:30
I have the same problem.

**Comment by erricgunawan** [comment] 2020-08-09 07:53
Probably a related issue:

> The built-in update function always gives me errors and when i manually download and install new version, the program is installed parallel to the old version. And when I then uninstall the old version, everything is gone!

Device info:

- HP ProBook
- Windows 10 x64, Version 1909
- happened two times, when updating from second-most up-to-date to the up-to-date version

3197678-zen

**Comment by msilbers** [comment] 2020-08-10 01:35
also reported in 3207389-zen

Windows 10, trying to install Simplenote 1.20

**Comment by azollafox** [comment] 2020-08-11 15:46
Report of a failure on Simplenote 1.21 as well in 3207389-zen

**Comment by azollafox** [comment] 2020-08-13 17:07
Another report here #3221322-zen

**Comment by azollafox** [comment] 2020-08-24 18:28
Reported #3250251-zen

**Comment by erricgunawan** [comment] 2020-08-27 08:53
Report from 3251700-zen

> Notebook 1
Edition Windows 10 Home
Version 1909
Installed on 01/25/2020
OS Build 18363.1016

> Simplenote Version 1.20.0 - When I went to uninstall I found installation entries for 1.17.0 and 1.20.0. Uninstalling 1.17.0 was impossible and I was asked to remove it from the list.

> Notebook 2
Edition Windows 10 Home
Version 2004
Installed on 06/08/2020
OS Build 19041.450

> Simplenote Version 1.21.0 - When I went to uninstall I found installation entries for 1.17.0 and 1.21.0. Uninstalling 1.17.0 was impossible and I was asked to remove it from the list.

**Comment by rezzap** [comment] 2020-08-29 11:42
Reported in 3256454-zen

Windows 10 desktop pc
Trying to upgrade to version 1.22.

**Comment by erricgunawan** [comment] 2020-08-31 03:55
3271026-zen:

> having trouble (re-)installing Simplenote on Windows 10.

> The setup progress bar gets this far, then it just stops and doesn't continue:

![image](https://user-images.githubusercontent.com/1813857/91681373-79c86300-eb78-11ea-9985-691d6ddd3e56.png)

**Comment by azollafox** [comment] 2020-10-18 16:18
#3401676-zen also reported

**Comment by reginabally** [comment] 2020-10-23 02:12
3427884-zen:

> But today, new version, I accept "close and install the
new version" and nothing happens. 

Windows 10, trying to upgrade to a newer version from 1.21.1

**Comment by iHeadway** [comment] 2020-10-25 07:17
Found a problem. You need to delete all the traces of previous installations before install/upgrade simplenote.

**Comment by reginabally** [comment] 2020-10-26 06:12
3435214-zen

**Comment by rossanafmenezes** [comment] 2020-10-27 14:12
Here 3436347-zen the user reports an issue with the pop up that says the update is available. Nothing happens when they click on the update. 

![win10_version](https://user-images.githubusercontent.com/30724184/97313310-d8d6eb00-183c-11eb-8ac8-e8546a743f22.png)

**Comment by rossanafmenezes** [comment] 2020-10-27 18:47
Another report here 3442423-zen

Windows-10 desktop
Simple note 1.1 (1.2 update failed as well)
User says that clicking on the button to update does not result in any action

![SimpleNote-update-failure (1)](https://user-images.githubusercontent.com/30724184/97347493-4269f000-1863-11eb-80a0-8a5477c0e6f0.jpg)

**Comment by azollafox** [comment] 2020-11-03 18:23
Another report at 3456683-zen

**Comment by azollafox** [comment] 2020-11-04 13:44
Another report at 3461943-zen

```
I've tried to update Simplenote on my PC (win10) and I keep getting "Cannot update now ... try later"
I have it on my laptop as well and I keep getting the same message.
```

**Comment by reginabally** [comment] 2020-11-05 05:02
3463690-zen

> My Windows desktop 1.21.1 is telling me to update and restart to go to Version 2.0. But nothing happens when I click the option? Same with the version news option on the popup.

**Comment by hashimaziz1** [comment] 2020-11-16 23:16
Same issue - as far as I can remember the built-in `Restart and Update` option has never worked for me - I don't get an error, it just doesn't do anything. Running Windows 10 and showing an update for 2.1 (currently on 2.0).

**Comment by reginabally** [comment] 2020-11-18 07:11
Another report in 3496365-zen.

**Comment by codebykat** [comment] 2020-11-19 20:27
**For those seeing an error on update**, please do a manual install of version 2.1. The issue should be fixed going forward. #2440 

We're aware of a separate issue with the installer hanging, so I'm leaving this open for now.

**Comment by rossanafmenezes** [comment] 2020-11-21 15:41
Another report here 3507015- zen. 

Will ask them to do the manual install of version 2.1 but just wanted to add it to the report

**Comment by codebykat** [comment] 2020-11-23 23:57
This was reported in https://github.com/Automattic/simplenote-electron/issues/2478 with a request to disable the update available dialog.

**Comment by gubrist** [comment] 2020-11-24 09:23
Regarding the work-around:  **Microsoft Store** does not mention:
- which SN version is installed and 
- which SN version is availble

**Comment by codebykat** [comment] 2020-11-25 18:27
Hi @gubrist, as far as I can tell this is a (annoying!) limitation of the Windows Store. I've been unable to find any apps that show their version. Do you know of any that do? I found an old conversation about this online and it seems nothing has changed. https://answers.microsoft.com/en-us/windows/forum/windows_8-windows_store/windows-store-apps-versions/cf390eb1-1676-41c1-91bb-ff1ec2ad3c2e

**Comment by reginabally** [comment] 2020-12-01 05:25
It was reported in 3532157-zen that the user was having version 2.0.0 installed from the Windows Store, receiving the notification to update the app to version 2.2.0. However, the updated version was 2.1.0 instead.

**Comment by reginabally** [comment] 2020-12-02 06:01
Another report in 3534808-zen that the user received an update notification for 2.2.0 but can only install 2.1.0 from the Windows Store. Screenshots can be found in the ticket.

**Comment by reginabally** [comment] 2020-12-02 07:02
The user has 2.1.0 installed but they were prompted to update from 2.0.0 to 2.2.0 in 3535232-zen.

**Comment by tarunvijwani** [comment] 2020-12-04 04:14
>The user has 2.1.0 installed but they were prompted to update from 2.0.0 to 2.2.0 in 3535232-zen.

User replied they are currently on the 2.0.0. (3535232-zen)

```
It seems I'm mistaken - my current version isn't 2.1.0, it's 2.0.0, despite my having attempted to install it. When I try to "Get" it from the Microsoft store, I'm told the product is installed - I thought it installed 2.1.0 previously, looks like I was wrong.

Screenshot is below of the Update Available window - clicking on --> Update & Restart does nothing, the window simply closes and the app continues to function normally.

```


![image (2)](https://user-images.githubusercontent.com/11503784/101121059-336e1e80-3615-11eb-8082-190257196d80.png)
![image (1)](https://user-images.githubusercontent.com/11503784/101121063-36690f00-3615-11eb-9fee-7c17c8a54d42.png)

**Comment by rossanafmenezes** [comment] 2020-12-04 14:24
Another one here 3537565-zen

version 2.0.0
Windows 10

**Comment by gubrist** [comment] 2020-12-12 11:07
Windows store has updated meanwhile to 2.2.0 
I did not get any notifcation from Windows.

**Comment by poojashetty18** [comment] 2020-12-17 06:04
Another one here #3573024-zen
Windows 10 Home
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz 2.71GHz
Installed memory: 8.00 GB
System Type: 64-bit Operating System, x64 based processor

The version of the Simplenote (that cannot be updated) is:
1.15.0

Suggested to manually update

**Comment by pachlava** [comment] 2021-01-11 16:52
+1 from 3633297-zen:

> When I start the Windows SimpleNote application I get an "Update Available" message box. When I click on "Update & Restart" the message box disappears but the update does not happen.

**Comment by codebykat** [comment] 2021-01-13 03:20
@pachlava Was this user on 2.0.0 or a later version?

**Comment by pachlava** [comment] 2021-01-13 09:46
@codebykat They did not mention, and seeing that the problem looks exactly like the one described here, I did not ask and just I gave them instructions on how to install store-free version, and asked if this help with the issue. Should I additionally ask for the version they had?

**Comment by codebykat** [comment] 2021-01-13 22:36
@pachlava If their issue is solved there's no need to get this information, but it would be good to know in the future if folks are still reporting issues. We haven't had many reports of this lately so if we do have reports of a bug in a version later than 2.0.0, we would want to look into it. Conversely if someone has 2.0.0 and can't update, and their issue is resolved with a manual update, we don't really need to track that as it is a known problem and has been fixed (but obviously the nature of the bug is such that they will need to manually update from 2.0.0).

**Comment by pachlava** [comment] 2021-01-15 13:31
3644440-zen

> I am currently running Simplenote 1.21.1. Every time I open it I get a message to upgrade to 2.4.0 but when I click update and restart,nothing happens.

**Comment by azollafox** [comment] 2021-02-11 14:41
This was reported once again with 2.6.0  in 3729084-zen

**Comment by hashimaziz1** [comment] 2021-02-11 17:09
Yep, experiencing this yet again to upgrade to 2.6.0 

> 
> 
> 3644440-zen
> 
> > I am currently running Simplenote 1.21.1. Every time I open it I get a message to upgrade to 2.4.0 but when I click update and restart,nothing happens.

Also having this problem, on 2.5.0 going to 2.6.0. Must have clicked `Update & Restart` at least four times by now and had it reappear as many, it's very annoying.

**Comment by eduardozulian** [comment] 2021-02-11 22:11
Same on 3732630-zen: when you try to update to 2.6.0, the version returns to 2.5.0

- Windows 10, Version 2004
- Simplenote Desktop Version 2.5.0

**Comment by erricgunawan** [comment] 2021-02-12 08:19
An addition from 3732630-zen:

> Tell them it is probably similar to the issue where clicking on "Update and Restart" in Version 2.1 did absolutely nothing - did not even attempt to download.

**Comment by Luna5521** [comment] 2021-02-25 09:17
> 
> 
> **For those seeing an error on update**, please do a manual install of version 2.1. The issue should be fixed going forward. #2440
> 
> We're aware of a separate issue with the installer hanging, so I'm leaving this open for now.

Any updates on the installer hanging issue?
I had it with going from 2.5 to 2.6 when updating from within Simplenote.
I was able to install 2.6 by downloading the installer.
Now, with going from 2.6 to 2.7 neither the in-app update or trying to update from the downloaded installer works.
Can't update anymore.


Don't really want to use the Windows Store version since it might be an older version??
When I check the release notes on the Windows Store version I think it's v2.5.
Can you confirm this?
Also, does the Windows Store version differ from the downloaded version?

**Comment by codebykat** [comment] 2021-02-26 00:06
Hi @Luna5521, we're trying to get the Windows Store version updated. Sorry for the oversight.

**Comment by Luna5521** [comment] 2021-02-26 02:34
> Hi @Luna5521, we're trying to get the Windows Store version updated. Sorry for the oversight.

Hi @codebykat, thank you for your reply.
No worries, I don't have the store version anyway.
Can the issue with the download version be fixed or is there a way around it?
Maybe the next version will install again ...

**Comment by codebykat** [comment] 2021-02-26 04:01
We've been investigating it but we don't yet know what the issue is, sorry.

**Comment by erricgunawan** [comment] 2021-03-10 03:49
Another report from 3797878-zen:

> I notified about new Simplenote version (2.7.0). After upgrade i see a popup to confirm email address. I click it and then i click on link in email which send to me. I see a message that inform me "your email is verified, return to app", but when I'm go back to app I see a popup and when i close it and close app and restart it I see old version (2.4.0.) and message that new version is available. And process start from start (i try that maybe 5 times and always these same result). What can I do to update Simplenote?

- Windows 10 
- Simplenote version is 2.4.0 trying to update to 2.7.0

Suggested to manually download and update the app.

**Comment by eduardozulian** [comment] 2021-03-19 20:42
From 3828354-zen:

> Thanks for the suggestion, and I would upgrade to the latest version, but I do not know how. I tried uninstalling, downloading, and reinstalling, but it installed the same version I have. I didn’t see any option inside the application either. How can I do it?

**Comment by erricgunawan** [comment] 2021-03-23 05:23
3840739-zen:

> I using microsoft windows 10.
The latest version on the Microsoft Store is version 2.5.0.
I hope update of simplenote to version 2.8.0.
When can I download version 2.7.0 or 2.8.0 from the Microsoft store?

**Comment by eduardozulian** [comment] 2021-04-16 18:51
From 3903000-zen:

> When I launch Simplenote desktop on my PC I get a Simplenote login screen and a dialog box that says I need to update Simplenote to 1.3.0. If I cancel the message, I cannot login, Simplenote does note recognize m user/password. Even though I am running 2.9.0, the only way I can log in is to download the “update” (1.3.0), after I download the “update” and install, it tells me 2.9.0 is available, I then download and install 2.9.0, then and only then can I login to Simplenote. BUT if I do not download 1.3.0, install it over 2.9.0 then install 2.9.0 again I cannot login.

**Comment by rollecode** [comment] 2021-09-11 20:08
Always trying to update here... when Update & Restart is performed and installation through, it does it again when I start the app.

2.17.0-beta1

![image](https://user-images.githubusercontent.com/1534150/132960407-fcf651b4-09ae-452f-ad6f-caca4a07f780.png)

**Comment by thabotswana** [comment] 2021-11-17 09:36
Another report in 4457123-zen

>I use Simplenote on PC (Windows 10) and on Android. On PC I am running
version 1.20.0. It often tells me that a new version is available, I
click the button that says "update and restart", and nothing happens. If
I try to download a new copy of the Windows app, it tells me that the
app is already installed, and doesn't give me the option to download the
latest version.

**Comment by codebykat** [comment] 2021-11-22 18:34
@thabotswana 1.20.0 is an ANCIENT version and probably did have the bug in the updater. Please ask them to install manually to the latest (by uninstalling first after ensuring they are synced / have backed up their notes). It's not like we'll ever be able to retroactively fix updater bugs in versions from years ago, so it's a bit more interesting to track if this bug is happening on more recent versions. 😅

**Comment by codebykat** [comment] 2024-05-09 20:48
Closing due to no recent reports.

**Closed as not planned by codebykat** 2024-05-09 20:48 UTC
Labels: bug, [OS] windows, [feature] build
