### ISSUE TITLE
Sidebar titles missing characters

### ISSUE THREAD

**Issue by kini547** [Automattic/simplenote-electron#1755] opened 2019-12-04 01:50 UTC
Expected
The title on the sidebar should match my note.

Observed
Some characters are missing. 

Reproduced
Not sure but the characters were initially capitalized at the beginning of each word: "Set Piece". Then I made them lower case and it showed this: "et iece". Then I deleted the whole line and retyped it and got this: "et piece". So looks like some characters aren't "deleting" properly. 

Using Windows 10 64-bit

![1](https://user-images.githubusercontent.com/58495492/70105306-abb69400-15fd-11ea-9d09-e4f3af7331f5.png)

**Comment by theck13** [comment] 2019-12-04 02:09
This looks like a duplicate of https://github.com/Automattic/simplenote-electron/issues/1746, which was fixed in https://github.com/Automattic/simplenote-electron/pull/1748 and should be included in the next release.

**Closed by theck13** 2019-12-04 02:09 UTC
Labels: bug
