### ISSUE TITLE
Text wrap issue.

### ISSUE THREAD

**Issue by Chett23** [Automattic/simplenote-electron#3179] opened 2024-02-07 22:36 UTC
### Expected
when indenting a line for a list or otherwise the text should remain ad the indent point even if the text wraps to the next line. An indented line should start at the same indentation point as the line it started on.

### Observed
when the text wraps to a new line, the text drops to the next line and moves back to the left and undoes the indent regardless or number of tabs. This 

### Reproduced
1. Create new note
2. hit tab or indent the line or add a new list
3. write until the text wraps to the next line
4. see error

![image](https://github.com/Automattic/simplenote-electron/assets/46825498/6131e74a-3a31-4acd-bc06-4262b1a78dd7)

### Where did you see the bug

- System Make: Web client
- System Model:
- OS: Macos, linux, and windows
- OS version: 
- Browser (if applicable): Brave
- Browser version (if applicable): Version 1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit)
- Simplenote app version: 2.19.1

**Comment by codebykat** [comment] 2024-05-09 19:57
Duplicate of #3053

**Closed as not planned** 2024-05-09 19:57 UTC
Labels: bug, [feature] editor
