### ISSUE TITLE
Windows Ctrl + F doesn't bring up search box

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#301] opened 2016-04-18 09:04 UTC
Ctrl + F on Windows takes focus to the search field in the app rather than bringing up the usual search box. This means it's not possible to step through to the next found item. 

This is happening on Windows 7 Enterprise with the desktop app.

**Comment by drw158** [comment] 2016-04-18 16:44
Should be fixed in the next release 

#249

**Comment by drw158** [comment] 2016-04-18 17:07
Sorry, I think that PR was merged before v1, so this should be working.

**Comment by tiangolo** [comment] 2016-07-25 14:07
Maybe this is related to #347.

I think I'm having the same "issue". I can search for a term in "All Notes" and in the left column the notes get filtered to the ones having the term. But I can't see where the keyword is inside one of the notes. I have to read it all to find it.

But using the web app (with a browser) instead of the desktop app I can use the browser's search box and find the keyword inside the note.

**Comment by kristarella** [comment] 2016-08-16 21:42
Received a support ticket requesting this, and confirming the behaviour that they can only search all notes, in Linux & Windows app.

**Comment by gracie** [comment] 2017-01-09 01:40
Also requested in #2991041-t

**Comment by SiobhyB** [comment] 2017-01-13 21:11
This also came up in 2994809-t.

**Comment by 74c5** [comment] 2017-02-07 21:03
Seems fixed in v1.08 on linux... searched word text is also highlighted within the note.

**Comment by dmsnell** [comment] 2017-07-12 11:51
@drw158 I feel like I finally understand what we ought to build, can you weigh in here?

<kbd>CtrlOrCmd</kbd> + <kbd>L</kbd> should open the note list search box
<kbd>CtrlOrCmd</kbd> + <kbd>F</kbd> should open the find box for the currently-open note

**Comment by 74c5** [comment] 2017-07-12 22:53
makes sense to me... 
When searching in open note, would we also get a hotkey to find next word... 
F3?

**Comment by drw158** [comment] 2017-07-13 00:26
I still stand by my opinion here in #412 

To paraphrase, <kbd>CtrlOrCmd</kbd> + <kbd>L</kbd> to search anything in SN is unintuitive to me, and I don't think we need to follow web browser paradigms or be consistent with the native MacOS app. We have a chance here to improve the native MacOS app.

I think something like what these apps have done would be great:

**Ulysses**

shift+command+F: search notes
command+F: search within note

**Evernote**

alt+command+F: search notes
command+F: search within note

**Comment by dmsnell** [comment] 2017-08-21 16:34
Closing as duplicate of #37

**Closed by dmsnell** 2017-08-21 16:34 UTC
Labels: feature request
