### ISSUE TITLE
Chinese unfriendly typing experience....!!!

### ISSUE THREAD

**Issue by zhihan526** [Automattic/simplenote-electron#2534] opened 2020-12-19 09:56 UTC
Hey there:

I came across problems while using Simplenotes after 2.0.0. The problem I'm asking here did NOT exist in 2.0.0, but in 2.1.0 to 2.4.0 beta(I tried today)

![image](https://user-images.githubusercontent.com/61249030/102686464-f021cb80-4222-11eb-996c-3ec9777112cd.png)

It's like this, in the top-left corner of the photo, the typing thing is blizzard. In normal typing experience as I would expected, it should be something like this:

![image](https://user-images.githubusercontent.com/61249030/102686527-3e36cf00-4223-11eb-98fb-ef06633973ee.png)

Not to mention, something Simplenotes will ignore my typing characters while I was typing Chinese characters. Such as if I type  "ident", it will shown "dent" or "idnt" sometimes. Very annoy....

please help or advise, thanks.
Otherwise, I'll have to stick with the old 2.0.0 version :(

Harry

**Comment by reginabally** [comment] 2020-12-21 05:40
Another similar reported in 3574944-zen with video recording attached in the ticket. Windows 10 (64-bit), Simple app version 2.3, Chinese IME (Full Pinyin, Simplified Chinese).

The user was trying to type the Chinese character 我 which requires only two keystrokes to enter "w" and "o" but we can hear that he typed "w" twice and then "o" to get the text.

**Comment by zoubei** [comment] 2020-12-21 06:21
I'm about to open an issue when I see this issue already exited. 
The is app is not compatible with Chinese Input Method,
Wish this bug can be fixed quickly.

**Comment by codebykat** [comment] 2020-12-21 21:48
Thank you, this looks like a duplicate of #2522 and maybe a few other reports. Can someone advise what to install to test and replicate this on an English-language computer? I have tested with a few of the OSX IMEs and cannot replicate the issue so far. (Closing to track in #2522 but feel free to answer in either place.)

**Closed as completed by codebykat** 2020-12-21 21:48 UTC
Labels: bug
