### ISSUE TITLE
Please kindly add "Sign up & Sign in with Google Account" option

### ISSUE THREAD

**Issue by romakhan** [Automattic/simplenote-electron#1254] opened 2019-05-01 20:38 UTC
Please kindly add an option to "**Sign up & Sign in with Google Account**"

**Comment by mirka** [comment] 2019-05-15 16:55
Duplicate of #1010

**Closed by mirka** 2019-05-15 16:55 UTC
Labels: feature request

**Comment by romakhan** [comment] 2019-05-15 23:24
Any Estimated time of arrival? @mirka

**Comment by mirka** [comment] 2019-05-16 09:22
No, not that I'm aware of. A new team is starting to develop a roadmap for the rest of the year, so we'll see 🙂
