### ISSUE TITLE
Tags with @ trigger sharing feature in Windows app

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#353] opened 2016-08-05 06:49 UTC
In the web and Mac app it's possible to have tags with @ that are not email addresses. In the Windows app these tags do not appear in the list of tags and they trigger the sharing feature. If we don't want to allow tags with @ - other than in email addresses - then we should make this consistent across all apps.

**Comment by mirka** [comment] 2018-11-09 16:59
Closing as this seems to have been resolved. (Could not reproduce in v1.2.1)

**Closed by mirka** 2018-11-09 16:59 UTC
Labels: bug
