### ISSUE TITLE
Sorting doesn't work in Firefox

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#144] opened 2016-02-04 21:25 UTC
Just a note that if we ever want to release this on the web, the sorting doesn't work in Firefox.

**Comment by dmsnell** [comment] 2016-03-27 23:08
@roundhill I wonder if this could be caused by the fact that we are requesting `alphabetical` as an index key when that column doesn't exist. If `sortType` is `alphabetical`, we should try and fetch the `content` index.

Not sure I can reproduce what you were seeing either. Do you have more details on what issues you were having and how to reproduce?

**Comment by dmsnell** [comment] 2016-03-27 23:17
Oops, please ignore my previous comment - I still had my fixed branch checked out. Now that I'm back on **master**, I can see that there appears to be no sorting done at all in Firefox, regardless of the sort options.

**Comment by dmsnell** [comment] 2017-08-23 03:29
Closing as we have no immediate plans for general release. We can revisit this (or rediscover it) if and when we do.

**Closed by dmsnell** 2017-08-23 03:29 UTC
Labels: bug
