### ISSUE TITLE
Duplicated tildes (áá éé, etc.) on Firefox and Seamonkey on Crunchbang++ Linux (Openbox)

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-electron#2327] opened 2020-09-07 02:44 UTC
### Expected
There should just be a single character and it's not duplicated.

### Observed
This bug occurs only in Firefox and Seamonkey but not in Google Chrome, and only, as far as it's known, in Crunchbang++ Linux (Openbox).

In this particular condition (Crunchbang++ and Firefox), typing letters with a tilde, as in `adiós`, duplicate those special
characters: ``adióós``.

It does, work, however, in other Linux Operating Systems such as Linux Mint and Ubuntu.

A particular thing to notice with the input method of Crunchbang is that these special characters need two keystrokes (\` and a for á) and when typing the first character, "`" appears, and then it is replaced with "á" after pressing the a. This may confuse the script that receives the text.

### Where did you see the bug
- System Make: -
- System Model: -
- OS: Linux
- OS version: Crunchbang++ (Openbox)
- Browser (if applicable): Firefox
- Browser version (if applicable): (confirming) 
- Simplenote app version: (confirming)

**Comment by leogermani** [comment] 2020-09-09 16:19
It also happens on Mac OS. I just opened a duplicate issue now (closing #2330)

I'd like to add that this makes the app Unusable!!!

**Comment by codebykat** [comment] 2020-09-16 04:56
Thanks for the reports; we're working on this upstream here: https://github.com/microsoft/vscode/issues/106392

**Comment by codebykat** [comment] 2020-12-10 20:08
Reported in 3562935-zen

> when typing special characters, like "á" (éíóú), "^", "—" ... they are automatically duplicated.
> I guess it's not a big issue for english users, but for spanish it's really annoying.

**Comment by leogermani** [comment] 2020-12-10 20:32
Yes, please fix this. It's not just annoying, it's almost unusable!

**Comment by dmsnell** [comment] 2020-12-10 20:58
thanks to the work that @belcherj did this is now fixed upstream in Monaco and as soon as we update that dependency (not entirely sure if it's out in the release yet as it was merged at the end of November) Simplenote should also have this fixed.

this was broken everywhere Monaco was in use and will now be fixed everywhere across the internet because it was a problem for Simplenote 😄

**Comment by codebykat** [comment] 2021-02-05 21:04
Will be finally fixed in 2.7.0!

**Closed as completed by codebykat** 2021-02-05 21:04 UTC
Labels: bug, [priority] high, [feature] editor

**Comment by pachlava** [comment] 2021-02-11 17:39
@codebykat I'm not sure if it's a separate thing or a side effect of the fix. When I try entering à via long hold on 'a' key, and then pressing number button in the popup, it results in 'aà' in Firefox (macOS):


https://user-images.githubusercontent.com/73365754/107675495-cfb14300-6ca0-11eb-8ef1-4a5a3119b88f.mov

**Comment by codebykat** [comment] 2021-02-11 17:59
@pachlava Is that a regression or a case that was not fixed by this fix?

**Comment by pachlava** [comment] 2021-02-11 18:21
@codebykat this was also my question to you :-) I think I can't answer this, because the issue was browser specific, and I can't revert to the older version. Anyway, at the moment there is no issue with 'àà' duplication, so I'm thinking of verifying the current issue, and creating a separate one for 'aà'. What do you think?

**Comment by codebykat** [comment] 2021-02-11 22:06
I can reproduce it on the [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html), so it looks like a related but separate upstream issue. @belcherj should we open a new one against vscode?

**Comment by belcherj** [comment] 2021-02-12 21:30
🤦 Yes, please do. Maybe I can try and fix this one too.

**Comment by pachlava** [comment] 2021-02-12 21:56
Created #2674
