### ISSUE TITLE
Windows App taking focus

### ISSUE THREAD

**Issue by dartiss** [Automattic/simplenote-electron#427] opened 2016-11-04 18:36 UTC
A user in Kayako has reported that, under certain conditions, the Windows app is overriding desktop focus. He’s posted a recreate but also details of a setting that appears to cause it.

From #2901197-t

> The bug is simple to reproduce…
> 
> 1. open Simplenote.
> 2. Open any of multitude of applications (I suspect that there is a LOT of them but I can confirm the following, Wordpad, MS Word, Skype, Putty, Win7 Task Manager).
> 3. Move Simplenote window so that it covers at least partially the window of the other application
> 4. now when you click the title bar of the other application to bring it forward to the screen, UI of Simplenote is still covering UI of the other application.
> 
> It seems that the bug is only present when “Enable desktop composition” in Control Panel – System – Advanced – Performance – Settings is disabled.
> 
> I guess it is a minority that disables this setting, but we still do exist. The reason I (and many other) have disabled it is that desktop composition causes audio glitches in digital audio workstations during heavy CPU loads with certain computers (at least mine).
> 

He’s also posted his hardware and software set-up too, if this is of use.

I've also posted the above details on the P2.

**Comment by drw158** [comment] 2016-11-04 19:03
User setup:

Simplenote (1.0.5) on Windows 7 64-bit

**Comment by drw158** [comment] 2016-11-04 19:09
This appears to only be a Windows 7 setting. I have 10, so I am unable to test it at the moment. If someone has a Windows 7 machine and can reproduce we can add this is as bug. Although, it is probably an issue with Electron.

**Comment by mirka** [comment] 2019-02-25 10:40
Closing since I couldn't reproduce this in the current Simplenote version, and also it's likely not something we can fix on our side.

**Closed by mirka** 2019-02-25 10:40 UTC
Labels: [OS] windows
