### ISSUE TITLE
Ubuntu: CTRL + SHIFT + UP doesn't work as expected

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2427] opened 2020-10-27 20:23 UTC
<kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>UP</kbd> keyboard combination doesn't work as expected in Simplenote 2.0.0 on Ubuntu.

### Steps to reproduce
1. Create a list
2. Place mouse pointer somewhere on the last list item
3. Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>UP</kbd> multiple times

### Expected

Standard highlighting as seen on the screenshot below (Windows 10).

![Screenshot_63](https://user-images.githubusercontent.com/8862464/97357812-a6f47180-189a-11eb-9e96-d363bbb6a26a.png)

### Observed

Multiple pointer lines appeared.

![2020-10-27_19-52](https://user-images.githubusercontent.com/8862464/97356993-60524780-1899-11eb-8ed4-bc2d21c90c16.png)

P.S. I haven't tested this with <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>DOWN</kbd> combination, but I assume it's the same as with <kbd>UP</kbd>.

|OS Version|App Version|
|-|-|
|Ubuntu 18.04 LTS|Simplenote 2.0.0|

**Comment by codebykat** [comment] 2020-10-27 23:31
I can reproduce this on the [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html).

#2428 disables those shortcuts, but it doesn't seem to restore the native selection behavior. I wonder if it's because there's not an underlying text area? We might not be able to fix it without a patch to Monaco (the upstream editor component).

**Comment by codebykat** [comment] 2020-11-13 22:21
Will be fixed in 2.2

**Closed as completed** 2020-11-13 22:20 UTC
Labels: bug
