### ISSUE TITLE
Unsynced changes UI not accurate

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-electron#1291] opened 2019-05-23 21:10 UTC
When using the electron app on various platforms (as well as the new web), many times I have noticed that the unsynced changes alert will state there's local changes, when there clearly are not:

<img width="709" alt="Napkin 144 05-23-19, 4 05 03 PM" src="https://user-images.githubusercontent.com/154014/58286521-8d312f80-7d74-11e9-8bd5-14494f2e3202.png">

<img width="290" alt="Screen Shot 2019-05-23 at 3 45 05 PM" src="https://user-images.githubusercontent.com/154014/58286481-768ad880-7d74-11e9-9c1f-c58a517fda3d.png">

This alert never goes away until I restart the app/close the webpage and reopen.

----

It's also worth noting that the electron client is the only one with this UI element. 

@SylvesterWilmott is this UI/functionality something you would like to either:

1. See fixed and then rolled out to the other clients
2. Abandonded and removed from the electron client

?

**Comment by msilbers** [comment] 2019-10-19 20:11
Someone has reported this issue but only in Safari for them right now. They are seeing 260 unsynced notes warning in the web app in Safari 13.0.2, but not Firefox and not in the /old web app. The notes appear to be synced fine but show that warning even after a browser cache clear and with all extensions disabled.

Cannot reproduce on my end.
Reported internally #2424106-zen

**Comment by belcherj** [comment] 2019-11-20 20:01
We merged a change that should have resolved this issue. Closing till it can be reproduced.

**Comment by cynion** [comment] 2019-11-28 13:07
It appears to happen when you empty the trash. I noticed the warning straight after I emptied the trash and the number of notes deleted matched the number not synced. I then deleted some more and, after emptying the trash again, the warning number rose accordingly.

**Closed** 2020-09-21 20:30 UTC
Labels: [feature] sync, [status] needs design review, bug, question
