### ISSUE TITLE
Tag Column too short

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#685] opened 2017-12-23 14:44 UTC
#### Steps to reproduce
1. Using Electron 1.1.1
2. The tag column is too short the read the complete tag names;
they are cut, ending "...."

#### What I expected
I want to expand manually the tag column 

#### OS version
Windows 10

#### Screenshot / Video
![tag column too short_23 12 2017](https://user-images.githubusercontent.com/22197180/34320327-1b8d96ec-e7f8-11e7-8626-42448dc165b5.JPG)

**Comment by dmsnell** [comment] 2017-12-23 20:45
Closing because this is a duplicate of #267. This is a good thing to do and we hope to get it out there before too long. Actually we've had some experimental patches but weren't ready to push their changes out yet. Thanks as always @gubrist!

**Closed by dmsnell** 2017-12-23 20:45 UTC
