### ISSUE TITLE
Sticky History Tooltip

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/simplenote-electron#2491] opened 2020-11-25 18:00 UTC
The tooltip for the History icon seems to stick (see gif). I think this might occur for new, empty notes.

<p align="center">
<img src="https://user-images.githubusercontent.com/8979548/100265321-169f6000-2f1e-11eb-97c3-e01967a0ccab.gif">
</p>

### Expected
Tooltip would be presented and subsequently disappear when the icon is not being hovered over, like the other icons.

### Observed

Tooltip does not disappear and clashes with other tooltips.

### Reproduced

1. Create new note
2. Hover over tooltips

### Where did you see the bug

- OS: Linux, Windows, Mac

**Comment by codebykat** [comment] 2020-11-25 18:10
Dupe of https://github.com/Automattic/simplenote-electron/issues/2464 :)

**Closed as completed by codebykat** 2020-11-25 18:10 UTC
Labels: bug
