### ISSUE TITLE
Simplenote Freezes When the User Attempts to Import Improperly Formatted JSON

### ISSUE THREAD

**Issue by matthewelmer** [Automattic/simplenote-electron#3130] opened 2023-01-12 14:41 UTC
### Expected
When you try to parse bad data, an error should be presented to the user.

### Observed
When bad data is parsed, Simplenote freezes.

### Reproduced
1. Open the Simplenote desktop app
2. File... Import Notes... Browse
3. Select improperly formatted json files (I tried to import from Google Keep)

![image](https://user-images.githubusercontent.com/26128847/212095600-06c45d51-2f51-4ffd-bba7-4631dfe13a35.png)

### Where did you see the bug
- System Make: Framework
- System Model: DIY Edition w/ 11th gen Intel Core i5-1135G7
- OS: Linux Mint
- OS version: 21.1
- Simplenote app version: 2.21.0

**Comment by codebykat** [comment] 2023-09-27 06:20
Duplicate of #2517

**Closed as not planned by codebykat** 2023-09-27 06:20 UTC
Labels: bug
