### ISSUE TITLE
Windows 10: Can't adjust notification settings

### ISSUE THREAD

**Issue by nr1995** [Automattic/simplenote-electron#2482] opened 2020-11-19 18:16 UTC
Hi,
I'm a bit of a noob, and don't know if this is even in the right place,
but I'm using **Simplenote v2.1.0** on Windows 10 (v20H2)(but it was the same in v2004),
and every time I make a note change from my phone,
my Windows 10 PC gives me the notification in the corner, along with an annoying system sound every few seconds.
**I would like to disable this noise, and only the noise.**
On the notification is written “electron.app.Simplenote”,
but when I open the Windows 10 notifications settings window,
those words don't appear, and I'm not sure which of the listed apps (if any) is the relevant one.
(Settings, Focus assist, Backup settings, Wireless, AutoPlay, Security and Maintenance, Audio, Battery saver, Microsoft Store, Print Notification, Settings, Suggested)
My only option seems to be to disable sounds for all notifications, which I don't want to do.
Am I being dumb?  How can I achieve this?
Thanks!

**Comment by codebykat** [comment] 2020-11-19 20:10
Hi @nr1995, thanks for this report. I've confirmed the issue in my testing. I also found if you disable all notifications from electron.app.Simplenote, there seems to be no way to re-enable them 😱 

We'll try to find a fix for this.

**Comment by codebykat** [comment] 2020-11-19 20:11
In case it's helpful for now, you can disable "Notify on remote changes" from your Simplenote app Preferences under Tools. Obviously this will disable the notifications completely.

**Closed as completed** 2020-11-21 02:24 UTC
Labels: bug
