### ISSUE TITLE
Windows: Repeated prompts to update to v1.2.1 on Windows 7, even after update

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#1032] opened 2018-11-21 10:27 UTC
This is a user report from 1580255-zen

### Steps to reproduce

1. User receives prompt through Windows Simplenote app to update to the latest version (v1.2.1).
2. User downloads the update to their PC, and installs the update.
3. Notwithstanding the update, user is again prompted to update.

### What I expected

Updating to the latest version should disable prompts to update to the latest version.

### What happened instead

As the user explained:

>I have installed the latest update at least 7 times on my machine and yet each time I open simplenote on my windows PC it asks me to install the same update again and again.

### Simplenote version

Version 1.2.1 (currently the latest version)

### OS version

Windows 7, 64 bit.

### Screenshot / Video

None.

**Comment by mirka** [comment] 2018-12-07 18:36
There have been big changes to the updater, so I'm going to close this for now.

This was likely caused by the app being installed in different directories. Uninstalling the app and reinstalling should fix it.

We'll see if we still get reports of this with v1.3.0 and higher.

**Closed by mirka** 2018-12-07 18:36 UTC
Labels: [OS] windows, [Status] Needs Review, bug
