### ISSUE TITLE
Note text doesn't expand horizontally to fill window

### ISSUE THREAD

**Issue by PeterTheobald** [Automattic/simplenote-electron#303] opened 2016-04-22 19:19 UTC
When the window is large or full-screen the note text is centered horizontally and doesn't expand horizontally to fill all the available space. It even word-wraps long lines to squeeze them into an imaginary boundary. The text should start at the left not in the center and should flow to near the window's edge not an arbitrary width far short of the window.

**Comment by dmsnell** [comment] 2016-04-22 19:36
Duplicate of #269 

Thanks for the report @PeterTheobald, but as of now we have limited the width of the text area for legibility reasons

**Closed by dmsnell** 2016-04-22 19:36 UTC
Labels: duplicate

**Comment by PeterTheobald** [comment] 2016-04-22 19:51
I disagree with that reasoning, I find wrapped lines much less legible than clean text running to the edge; But thank you for addressing this.

At 03:36 PM 4/22/2016, Dennis Snell wrote:

**Comment by nilsi** [comment] 2018-10-25 15:01
Would also like to see this feature. Maybe like an option. I often paste code into simple note fore temporary storage, for me its getting harder to read when it breaks lines when it wouldn't in my code editor

**Comment by mirka** [comment] 2018-10-25 15:06
@nilsi We actually added this option (#815) in the latest version 1.2.1 👍

**Comment by nilsi** [comment] 2018-10-25 17:16
Oh, wow for some reason I haven't updated in a while! Thanks!
