### ISSUE TITLE
Ctrl+F and menu->Edit->search notes does not jump to application search box (Linux)

### ISSUE THREAD

**Issue by 74c5** [Automattic/simplenote-electron#505] opened 2017-01-29 13:07 UTC
#### Steps to reproduce
1. Launch app
2. From any note/section press 'Ctrl+F'  (or select 'search notes' from drop-down menu)

#### What I expected
Focus should shift to the search field.

#### What happened instead
Nothing.

#### OS version
Manjaro Linux 16.10 64-bit
Simplenote Electron 1.0.7  (aur/simplenote-electron-bin 1.0.7-1)

#### Speculation
Changing hotkeys to 'Shift+CommandOrControl+F' in */usr/share/simplenote/resources/app/desktop*/app.js didn't help. So problem may be with command to set focus? line 209?

**Comment by dmsnell** [comment] 2017-01-30 02:47
Closing as a duplicate of #301 - I would suspect that we can get this in for the next release, which will probably be 1.0.9 (just pushed out 1.0.8 for testing)

**Closed by dmsnell** 2017-01-30 02:47 UTC
