### ISSUE TITLE
Sort Order Preference Not Respected In Web App

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#1560] opened 2019-08-27 21:05 UTC
If you set your sort order preference to be alphabetical, when you log out and log back into the web app, it won't keep your preference set. This happens in Firefox only. 

### Expected
If I set my notes to display alphabetical, that the sort order in the settings, stays. 

### Observed
Using FF, if you set the sort order to alphabetical instead of last updated, it will not keep the setting once you log out and then log back in. 

### Reproduced
1. In Firefox, open Simplenote. 
2. Under settings, set your sort order to alphabetical.
3. See the sort order change.
4. Log out of Simplenote. Close the browser.
5. Open Firefox again, and log into Simplenote.
6. Notice the sort order is back to last updated instead of alphabetical.

Reproduced on Firefox 68.0.2

**Comment by belcherj** [comment] 2019-09-04 16:19
Please retest as I think this has been fixed.  Was not able to reproduce in Firefox 69.0 (64-bit)

**Comment by belcherj** [comment] 2019-09-04 16:23
This setting is only held in the application state and disappears if the app state is flushed which could happen on browser restart.  It will also not be shared across browsers.  I will work to change this setting to use the settings stored by the server.

**Comment by belcherj** [comment] 2019-10-22 14:38
Closing as I have tested this a couple of times and cannot reproduce. Due to local storage being semi-ephemeral you will have this happen from time to time. We are discussing if we want to store preferences per account or per device.

**Closed by belcherj** 2019-10-22 14:38 UTC
Labels: bug

**Comment by joashrajin** [comment] 2025-06-18 14:36
Issue appears to be back and I can replicate it: https://forums.simplenote.com/forums/topic/sort-order-on-https-simplenote-com-reverts-to-modifiednewest/
