### ISSUE TITLE
Sync: Changes not propagating from other apps to Electron app (Windows, Linux)

### ISSUE THREAD

**Issue by Decadence** [Automattic/simplenote-electron#385] opened 2016-09-17 07:35 UTC
Hello. I'm facing issue when Simplenote stops sync notes on Windows 10.
It happens when I don't open application on PC for a few days, but I edit notes from other devices. Then I open app on PC and see old notes.
Account is set in Preferences. Only solution I found is relogin. Seems like authentication has expired.
It's already detected on two different PC.

**Comment by Decadence** [comment] 2016-09-17 07:38
It would be nice to indicate somehow sync status.

**Comment by rustykeyctrl** [comment] 2016-09-17 13:01
Sry I'm a beginner here but really intrigued with git and for the most part don't know these things that's why I'm watching this thread maybe I can learn it as I'm learning git.
I won't summit any other then feedback to learn but my sync status is computer in the shop.
I'd appreciate any help and if it not ok to give any feedback just reports things I'll understand.
Thank you.
Have A Great Day
               Victor Evans
On Sep 17, 2016 2:38 AM, Victor <notifications@github.com> wrote:It would be nice to indicate somehow sync status.

**Comment by neelkadia** [comment] 2016-09-17 23:05
@Decadence I think you can merge the issue with #384 this one.

**Comment by Decadence** [comment] 2016-09-18 08:12
@neelkadia Hardly. I don't use web version at all.

**Comment by hedgefield** [comment] 2016-09-20 19:09
Same problem here. Was supposed to be better in 1.0.3 I think but I'm still seeing it. Only logging out and back in again updates the list properly.

**Comment by rustykeyctrl** [comment] 2016-09-21 00:34
Thanks for the tip I'll try that if the problem persist
Have A Great Day
               Victor Evans
On Sep 20, 2016 2:09 PM, Tim Hengeveld <notifications@github.com> wrote:Same problem here. Was supposed to be better in 1.0.3 I think but I'm still seeing it. Only logging out and back in again updates the list properly.

**Comment by raniesantos** [comment] 2016-09-22 19:08
I use Windows 7.
The desktop electron app of Simplenote always fails to pull down new notes.
When I edit *already existing notes* from Android app or the web app it syncs the changes perfectly fine.
But when I create a *new note* from Android or web, the electron app NEVER SYNCS THEM.

**PLEASE ADD A MANUAL SYNC BUTTON ON THE DESKTOP APP**

**Comment by dmsnell** [comment] 2016-09-22 19:14
Thanks for the report @raniesantos. We're currently trying to figure out why these sync issues are occurring, and we just hate the idea that people are losing content, but we don't expect a manual sync button anytime soon because that doesn't reflect how Simplenote works. Adding a button wouldn't likely impact the current issues. In other words, Simplenote is _always_ synchronizing the notes and if anything has slipped through the cracks there it will continue to be a problem until we figure out why at the deeper level.

You can follow the progress in the new [Resolve sync issues project](https://github.com/Automattic/simplenote-electron/projects/1#card-205890).

**Comment by raniesantos** [comment] 2016-10-01 13:47
Oh and btw, it has already been mentioned but this is also true in my case, logging out and in again temporarily fixes the problem.

**Comment by roundhill** [comment] 2016-10-11 19:20
Here's a build of the next release of the app, that may resolve some sync issues. Give it a try and let us know if you see any improvements or not: https://github.com/Automattic/simplenote-electron/releases/tag/untagged-6a81612f542e4dcb0391

**Comment by nfcampos** [comment] 2016-10-11 19:26
@roundhill that link is a 404, for me at least

**Comment by roundhill** [comment] 2016-10-11 19:28
Thanks @nfcampos, I updated it.

**Comment by CorentinLemaitre** [comment] 2016-10-13 21:31
I have the same problem with the version 1.0.3
I just install the version 1.0.4 and i will let you know if i have some sync problem (in 10 days if i did n't reply it mean that there is no problem)

**Comment by CorentinLemaitre** [comment] 2016-10-17 12:29
I have still problem to sync the notes even with 1.0.4

**Comment by hedgefield** [comment] 2016-10-17 19:05
So far it seems for me 1.0.4 solves it.

**Comment by CorentinLemaitre** [comment] 2016-10-20 14:17
I switch to 1.05. I let you know if i have problems.

**Comment by hedgefield** [comment] 2016-10-26 20:46
Nope 1.0.5 still has the problem.

**Comment by dmsnell** [comment] 2016-10-26 20:53
Thanks everyone for continuing to test on these updates. We're working on it trying to track down the issue but it has been elusive because we haven't been able to reproduce. Maybe one of us has been able to reproduce once but we aren't fully sure.

**Comment by hedgefield** [comment] 2016-10-27 18:30
What usually happens for me is I start a new note on the iOS client, or maybe the webapp or Mac app, and then a few days later when I get around to opening the Windows app, it doesn't sync. So I go into options and logout-login and then the list gets updated properly. I haven't tested extensively with then making more changes across the various platforms, but once the windows app is up-to-date I think it syncs what I do okay until the next time I've edited or newly created something via iOS (that's where I mostly use Simplenote).

**Comment by dmsnell** [comment] 2016-10-27 20:23
Thanks again @hedgefield for your reports. While we haven't identified the problem yet, these details are helping us to narrow down what could be causing the bug. We appreciate it!

**Comment by Decadence** [comment] 2016-10-27 20:30
Guys, I'm going to unsubscribe from this issue because I don't use Simplenote any more so you can close this whenever you want.

**Comment by kriskarkoski** [comment] 2016-10-31 14:39
Another report in 2851098-t

**Comment by planetahuevo** [comment] 2016-11-04 17:55
Another one with the same issue. 
It seems that it sync the data I create or modify on my app to the web, but never on the other direction.
I have 2 computers. If I create a new note on one computer, and go to the other, is not there, but if I open the web, everything is ok. 
I log out and log in into the 2nd computer and everything syncs again.
until i create  anew one. Windows 10 here too on both computers.

**Comment by klakar** [comment] 2016-11-05 09:04
Just adding Linux App to the problem, and Yes! Logging out, and then in again will sync **all** notes!
(Using Simple Note 1.0.6).
Usually occurs when creating the note in the Android App. Editing the note, even in the web-app, will ___not___ sync to Linux App. This is however not consistent! If i do a log-off/log-on it seems to work fine for a while at least.

**Comment by darrenca** [comment] 2016-11-08 23:03
Another reported sync issue in 2903142.

**Comment by charliescheer** [comment] 2016-11-13 06:14
Another sync issue with Windows 7 in 2916145

**Comment by ajcool2k** [comment] 2016-11-15 09:14
Reporting because I lost some unsynced notes lately. Using the app mainly on Ubuntu 16.04 / Windows 10 and at times on Android. All updated to the latest version.

**Comment by dmsnell** [comment] 2016-11-19 21:11
@raniesantos are you willing to share your normal usage pattern? do you keep Simplenote open for days at a time? close it for days at a time and then only after reopening do you notice the sync issues?

if it's up-to-date and you close the app then open it again after a few minutes, do the changes from the mobile apps sync then?

**Comment by raniesantos** [comment] 2016-11-20 18:11
@dmsnell I tested simplenote just now. It seems to have been fixed in my case.

**Comment by dmsnell** [comment] 2016-11-20 19:31
Thanks @raniesantos!

We still believe there's a problem out there because many people _are_ experiencing this issue. We're suspicious of the underlying Simperium JavaScript library.

❓
For those who are experiencing this regularly, when you login after a few days and lose the synchronization, do you have lots of changes/notes waiting to come in from your mobile devices or from Simplenote online? Might you get a subset of changes and then none after that?
❓ 

We're still working hard to try and be able to reproduce this but none of us have had success yet. Maybe one of us has been able to reproduce it once but we're not confident and definitely can't reliably reproduce. Nonetheless, we're still trying to get to the bottom of it.

**Comment by roundhill** [comment] 2016-11-21 14:02
I was thinking... maybe one way to band-aid fix this issue for now would be to force an `index` call to Simperium everytime the app starts (currently it does this only after signing in). I'm 70% confident it would fix the bug, but doesn't isolate the cause.

**Comment by planetahuevo** [comment] 2016-11-21 14:15
Anything will be good. I am just using the web version as I cannot trust the app anymore. :(

**Comment by roundhill** [comment] 2016-11-23 15:21
We were finally able to reproduce the bug and have implemented a fix. I created some beta builds for y'all to try out to ensure that it does indeed fix the issue. Let us know!

You can download the beta here: https://github.com/Automattic/simplenote-electron/releases/tag/1.0.7-beta

**Comment by dmsnell** [comment] 2016-11-24 03:11
@roundhill is there a technical explanation of what you found and how you resolved it and under what circumstances we would predict that this is happening? while offline I was auditing the protocol in `node-simperium` and was forming my own hypothesis.

thanks for the awesome sleuthing on that! if we can get this one fixed, what a happy day that will be

**Comment by planetahuevo** [comment] 2016-11-24 14:00
I will try it as soon as I can. 
Thanks!

**Comment by dmsnell** [comment] 2016-11-30 18:43
Has anyone here been able to try the 1.0.7 beta and either reproduce the bug or confirm that the update fixed it?

**Comment by hedgefield** [comment] 2016-12-01 10:12
I got around to installing it, and right away it loaded in all my most recent notes, and I haven't used the windows desktop app in weeks and changed a ton via the iOS app, so it's looking good!

**Comment by sgbw** [comment] 2016-12-03 08:04
I used to have the same problem with notes written on android not syncing with the linux client on mint 17/18. Updating from 1.0.2 to 1.0.3 only fixed it for a very short period. From then on the only way to keep linux synced was login/logout, which was pretty annoying.
Installed 1.0.7 and it synced like a charm. Will try and test during the next days to see if this time around it keeps working fine.

**Comment by owcz** [comment] 2016-12-07 07:25
Updated to 1.0.7 through the Arch user repo and still having upload sync issues after logging out and in again. For instance, if on the Linux app I make new notes and other edits, other devices won't receive the new text. However, if I make edits on the web app, the Linux app will receive them (so download working better than upload). Moving back to web app now for stability.

**Comment by raniesantos** [comment] 2016-12-12 12:46
Just when I thought it was fixed, I'm here again. (v1.0.6 on Win7)

The only details I'm able to provide right now is that I haven't used it for several days and it suddenly won't sync again.

**Comment by hedgefield** [comment] 2016-12-12 14:46
Did you try the 1.0.7 beta linked above @raniesantos? That fixed it for me.

**Comment by dmsnell** [comment] 2017-01-30 03:30
Closing for now because I believe that the fix in 1.0.7 took care of this issue. We can reopen if this continues to be a problem in 1.0.8 and newer releases.

**Closed by dmsnell** 2017-01-30 03:30 UTC
Labels: bug, priority-high, [Status] In Progress

**Comment by raniesantos** [comment] 2017-01-30 16:08
@dmsnell Yes, I think it definitely did.

**Comment by duttakapil** [comment] 2017-03-31 20:03
I'm on Windows 10, Simplenote 1.0.8 and having this issue. It worked when I first set the mobile and desktop app, but not anymore.

**Comment by stevenfletcher** [comment] 2017-04-23 01:10
I'm having the same problem, but it is hard to spot under what cases this happens and does not happen. I'm wondering (somewhat blindly) if a forced sync on closing the app OR on going from one note to another OR on a settable time of no activity (signifying I'm done for now). Traditionally, you'd do a record lock and release but that can't work here. I often have Simplenote open on both my computer (Windows 7) and on my phone (android). I have tried to make sure I exit one before updated the other, but even then it still has problems. Assuming 3 copies (my computer, my phone and the simplenote server) then it could be seen as 1) action starts > 2) changes > 3) action ends This triad (if you like) has a date and time and should be propagated before allowing any other similar triads on another device (OR they are treated like a log of changes). [The old Palm software would duplicate a record if it got confused in the sync process. Ugly but safe!] ] Just mostly musing here...

**Comment by roorco** [comment] 2018-11-08 11:02
I'm on Manjaro 18, same issue here.
My android app is syncing but not the version on my pc.This after the recent upgrade.
Syncing only after logging out an loggin ing.
