### ISSUE TITLE
No way to quit simplenote 2.0.0 in KDE Plamsa 

### ISSUE THREAD

**Issue by texstar** [Automattic/simplenote-electron#2465] opened 2020-11-11 14:54 UTC
After launching Simplenote 2.0.0 in KDE Plasma,  Quit or clicking on the X icon does not close Simplenote!

**Comment by codebykat** [comment] 2020-11-11 19:58
Thanks for the report! This is very likely a duplicate of #2421 and might be fixed in the next version by #2439.

**Closed as completed by codebykat** 2020-11-11 19:58 UTC
Labels: bug
