### ISSUE TITLE
Request : keyboard shortcut

### ISSUE THREAD

**Issue by CorentinLemaitre** [Automattic/simplenote-electron#529] opened 2017-03-17 10:12 UTC
Hello,
I want to proposed a shortcut to change beetween notes as you can change beetween tabs (Ctrl+ tab AND ctrl+maj+tab). It would be really usefull whe you mainly write in 10 or less notes.
I hope it is possible... (but i am not at all a developper)

**Comment by dmsnell** [comment] 2017-03-17 18:01
@drw158 have you thought about this? do we have some meta+arrow combination not already taken? or something like some IDEs do with <kbd>Ctrl</kdb>+<kbd>[</kbd> etc…

**Comment by drw158** [comment] 2017-03-17 18:08
Technically I think this is a dupe of https://github.com/Automattic/simplenote-electron/issues/37

The MacOS for SN seems like a good approach. If the cursor is not focused on the editor, then you can simply used the up and down arrows to change notes.

**Comment by dmsnell** [comment] 2017-08-21 16:12
Closing as duplicate of #37

**Closed by dmsnell** 2017-08-21 16:12 UTC
