### ISSUE TITLE
Tags not appearing in search results even with "tag:" prefix

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/simplenote-electron#343] opened 2016-07-14 15:23 UTC
Searching for a tag is a feature in the web app that's not available on desktop.
#### Steps to reproduce
1. Add a tag to a note that is not a word found in the note's body, "example123"
2. Search for "example123" and notice no results
3. Search for "tag:example123" and notice no results
#### What I expected

When searching for "tag:example123" to see a list of notes tagged with "example123" as is the behaviour in the web app

![screen shot 2016-07-14 at 11 20 54 am](https://cloud.githubusercontent.com/assets/933450/16844916/0cb2e344-49b5-11e6-8ed1-d5c0245d5d7c.png)
#### What happened instead

No results listed when searching for "tag:example123"
![screen shot 2016-07-14 at 11 21 17 am](https://cloud.githubusercontent.com/assets/933450/16844929/1cd66c78-49b5-11e6-8608-9700c82343c9.png)
#### OS version

Win10

**Comment by alexjgustafson** [comment] 2016-07-14 15:23
Relevant to #2736296-t

**Comment by roundhill** [comment] 2016-07-14 16:20
Isn't this the same as filtering by the tag name when you click on it in the left sidebar?

**Comment by alexjgustafson** [comment] 2016-07-15 10:40
It is - but we provide both the clickable and searchable option in web app. Only the clickable on desktop.

**Comment by elexpander** [comment] 2017-05-18 17:00
In my opinion the search bar should search **content and tags** by default. This way you can find any note related to a word even if the word is not part of the note content.

The `tag:` prefix would still be useful if you want to search tags exclusively. Although this feature is already provided by the tag side bar as they said.

**Comment by dmsnell** [comment] 2017-07-12 11:52
I'm going to close this here as a duplicate of #54 more so to merge the requests. We should provide a way to indicate in a search that a given string is specifically for searching tags.

**Closed by dmsnell** 2017-07-12 11:52 UTC
Labels: enhancement
