### ISSUE TITLE
Persistent "Review your account" popup (Windows 2.21.0)

### ISSUE THREAD

**Issue by DrSpaldo** [Automattic/simplenote-electron#3046] opened 2021-11-18 01:43 UTC
### Expected
That the popup "review your account" would only come up once when you confirm your email. 

### Observed
Since updating to version 2.21.0 (Windows), every time I load Simplenote the "review your account" popup comes up every time! I have confirmed my email 3 times and it still keeps coming up.

### Reproduced
1. Update to 2.21.0 (Windows)
2. Load simplenote
3. Cry

### Where did you see the bug
- System Make: PC
- OS: Windows 10
- OS version: 19043.1348
- Simplenote app version: 2.21.0

**Comment by DrSpaldo** [comment] 2021-11-18 01:44
![screenshot 2021-11-18](https://user-images.githubusercontent.com/8526509/142335907-982d4b23-28bc-495a-9475-d87bdfae75a5.png)

**Comment by codebykat** [comment] 2021-11-18 02:34
Hi @DrSpaldo, sorry for the trouble. Sometimes the app gets out of sync with the backend. Can you please try logging out of the app entirely and logging back in (not simply closing it, but logging out from settings)? That should get it to sync up again.

If that doesn't work, kindly drop us a line via support@simplenote.com so we can have a look at your account details and get this straightened out. Thanks!

(Closing as a duplicate of #2647.)

**Closed as completed by codebykat** 2021-11-18 02:34 UTC
Labels: bug

**Comment by DrSpaldo** [comment] 2021-11-18 03:10
That looks like it has fixed it @codebykat. Thanks :)
