### ISSUE TITLE
Show notes without tag -  find "orphans"

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#639] opened 2017-09-30 20:34 UTC
#### Steps to reproduce/understand
I write a lot of notes and any one is supposed to have one single tag in order to assign it to a specific topic. I organize my notes by these topics.

#### What I expected
Show notes without tag in order to find "orphans"

#### What happened instead
This functionality is not yet available.

#### OS version
Windows 10

**Comment by dmsnell** [comment] 2017-09-30 23:31
Thanks for reporting @gubrist - I'm going to mark this as a duplicate of #54 because we had already decided to add an `untagged` menu item.

In general, I want to repeat that we're grateful for your feedback. You have provided many great reports for feature requests/bugs and we're happy to work to make Simplenote more effective for you and everyone else :smile:

**Closed by dmsnell** 2017-09-30 23:31 UTC
