### ISSUE TITLE
Mac Electron revisions slider hard to move

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#1260] opened 2019-05-08 19:50 UTC
### Expected
On  the Mac Electron version, I expected to be able to click and drag the revisions slider to look through note history.

### Observed
Clicking and dragging the slider drags the entire app around. Although you can click in the slider to move to a point, there's no way to tell how many revisions back you are. You have to click exactly on the line to move it, which is difficult.

Also, the slider gets bigger when you go back to a point.

### Reproduced
1. Open a frequently updated note in the Mac Electron app
2. Click on the revisions/history button
3. Try to drag the slider
4. Click a very early revision, to the left

![revisions-mac-electron](https://user-images.githubusercontent.com/31680407/57403896-b2d10d00-71a8-11e9-8d18-848265922921.gif)

MacBook Pro | macOS Mojave, 10.14.4 | Simplenote 1.5.0
MacBook Pro | macOS Mojave, 10.14.4 | Simplenote 1.4.1

**Comment by bummytime** [comment] 2019-05-08 20:17
Ref: #587, #1140, #980

**Comment by mirka** [comment] 2019-05-10 09:37
Duplicate of #898

**Comment by bummytime** [comment] 2019-05-10 13:53
Thanks for the heads up @mirka — closing this issue in favor of #898

**Closed by bummytime** 2019-05-10 13:53 UTC
Labels: [OS] macOS, bug
