### ISSUE TITLE
Linux: Some keyboard shortcuts don't work

### ISSUE THREAD

**Issue by eturkes** [Automattic/simplenote-electron#2488] opened 2020-11-24 13:35 UTC
This issue appears to be specific to my Linux app, I tested it on the web app and Windows 10 and I don't observe the problem.

### Expected

All keyboard shortcuts work.

### Observed

Some keyboard shortcuts do not work (Ctrl+Z, Ctrl+Shift+Z, Ctrl+A), while others do (Ctrl+P, Ctrl+Comma, Ctrl+F). For the non-working shortcuts, the function can still be carried out using the right-click context menu or menu bar. This is a recent issue, but I'm not sure if its related to a recent Simplenote release. 

### Reproduced

1. Try one of the non-working shortcuts (e.g. Ctrl+A).
2. Observe no effect.
3. Try a non-working shortcut using the right-click context menu or menu bar.
4. Observe that it works.
5. Try one of the working shortcuts (e.g. Ctrl+F).
6. Observe that it works.

### Where did you see the bug

- System Make: Lenovo
- System Model: Thinkpad X230 Tablet
- OS: openSUSE Linux
- OS version: Leap 15.2
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.1.0

**Comment by codebykat** [comment] 2020-11-24 18:12
Thanks for the report, I believe this is a duplicate of https://github.com/Automattic/simplenote-electron/issues/2426, though it's odd that you're not seeing it on Windows (it's the same code, and we've had reports of the shortcuts not working on both Linux and Windows). I'm working on a fix this week. Closing in favor of #2426 anyhow.

**Closed as completed by codebykat** 2020-11-24 18:12 UTC
Labels: bug
