### ISSUE TITLE
Data loss after client failed to synchronize

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#332] opened 2016-07-03 11:03 UTC
Simplenote wrote: 

> In the vast majority of cases, Simplenote’s synchronization works great. We handle millions of synchronization requests each day without any problems. But if you do lose your data, even just a single character, and even if it’s not our fault, we want to hear about it. The integrity of your notes is our top priority. Any form of data loss is completely unacceptable.
#### What happened so far
1. I have recently changed the email I use to sign in to my account (from m...@gmx... to m...@posteo...). My hunch is that this transition didn't go well. 
2. Over the course of the last days I have been writing long notes (mostly bug reports), using [the latest Simplenote client for Ubuntu v1.0.2.](https://github.com/Automattic/simplenote-electron/releases/download/v1.0.2/simplenote-1.0.2.deb).  
3. Yesterday I realized, that these notes did not show up on my Android phone (using the Simplenote client for Android v1.4.0), and found, that the the Simplenote client for Ubuntu was not synchronizing. 
4. I logged out the Simplenote client for Ubuntu (File > Preferences > Account > Log Out) and logged back in. 
#### What I expected

I expected the Simplenote client for Ubuntu to synchronize latest modified notes to the server and retrieve changes to other notes from there. 
#### What happened instead

The Simplenote client for Ubuntu started synchronizing from the top, and all _new_ notes that were off-sync have disappeared. They are _not_ to be found with the trash. Note history of _old_ notes does not reflect recent changes. 
### Questions

Where and how are these files stored locally with Ubuntu 16.04? Is there a chance of recovering these notes? I am currently searching locally (using grep) for hidden files containing a unique string used in one of my notes ("kidle_inject"). 
### Suggestion

If the email address change should have caused this client's behaviour, users ought to be advised and/or forcefully logged out of all instances, to avoid data loss. 
#### My Configuration
- Ubuntu 16.04.1 LTS (Xenial Xerus) 64-bit
- Kernel Linux 4.4.0-38-generic
- GNOME 3.18.3
- Memory: 7.5 GiB
- Processor: Intel® Core™ i5-3320M CPU @ 2.60GHz × 4

**Comment by marianoju** [comment] 2016-07-22 17:20
Since this issue has not received any reply in 19 days I have permanently given up on recovering the lost data. I have not been able to find out where the latest Simplenote client for Ubuntu v1.0.2. stores my notes locally. Support has been unable or unwilling to answer my questions in detail. For the record: 

1. Where & how does the Simplenote application locally save notes on Ubuntu 16.04 (64 bit)? Are the files stored in the user home directory? Are the notes stored in one file or several files? Which format is used? JSON? XML? Something completely different?
2. What happens (on the client side) when a note is trashed? Are files *deleted*? Are files *overwritten*? Are backup files kept on the client side?

An automatic periodic plain-text (zipped) backup copy of my notes would have enabled me to recover lost data after the client failed to synchronize, see #271.

**Comment by teemune** [comment] 2016-08-14 06:45
I'm using Windows client and it keeps logging out, without a warning. After I log back in all the changes I've made are gone. This makes the app unusable for me.

Android client stays logged in without a problem.

**Comment by marianoju** [comment] 2016-09-21 14:56
@teemune Not sure this relates to the aforementioned issue, since you're using different (non-Linux) clients and describing a different scenario (i.e. spontaneous log-out).

**Comment by dmsnell** [comment] 2016-09-22 06:24
@marianoju thanks for filing the issue. we really do appreciate it and wish we could attend to replying faster for you. so despite the delay, here is something…

> Where and how are these files stored locally with Ubuntu 16.04?

all of the notes should be stored in the **IndexedDB** instance inside of the Electron app. we don't store the local copies of the notes anywhere on disk. I believe that the IndexedDB database is being stored as a SQLite database, but that's internal to Chromium/Electron and my knowledge is limited there. @beaucollins or @roundhill should be able to correct me if I'm wrong here.

> What happens (on the client side) when a note is trashed? Are files deleted? Are files overwritten? Are backup files kept on the client side?

Trashed notes should set a _trashed_ flag and synchronize with all other clients. we don't guarantee that they will live on forever, but they should remain in the trash bin/folder/tag for at least thirty days. We are currently investigating and trying to resolve these sync issues, so hopefully we can resolve it so that it won't be a continuing problem.

The way the app is designed eschews a local backup to disk, though we offer a zipped download from the website. It may be possible to eventually provide such an export from this client too.

Thanks again for your help in reporting this. We will be tracking the sync issues in our first GitHub project for this app: [Resolve sync issues](https://github.com/Automattic/simplenote-electron/projects/1#card-205905)

**Comment by rohzart** [comment] 2016-09-22 12:12
I'm using the **Desktop App** on **Windows 10** and I've **lost my notes/data** following these below steps:

1. Updated to 1.0.3
2. Noticed that notes weren't syncing at all
3. Logged out and logged back in
4. Notes started syncing but lost almost all my 'un-synced' notes
5. Since, the some of the new local notes did sync (just 2 actually), I think the rest of them are still lying somewhere on my local but I'm clueless how to access them (from: C:\Users\<username>\AppData\Roaming\Simplenote\* )

**Comment by marianoju** [comment] 2016-09-22 13:30
> The way the app is designed eschews a local backup to disk [...] 

@dmsnell I am not sure why you all (including two Happiness Engineer from Simplenote Support) are so adamantly stating that the Simplenote client does not store the notes locally. I don't really care about the technical details, if this happens within the software framework called Electron, if Chromium is involved or not – but while offline the Simplenote application *somehow* has to write the notes *somewhere*. I understand this probably does not happen as plain-text files.

**Comment by dmsnell** [comment] 2016-09-22 17:53
> so adamantly stating that the Simplenote client does not store the notes locally

@marianoju we don't mean to communicate that there's no local copy of the notes somewhere, but storing the data to a local file is something that the app doesn't initiate and doesn't care about. It's all stored in IndexedDB which is handled entirely by the Chromium code inside of Electron. That data for sure lives somewhere in the user directory, but it's also not readily available to us.

I'm less familiar with how Chromium stores its IndexedDB data. We would certainly welcome some knowledge on how to access and extract it.

**Comment by rohzart** [comment] 2016-09-24 13:45
If lucky, you might find a ".bak" file in the folder "C:\Users\<username>\AppData\Roaming\Simplenote\IndexedDB\file__0.indexeddb.leveldb". That's the one which has all lost data just hilariously transposed and weirdly encoded (supposed to be utf-8 but I not by the looks of it). 

If you don't have  a .bak file there, give up. :(

Too much time lost. I need to learn leveldb to extract my data from this point. Any support would be so very welcome. 

Some info to get other a head start: SimpleNote uses Electron (atom shell) which uses Chromium which implements IndexedDB which uses LevelDb (key/value store). I suppose the .bak was created by chromium "cause things could do wrong".

**Comment by dmsnell** [comment] 2016-09-24 14:58
> Some info to get other a head start: SimpleNote uses Electron (atom shell) which uses Chromium which implements IndexedDB which uses LevelDb (key/value store). I suppose the .bak was created by chromium "cause things could do wrong".

what an illustrative statement! it feels like a mess when following the chain like this.

interestingly, I have been recently trying to look into exporting IndexedDB data and _there's no standard way to do it_! it appears like a JSON export is possible by reading in the whole thing but there's no defined way to export the data.

thanks again for the hint @rohzart. we're continuing to try and track down the root cause of this

**Comment by marianoju** [comment] 2016-09-26 06:49
Thanks @rohzart, but I have been unable to find any file containing "indexeddb" or "leveldb" (nor an .BAK file). Since I am using Ubuntu my folder structure differs from yours. I have permanently given up on recovering the lost data two months ago, and abstain from using Simplenote in a productive environment.

**Comment by rohzart** [comment] 2016-09-29 18:53
Hello @marianoju, I got an ubuntu VM running, installed simplenote and found that the equivalent path for ubuntu: "/home/<username>/.config/Simplenote/IndexedDB/file__0.indexeddb.leveldb/". This just took me 15mins to figure out and I really hope you find a ".bak" file there. I have made a copy of that and kept it aside to try recover my data as and when I get time. I'll update this thread as and when I do.

@dmsnell : You're welcome. Is anyone looking into helping people recover data while I know for sure there's a prrretty good chance of successful recovery (using the same ".bak" file)? Also, I'm more inclined towards using levelDB to work with those files' data and not indexedDB. Please do correct me if I'm headed in the wrong direction.

**Comment by dmsnell** [comment] 2016-09-29 19:01
@rohzart right now we're spending our available time finishing up a few small but old issues and the rest of that available time trying to understand the synchronization issue first. data loss isn't something we take lightly, but if we can restore the sync process that might alleviate the data loss problems enough to give us a chance to figure it out (the two issues could be commingled)

I want to let you know that we think it's wonderful how helpful you have been here. thanks a million!

**Comment by marianoju** [comment] 2016-09-29 21:11
Thanks @rohzart! I followed your lead and found some BAK files in the
directory you indicated. However they display timestamps of modification
long *after* the data loss event, so I doubt that it would be possible
to restore any of the lost data from these files. Oldest file is from
September 5th (data loss was two months prior).

I appreciate your effort in pointing me in the right direction, but the
“need to learn leveldb to extract my data from this point” as you
mentioned is beyond what I am willing to invest. To much time lost
already. If I understand @dmsnell correctly nobody is currently “looking
into helping people recover data”.

**Comment by rohzart** [comment] 2016-10-31 17:21
I did learn to work with leveldb and when I attempt to connect/open the database directly using level npm package in my nodejs program, it fails since the default comparator "idb_cmp1" is different from what was used to "encrypt" the database. In the code below, the second line throws this error.
```
var levelup = require('levelup')
var db = levelup('./<path to your database>/file__0.indexeddb.leveldb')
```
At this point, @dmsnell , I'm curious if you know how (or where from) one could retrieve the comparator that simplenote sets for setting up the leveldb?

@marianoju : You may use [levelui](https://github.com/0x00A/levelui) to work with the database. This works well on ubuntu and doesn't need you to learn leveldb. I haven't been able to run this on windows and I might try it on ubuntu "someday". So, I'm not sure if this would help retrieve your data but I guess it's worth a try.

**Comment by dmsnell** [comment] 2016-10-31 18:44
@rohzart unfortunately I don't know what that is using or if we even set it. my guess is that the browser is making those decisions for us.

have you had access to a development build of the app wherein the developer tools are enabled? with those you can directly access the IndexedDB data without trouble. using the console it would be possible to pull out the data, though maybe only with a bit of finagling. if you don't, we'll get you a binary soon if you are interested.

**Comment by dmsnell** [comment] 2016-10-31 20:04
@rohzart here is a link to the debug-enabled version. when you open it you should have access to the developer tools where you can inspect the data in IndexedDB directly.

https://cloudup.com/i0WtqAodryF

^^^ thanks @roundhill for making that binary!

**Comment by rohzart** [comment] 2016-12-03 12:46
I've not been able to attend to this since long and I'm giving up. :/ Thank you @dmsnell, @marianoju. Cheers.

**Comment by dmsnell** [comment] 2017-07-12 11:46
Looks like I forgot to mention it here explicitly, but #448 added an export feature to get all notes out from the app into a zip archive containing the plaintext notes as well as a JSON export of the entire collection.

Because we have few specific details to work with on the sync loss I'm going to close this specific issue but please know we are continuing to work to make sure information loss doesn't occur. In other words, I'm folding this issue into the larger topic of handling synchronization well when logging out and logging in.

Thanks all for the help and comments. I hope that you find the export functionality useful. We're also planning on building a similar import method soon.

**Closed** 2017-07-12 11:46 UTC
Labels: bug

**Comment by GitarMan** [comment] 2018-01-06 02:31
Just lost the past month's worth of notes due to this same issue on MacOS. Desktop wasn't syncing with online or my phone. Logged out and logged back in. All my notes were gone.

Just upgraded to the latest version so hopefully it's fixed now. The notes must have been stored locally somewhere, but I can't find where. I guess they were cleared out when I logged out?

This was all pretty frustrating. If this happens again, I'm going to have to switch to something more reliable. It's a shame because I really love the simplicity of this app.

**Comment by marianoju** [comment] 2018-02-16 12:03
> This was all pretty frustrating. If this happens again, I'm going to have to switch to something more reliable. It's a shame because I really love the simplicity of this app. 

What he said.

**Comment by GitarMan** [comment] 2018-02-16 23:31
@marianoju Switched to Google Keep. More features, most of which I barely use, but it integrates into some Google products, and I trust the tech not to fail.

**Comment by mofahead** [comment] 2019-11-07 04:13
Love Simplenote's interface but I've lost data too many times now.

**Comment by working-name** [comment] 2020-08-15 13:22
Guys, **DO NOT SIGN OUT** before you save your notes that don't sync over. In my view the equivalent of that would be copying the long text you typed in a textarea before refreshing the page.

I've bumped into sync issues like this before with other software and the first thought was always "gotta backup what I have now". 

That being said I'm sure they'll resolve all the sync bugs to where a user will never be in that situation again.
