### ISSUE TITLE
Ctrl+L to toggle search field focus

### ISSUE THREAD

**Issue by owcz** [Automattic/simplenote-electron#412] opened 2016-10-23 05:48 UTC
Modifier key + L is a common shortcut to the app search bar (most web browsers even in Linux, the native Simplenote OS X app, etc.) I see that Ctrl+F does that function right now (#301), but that's more expected for internal search within a note than for all notes. It's also strange to have the same function assigned to different letters across platforms.

**Comment by dmsnell** [comment] 2016-10-27 21:07
@drw158 what do you think about this? <kbd>ctrl+l</kbd> seems to jive with browser notions of controlling navigation. plus, the native Mac app already uses this binding. maybe it was simply overlooked?

**Comment by drw158** [comment] 2016-10-31 16:57
We differ from the Mac app because it didn't make sense at the time to focus the search field with ctrl L. It seemed unintuitive, especially since we don't currently have searching within notes. I know it's standard to focus the search field on browsers with ctrl L, but I think we should be looking more at other apps, writing apps. 

**Ulysses** 
- shift+command+F: search notes
- command+F search within note

**Slack** 
- command+F search bar

**Evernote** 
- alt+command+F: search notes
- command+F search within note

**Comment by dmsnell** [comment] 2017-01-30 02:46
Closing as a duplicate of #301

**Closed by dmsnell** 2017-01-30 02:46 UTC
Labels: enhancement, question

**Comment by owcz** [comment] 2017-07-07 20:19
mod+F is most often used to search _within_ a document, as it is on webpages and as is in Evernote/Ulysses. If mod+F invoked a simultaneous view of all hits (as it does in Slack), I could see the parallel.

This isn't a complete duplicate of #301—once that ticket adds "search within note" alongside the existing electron all-notes-search, they'll need different keyboard shortcuts, hence why the SN macOS native app assigns "search within note" to Cmd+F and all-notes-search to Cmd+L. I think it's smart to extend the native app's paradigm to the electron app ("L" signifying that the all-notes-search is similar to a browser's location bar). But at least it should be made consistent when 301 is resolved, right?
