### ISSUE TITLE
Keyboard shortcuts for switching between notes

### ISSUE THREAD

**Issue by Topy44** [Automattic/simplenote-electron#597] opened 2017-08-08 17:43 UTC
New user, liking it so far. Unfortunately the Windows application's keyboard support is lacking.
I would love to see shortcuts to switch between notes. Suggestions would be Alt+Up/Alt+Down or, more standard but much less convenient, CTRL+Tab/CTRL+Shift+Tab for selecting the previous/next note in the list.

**Comment by dmsnell** [comment] 2017-08-21 16:14
Closing here as a duplicate of #37 - check back soon for updates in v1.0.9!

**Closed by dmsnell** 2017-08-21 16:14 UTC
