### ISSUE TITLE
the menu bar follows system theme not simplenote theme

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#1972] opened 2020-03-18 17:43 UTC
windows 10
i set system theme to dark in settings
but simplenote theme to white
this is what happens
![image](https://user-images.githubusercontent.com/21956756/76990304-0921e700-6948-11ea-8b5e-d379c8c5bfe8.png)

### Expected:
the menu bar theme should follow the simplenote theme

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Go to windows settings,  personalisation, colors
> 2. Set OS theme to dark, but simplenote to white
> 3. see the screenshot

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
-|-|-|-
Windows|10|10|1.15.1
![image](https://user-images.githubusercontent.com/21956756/76990229-e98abe80-6947-11ea-9405-0d740af9c8ae.png)

**Comment by rachelmcr** [comment] 2020-04-22 08:12
I noticed the same issue but with opposite settings (system theme light, Simplenote theme dark):

![Screenshot 2020-04-22 09 09 03](https://user-images.githubusercontent.com/8658164/79957280-3d258600-8479-11ea-9047-f639b95ddf50.png)

Observed on VirtualBox VM with Windows 10, Simplenote Electron app v.1.16.0-beta1.

**Comment by codebykat** [comment] 2020-06-04 06:35
I think this is a dupe of #1799

**Closed by codebykat** 2020-06-04 06:35 UTC
Labels: [OS] windows, [feature] dark mode, bug
