### ISSUE TITLE
Linux note editor: Korean consonants and vowels represented separately

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#745] opened 2018-04-09 15:33 UTC
This issue was raised in 1040852-zen

#### Steps to reproduce

1. The user installed Simplenote for Linux using the `simplenote-linux-1.1.3.deb` package
2. Latin characters are rendered correctly.
3. Korean characters are not rendered correctly (user's explanation below).

#### What I expected

For Korean characters to be rendered correctly.

#### What happened instead

From the user's report:

>I downloaded the simplenote package from the website.
>(simplenote-linux-1.1.3.deb)
>I installed the app on my ubuntu os successfully.
>
>Everything is find except typing non-english character.
>When I try to type Korean character, it typed weirdly.
>
>For example, I would like to type "한글", but it typed "한ㄱㅡㄹ" on the editor. The problem is consonants and vowels are inputted separately.

>To input Korean character, I'm using IBusHangul package and my keyboard layout is Hangul keyboard Dubeolsik.

#### OS version

To be confirmed.

#### Related issues

These issues appear to be related:

https://github.com/Automattic/simplenote-electron/issues/561

https://github.com/Automattic/simplenote-electron/issues/560

**Comment by rumahrumah** [comment] 2018-09-22 22:04
When I try to add a tag in Korean, one stroke produces two characters.
![2018-09-23 07-02-22](https://user-images.githubusercontent.com/14152092/45922133-d471d280-befe-11e8-8936-0a1b093bf95a.png)

I guess it's related to this issue.
I'm using Simplenote 1.1.7 on Ubuntu 18.04.

**Comment by mirka** [comment] 2018-11-09 21:05
I confirmed this issue on Ubuntu 18, Simplenote v1.2.1. Typing the key sequence `gksrmf` seems to produce the characters `한글` in Text Editor, Firefox, etc., but this fails in Simplenote. Japanese is working fine. I would like to know if Chinese is working.

Also, this does not happen on Windows or Mac.

**Comment by mirka** [comment] 2018-11-09 21:06
> When I try to add a tag in Korean, one stroke produces two characters.

@rumahrumah Thanks for the report! This is a different issue and will be fixed in #999.

**Comment by nemonein** [comment] 2018-12-20 03:07
I tested 1.3.4 on KDE Neon(Kubuntu 18.04 based Disto).
Kubuntu's default input system(for Far east Asian languages) is fcitx. I used fcitx and fcitx-hangul(Korean engine).

I can't say it works fine.
![simplenote-20181220](https://user-images.githubusercontent.com/5688288/50261074-38e4f500-044e-11e9-8535-6b37b3b93a82.gif)

In the gif, the first paragraph shows the right text, and I retype it on the second paragraph.
As you can see, there's some lagging(?) at the beginning of the each line. Those are not my typo.

However, it does not happen when I use other input system, [Nimf](https://gitlab.com/nimf-i18n/nimf).
I have not tried with iBus, etc.

I don't know why this happens. I don't even know who is responsible for this.
All I can say is, fcitx is a 'default' input system for Kubuntu, and Nimf is not mainly used.

**Comment by palindrom615** [comment] 2019-02-04 09:34
I guess I have found the cause of bug! It seems that the bug does *not* come from simplenote-electron itself *but* [draft-js](https://github.com/facebook/draft-js) and electron.

I have reproduced the bug with electron and draft-js only.

![my own reproduction of bug](https://user-images.githubusercontent.com/10936496/52200001-eb600280-28aa-11e9-85aa-dd7a17be0ed1.gif)

I will report this bug on draft-js repo and contribute if I can.

**Comment by mirka** [comment] 2019-02-05 11:34
Thank you so much for looking into this @palindrom615. Seems like this probably can only be addressed in either DraftJS or Chromium itself. There are some nasty interactions between CJK composition and contenteditable and DraftJS 😭 (Like this one: #1171)

**Closed by mirka** 2019-02-05 11:34 UTC
Labels: [OS] linux, bug, help wanted, i18n
