### ISSUE TITLE
Copy-Paste without line breaks (Electron 1.0.8.)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#512] opened 2017-02-02 20:16 UTC
#### Steps to reproduce
1. Copy a note containing line breaks (carriage return) with [ Ctrl + C ]  within Electron 1.0.8
2. Paste it into Windows Text Editor

#### What I expected
As previous versions of Electron, I expect to get al legible text with line breaks.

#### What happened instead
A text without line breaks.

#### OS version
Windows 10

#### Screenshot / Video

![no line break 02 02 2017](https://cloud.githubusercontent.com/assets/22197180/22566582/d975c9ec-e98c-11e6-9e30-195b78d54e15.JPG)

**Comment by dmsnell** [comment] 2017-02-02 20:23
Thanks for the report @gubrist and I hope this didn't interrupt your flow too much!

@Copons maybe we missed the fact that Windows apps still use `\r\n` as newlines and we need to coerce this format [when we fill the paste buffer](https://github.com/Automattic/simplenote-electron/pull/480/files#diff-d65a368b0648bee7bc77b758399fb23cR171)

something like `selectedText.replace( /(?![\r])[\n]/, "\r\n" )` maybe (negative-lookahead `\r` followed by `\n` meaning "replace all newlines not preceded by a carriage return with a `\r\n`)

**Comment by Copons** [comment] 2017-02-03 11:52
Ouch @dmsnell I assumed the newline differences ware handled directly on a OS level.
Opening a fix ASAP, but I'm currently not in the conditions for testing on Win.

**Comment by gubrist** [comment] 2017-08-24 16:56
![copy-paste without line breaks 2a](https://user-images.githubusercontent.com/22197180/29677961-1e5803f8-88fd-11e7-8528-8cbc97c0e488.JPG)
![copy-paste without line breaks 2b](https://user-images.githubusercontent.com/22197180/29677964-1ff0d230-88fd-11e7-8836-da3758ea5f98.JPG)
![copy-paste without line breaks 2c](https://user-images.githubusercontent.com/22197180/29677970-22596cc6-88fd-11e7-994f-101ecefff5db.JPG)

Thanks, the line brake problem seems to be on the classic Wind Text editor 
(still running under Windows 10; see 1st image).

You can resolve it by using an comprehenisve Text Processor such as open Office.

On the other hand, there is an issue with ä, ö, ü etc. (see 3rd image).
- Which is the right charset to be applied?

**Comment by dmsnell** [comment] 2017-08-24 17:16
@gubrist the output should be in UTF-8 encoding, with simple newlines, in the picture that would just be `LF` and probably `UTF8` or `UTF-8`

**Comment by dmsnell** [comment] 2017-08-24 17:17
We could potentially detect the host operating system and normalize the line endings accordingly but I have some other concerns about that too. Let's do some research on how other paps do this when saving plaintext files.

**Comment by gubrist** [comment] 2017-08-24 17:32
a) Detecting the host operating system and normalize the line endings accordingly is a good idea 👍 

b) For the meanwhile work-around, the UTF-8 workes - thank you: 

![copy-paste without line breaks 3a](https://user-images.githubusercontent.com/22197180/29679737-b83331f0-8902-11e7-8620-25a06f8ab134.JPG)
![copy-paste without line breaks 3b](https://user-images.githubusercontent.com/22197180/29679741-bc6ebf46-8902-11e7-8836-a4b7a4b406fa.JPG)

**Comment by codebykat** [comment] 2020-05-01 00:29
Same issue reported in 2932509-zen

**Comment by codebykat** [comment] 2020-09-22 03:56
Can't reproduce this in the latest version with Windows 10 / Chrome. I don't have Windows 7 but I'm going to close this since it was probably fixed by switch to Monaco (#2148) and the code path discussed above is now super outdated. Let's reopen if we get any new reports.

**Closed by codebykat** 2020-09-22 03:56 UTC
Labels: bug
