### ISSUE TITLE
Keyboard shortcut for 'Search Notes' doesn't work

### ISSUE THREAD

**Issue by hoverduck** [Automattic/simplenote-electron#507] opened 2017-01-30 20:11 UTC
#### Steps to reproduce
1. Open Simplenote
2. Press CTRL-F
 -- or --
2. Navigate to the menu option Edit -> Search Notes

#### What I expected
To have keyboard focus given to the search field

#### What happened instead
Nothing

#### OS version
Tested on Simplenote v1.0.8 on Windows 10 and Linux Mint 18

**Comment by roundhill** [comment] 2017-01-30 23:03
Thanks @hoverduck! Picking this up, looks like an easy fix.

**Comment by dmsnell** [comment] 2017-01-31 04:40
Also a dupe of #301 - closing to keep issues organized

**Closed by dmsnell** 2017-01-31 04:40 UTC
Labels: bug, duplicate, [OS] linux, [OS] windows
