### ISSUE TITLE
Cursor Jumps to behind fixed keyboard on Windows tablet

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#1950] opened 2020-03-10 10:16 UTC
### Expected
I would expect that when I start editing a note, the cursor would stay on screen so I can view the edits being done. 

### Observed
User reports: "As soon as I start editing a note on a touch screen, the cursor jumps to the bottom of the screen and thus behind the touch keybord – I can only edit the note without seeing what I’m typing."

### Reproduced

We haven't been able to reproduce this so far, but the following is reported:

"It appears to depend on the specific note. I have been using
rather long bullet point lists that have been created in previous
versions and modified on various devices. The issue occurs reproducibly
on the tablet with these notes, it is different though with a new note
that I have created for this purpose.

I have prepared screenshots with a new note and the default keyboard
anyway. With using the floating keyboard, the cursor stays where I put
it (fig 1). With the fixed keyboard, the cursor jumps behind the
keyboard after pressing Enter (fig 2) and just above the keyboard when
starting to type in the new line (fig 3). With my earlier notes, the
cursor jumps further down behind the fixed keyboard and does not appear
when I start to write." 

![Capture1](https://user-images.githubusercontent.com/10325627/76302318-ab422f00-62b7-11ea-941b-3b3f63db00c0.JPG)
![Capture2A](https://user-images.githubusercontent.com/10325627/76302325-ad0bf280-62b7-11ea-874e-9f0d23b6e308.jpg)
![Capture3A](https://user-images.githubusercontent.com/10325627/76302336-af6e4c80-62b7-11ea-9505-093753943ba2.jpg)

Make|Model|OS Version|App Version
-|-|-|-
Windows Tablet | Lenovo Ideapad/ Lenovo TAB 10|recent Windows versions (1909)|1.14

Reported in 2737975-zen

**Comment by belcherj** [comment] 2020-09-22 15:54
I have tested this on a Windows Surface X on Windows 10 and have not bee able to reproduce. Closing for now as we are unable to reproduce.

**Closed by belcherj** 2020-09-22 15:54 UTC
Labels: bug
