### ISSUE TITLE
2.2.0 Windows Input Text Err

### ISSUE THREAD

**Issue by 793383996** [Automattic/simplenote-electron#2509] opened 2020-12-08 04:35 UTC
Sometimes the first letter disappears when the text cannot be typed properly on the Windows platform.
Reopen it's ok.

**Comment by codebykat** [comment] 2020-12-09 23:34
@793383996 I'm not sure what this means, can you provide some screenshots to illustrate the problem? Thanks 😄

**Comment by codebykat** [comment] 2020-12-21 21:50
I think this is a probable duplicate of #2522

**Closed as completed by codebykat** 2020-12-21 21:50 UTC
Labels: bug

**Comment by 793383996** [comment] 2021-01-08 11:53
2.0 is ok
