### ISSUE TITLE
Simplenote on Linux does not display in the system language

### ISSUE THREAD

**Issue by damiongans** [Automattic/simplenote-electron#563] opened 2017-06-01 04:56 UTC
#### Steps to reproduce
1. Install Simplenote
2. Open Simplenote
3.
4.

#### What I expected
My system is installed in Dutch, so I was hoping Simplenote to be Dutch too

#### What happened instead
Simplenote displayed in English, without an option to change it.

#### OS version
Manjaro Linux (arch) x64 fully updated

**Comment by dmsnell** [comment] 2017-06-01 13:53
Thanks for raising this @damiongans - we don't currently have translations available for Simplenote, though we would love to and plan on it at some point.

**Comment by damiongans** [comment] 2017-06-01 15:27
The Android version is available in Dutch, so maybe you can port that easily to the desktop app?

**Comment by dmsnell** [comment] 2017-06-01 15:32
> The Android version is available in Dutch, so maybe you can port that easily to the desktop app?

I wish we could @damiongans - the problem is that we don't have the translation infrastructure built-in to the app. If we had it we could probably do that. This might actually be a reasonably good project for someone wanting to help out with a "manageable chunk" of work.

Unless I'm mistaken, we could accomplish this with these broad steps:
 - Pull in a translation wrapper such as automattic/i18n-calypso or any other popular one that fits with the project
 - Build an Electron-based provider for the translation files. We probably wouldn't want to load them from the network on every load of the app. We might ship them with the distribution, for example, or might cache them and routinely update them.
 - Wrap all text in the translate wrapper

**Comment by drw158** [comment] 2017-06-01 16:53
I will cross link the main localization issue: #16 

Closing because this is a dupe.

**Closed by drw158** 2017-06-01 16:53 UTC
Labels: duplicate
