### ISSUE TITLE
Keyboard shortcut for toggling markdown preview

### ISSUE THREAD

**Issue by EJOweb** [Automattic/simplenote-electron#306] opened 2016-04-30 08:00 UTC
Adding a keyboard shortcut for switching from markdown to preview and vice versa would be nice. Maybe CTRL + M(arkdown) or something?

**Comment by prat0088** [comment] 2016-06-14 14:21
CTRL+M would be great.

**Comment by sambody** [comment] 2016-06-14 18:50
In the desktop app, Ctrl+M is already used to minimize the desktop app (Windows 10). 

And in the web version on Firefox, Ctrl+M is used to mute the current page. So it will probably have to be another shortcut.

**Comment by prat0088** [comment] 2016-06-14 22:58
Ok. As long as it gets a shortcut I'm happy.

**Comment by jcrben** [comment] 2017-03-11 18:01
Ideally keyboard shortcuts are configurable.

**Comment by guilsa** [comment] 2017-04-27 23:11
Why not treat Edit/Preview like browser tabs, so switching between them can be Cmd + Shift + [ OR ]

**Comment by dmsnell** [comment] 2017-07-12 12:00
How do y'all feel about making it a kind of print-preview shortcut like <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>?

Candidates:
 - <kbd>CmdOrCtrl</kbd> + <kbd>M</kbd> already mentioned that it is used
 - <kbd>CmdOrCtrl</kbd> + <kbd>[</kbd> it doesn't really feel like browser tabs, and I don't think we need two keys whereas a toggle feels right. Further, if we decide to open a live preview on wide displays I think the single-key toggle would fit better with "open or close preview."

@drw158 do you like this idea?

**Comment by drw158** [comment] 2017-07-12 16:18
That idea sounds great to me. `p` as in `preview` or `p` as in `print`. Easy to remember.

**Comment by dmsnell** [comment] 2017-08-21 16:15
Closing here as a duplicate of #37 - check back soon for an update in v1.0.9!

**Closed by dmsnell** 2017-08-21 16:15 UTC
