### ISSUE TITLE
CTRL + Z doesn't work after toggling markdown

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/simplenote-electron#2467] opened 2020-11-11 22:04 UTC
After switching markdown mode to on, changes made in note editor cannot be undone with CTRL + Z keyboard shortcut. 

### Expected

* Changes to be undone after undo/redo keyboard shortcut entered

### Observed

No action is taken after pressing CTRL + Z after making changes after enabling markdown. 

### Reproduced

1. Go to a note with markdown not enabled 
2. Enable markdown mode
3. Make changes
4. Press CTRL + Z
5. Observe changes are not undone. 

### Where did you see the bug

- System Make: HP Envy
- OS: Windows 10
- Simplenote app version: 2.1.0-beta2

**Comment by codebykat** [comment] 2020-11-12 02:46
Thanks @JavonDavis, I think this is a duplicate of #2426. Good additional info on the Markdown switch. I'm looking into it 😅 

Can you tell me if you're able to undo edits after making changes using the file menu (File -> Undo)? What about the right click menu?

**Closed as completed by codebykat** 2020-11-12 02:46 UTC
Labels: bug
