### ISSUE TITLE
Duplicated Characters/Text on Mobile Browser

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-electron#2341] opened 2020-09-22 04:01 UTC
When typing in a text in the title and hitting newline, it will duplicate the title on the next line.

Typing a word in the body content also duplicate the word/characters and produce some other errors related to cursor.

User's exact word of report:

> I typed "BETA" for the title and hit newline. It duplicated "BETA" on the next line. I tried to type "Unusable" and it typed "UNUUNNUUUUNUUUUUN..." as I tapped the Shift Key and tried to enter other characters or control keys like Backspace besides "U" or "N".

Per @dmsnell comment [here](https://github.com/Automattic/simplenote-electron/issues/2030#issuecomment-693747809): 

> looks like maybe something on the mobile browser is creating multiple cursors and then edits apply twice.

### Expected
There should be no duplicate words or lines. 

### Observed
Words/characters become duplicated. Some other cursor-related functions also don't work. 

### Reproduced
1. Start a New Note.
2. Enter "BETA" in the Title. 
3. Tap Newline. 
4. IT (the BETA) entered "BETA" on the new line. 
5. Tap Backspace to (try to) erase "BETA" and IT didn't. Instead IT entered what we see on the screenshot below which resulted from multiple taps on only Backspace.

(The screenshot appears to show several Newlines which I may have entered after the second "BETA" which I then followed with a series of only Backspaces.)

Screenshot: 

![Screenshot_20200916-051326](https://user-images.githubusercontent.com/1813857/93403788-aa1b3b80-f8b2-11ea-9a2a-d2d8f6dfced9.png)

Another screenshot that shows the other errors:

![Screenshot_20200916-054552](https://user-images.githubusercontent.com/1813857/93403763-a38cc400-f8b2-11ea-9794-2fa7c867be0f.png)

### Where did you see the bug
- System Make and Model: Moto g5 Plus
- OS: Android
- OS version: 8.1.0
- Browser version (if applicable): Firefox Daylight 80.1.3 and Chrome 85.0.4183.81
- Simplenote app version: current https://staging.simplenote.com/

User noted that it works on https://app.simplenote.com/ (meaning the issue doesn't happen there).

Reported on 3317478-zen

**Comment by codebykat** [comment] 2020-09-22 04:44
Just noting I can't duplicate on Firefox / iOS so far, might be something Android specific?

**Comment by theck13** [comment] 2020-09-22 13:22
We may want to ask about the red navigation and status bars in the screenshots.  That can indicate that the device has Battery Saver enabled, which can affect how all apps on the device work.  The red navigation and status bars could be something else for their specific device, but clarifying that may help with troubleshooting.

**Comment by msilbers** [comment] 2020-09-27 16:37
I have asked them about Battery Saver mode.

cc @erricgunawan

**Comment by erricgunawan** [comment] 2020-09-28 02:06
Ah, I missed this, sorry. Thanks, both @theck13 and @msilbers!

**Comment by reginabally** [comment] 2020-09-28 03:33
Battery Saver mode turned off with the following test results but these were tested on https://app.simplenote.com.

> Using Chrome 85.0.4183.127 and https://app.simplenote.com/login/, I started a New Note. I typed "Chrome 8" and Simplenote wouldn't accept any more characters. See screenshot. I wanted to type "Chrome 85.0.4183.127".

![Screenshot_20200927-195224](https://user-images.githubusercontent.com/40906847/94387285-4af3db80-017c-11eb-80ad-8acc8ac1c3f9.png)

Replicated on OPPO Reno 4, Android 10, and Chrome 85.0.4183.127 and it looks like there are two cursors on screen after I started typing on the new note. Video recording: https://d.pr/v/k1Nnk9

> Using Firefox Daylight 81.1.1 and https://app.simplenote.com/login/, I started a New Note. I typed "Firefox " and Simplenote added the second "Firefox" when I typed the " " (space). I didn't try to type any more characters. Then I was interrupted and when I returned the keyboard was gone and couldn't be opened. See screenshot. I wanted to type "Firefox Daylight 81.1.1".
Lastly, I repeated the above with Firefox and typed only "Firefox Daylight" and Firefox provided the rest.

![Screenshot_20200927-195644](https://user-images.githubusercontent.com/40906847/94387334-724aa880-017c-11eb-9678-4b9538b033cb.png)

![Screenshot_20200927-203213](https://user-images.githubusercontent.com/40906847/94387364-82fb1e80-017c-11eb-83e9-e0c4cb6835d4.png)

Replicated on OPPO Reno 4, Android 10, and Firefox Daylight 81.1.1. Video recording: https://d.pr/v/nuebR8

**Comment by erricgunawan** [comment] 2022-06-10 09:34
> Some strange things happened in my iPhone.
>
> I type "abcde" and enter, It was displayed "abcdeabede"
>
> I type "12345" and enter, it displayed "123512345"
>
> Automatically Double typing!
>
> In PC it does not happen.
> In iPhone it only happen.

>It happen in both English and Japanese.

https://user-images.githubusercontent.com/1813857/173036675-278fca15-3baf-412d-89f4-65018e852219.mov

Machine: iPhone 7
OS: iOS 15.5

(Confirming what browser is used)

5239292-zen

**Comment by codebykat** [comment] 2022-06-14 04:43
Since it apparently hasn't been stated in this thread, Monaco (the editor used in Simplenote web) is [officially unsupported](https://github.com/microsoft/monaco-editor/issues/246) on mobile browsers. While it might still be interesting to track down the cause / reproduction steps, let's be sure to advise folks that they would have more luck downloading the Simplenote app for their device. Not everyone who tries to use it on mobile web will have issues, but for those who do, using the app is likely the easiest fix.

**Comment by erricgunawan** [comment] 2022-06-16 02:22
>  let's be sure to advise folks that they would have more luck downloading the Simplenote app for their device.

Yes, I should have mentioned I noticed the user in 5239292-zen was using the mobile web version and they were having another issue (copy and paste). 

So I suggested them to use the native iOS app and it worked well! 🎉

Here is their response:

> I use web version Simplenote.
>
> I download native apps and I can copy&paste !
>
> And It finished double typing error.

**Comment by codebykat** [comment] 2024-05-09 20:25
Closing because we've disabled multicursor on Monaco and because we advise folks to use the native app instead of mobile.

**Closed as completed by codebykat** 2024-05-09 20:25 UTC
Labels: bug, mobile
