### ISSUE TITLE
Shift+DownArrow doesn't work on a line above a checklist item

### ISSUE THREAD

**Issue by laskin82** [Automattic/simplenote-electron#1200] opened 2019-02-12 12:11 UTC
#### Steps to reproduce
1. Create note
2. Create strcture of note with checklist
3. Try to select text under cursor

#### What I expected

Selected text

#### What happened instead

Cant select

#### Simplenote version

1.4.1

#### OS version
Win 10 x64 1909

#### Screenshot / Video

![ezgif-4-b4ef2fd8393c](https://user-images.githubusercontent.com/16285422/52634489-6abb8a80-2ed8-11e9-9aee-6925803a75f8.gif)

**Comment by qualitymanifest** [comment] 2019-02-15 01:56
I can duplicate this, it seems to be specific to the checkboxes. I noticed that if you move the cursor over so that you wouldn't select a checkbox it works okay until you encounter another group of checkboxes (since the cursor is back at the beginning of the line). 

It works fine if you select by clicking and dragging over text, it only seems to be a problem when using shift + arrow keys.

![q8l88-mvee5](https://user-images.githubusercontent.com/13897419/52829372-84a4cb00-309a-11e9-899d-bef12d155d77.gif)

**Comment by laskin82** [comment] 2019-02-15 05:31
I got it. I just do not use the mouse and work mostly from the keyboard when editing a note.

**Comment by qualitymanifest** [comment] 2019-02-15 05:53
I understand, I’m just providing more details about what works/doesn’t work

**Comment by mirka** [comment] 2019-02-15 22:14
This is caused by the fact that technically, the caret cannot be positioned at offset 0 when a checkbox is at the beginning of the line. A fix will likely require a listener on <kbd>Shift+DownArrow</kbd> that calculates an adjusted caret position.

For keyboard users, a temporary workaround is to use <kbd>Opt+Shift+RightArrow</kbd> instead.

**Comment by dmsnell** [comment] 2020-09-21 22:05
Resolved in #2148

**Closed by dmsnell** 2020-09-21 22:05 UTC
Labels: [feature] checklist, [feature] editor, bug, keyboard
