### ISSUE TITLE
After creating new account, window remains, content loads there

### ISSUE THREAD

**Issue by topher1kenobe** [Automattic/simplenote-electron#290] opened 2016-04-08 17:01 UTC
I installed via apacman in Arch Linux, fired it up, and clicked to create a new account.  A new window opened, I filled out the form, my account was created, and simplenote loaded in that small window. The main window remained at a login page.
![selection_278](https://cloud.githubusercontent.com/assets/341412/14391431/f5289010-fd89-11e5-96ae-e621b166bd85.png)

**Comment by soren121** [comment] 2016-04-08 23:33
Duplicate of #277, although this one does have a screenshot!

**Comment by dmsnell** [comment] 2017-09-21 21:02
Closing here since we started allowing registration from within the app itself.

Please reopen if you feel the problem remains after `v1.1.0` is released. Thanks as always for your help!

**Closed by dmsnell** 2017-09-21 21:02 UTC
Labels: bug
