### ISSUE TITLE
RESTful search on the web app

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2477] opened 2020-11-17 03:06 UTC
Requested in 3491662-zen.

> I would like to be able to access the page showing
> "tags:Diary" with something like:
> 
> https://app.simplenote.com/?q=tags%3ADiary
> 
> The current status quo is unfortunate for the resource representation
> therefore being an implicit client-side document state, to which
> transition is impossible via pure hypertextual facilities, but only
> manifest via specific DOM-side interaction, implying GUI.

### What

> More genrally, allowing for such representation and transation/recovery
of document state would be great:

> https://app.simplenote.com/notes/any-note-slug-or-id-or-whatever-opened?q=some-search-words

### Why

> Fixing the above would also allow app resources and document state to be
representable on whichever restful API, and embrace all the goodness of believing in REST-ful-ness.

**Comment by codebykat** [comment] 2020-11-17 15:22
A somewhat confusingly worded duplicate of https://github.com/Automattic/simplenote-electron/issues/1635

**Closed as completed** 2020-11-17 15:22 UTC
Labels: feature request
