### ISSUE TITLE
Add date with notes title.

### ISSUE THREAD

**Issue by arkniazi** [Automattic/simplenote-electron#1699] opened 2019-11-07 09:03 UTC
### What
Please add date with title.

### Why
Because if I want to check when the note was created I have to open it and check it info. Which makes it complicated.

### How
Just copy the date from info tab to place below the notes title.

**Comment by dmsnell** [comment] 2019-11-08 02:55
Thanks for asking @arkniazi - I'm closing this as a duplicate of #599

**Closed by dmsnell** 2019-11-08 02:55 UTC
Labels: feature request
