### ISSUE TITLE
Characters Duplicating in Text of Note

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2391] opened 2020-10-11 17:23 UTC
### Issue:

Random text duplicates while the user writes in Android Simplenote app

### Example:

133 / 90 (9am) transforms to 1133 / 990 (99a9am)

### Further Details

Unable to reproduce. 
User reported:
Simplenote Version: 2 0 0-beta 1
#3386461-zen

**Comment by theck13** [comment] 2020-10-11 17:37
I'm moving this to the [simplenote-electron](https://github.com/Automattic/simplenote-electron) repository since the screenshots shared by the user are from their mobile browser and the Simplenote version they shared was 2.0.0-beta1, which is for the Electron app.  There is no 2.0.0-beta1 version of Simplenote Android.  The current Simplenote Android version is 2.11.0.

**Comment by rezzap** [comment] 2020-10-13 10:13
I've suggested the user try downloading the Android app instead of using the web app on their device. They are looking at alternatives apps for now though.

**Comment by codebykat** [comment] 2020-10-15 23:45
Looks like a duplicate of https://github.com/Automattic/simplenote-electron/issues/2386

**Closed as completed by codebykat** 2020-10-15 23:45 UTC
