### ISSUE TITLE
Hitting "Add Note" after searching for a note that doesn't exist doesn't populate the title of the note with the search term.

### ISSUE THREAD

**Issue by starpause** [Automattic/simplenote-electron#572] opened 2017-06-15 18:50 UTC
#### Steps to reproduce
1. Type search query
2. Notice no notes match
3. Hit "New Note" button
4. New note is created with a blank name

#### What I expected
I expected the new note to have it's title set to the search query which didn't bring up any notes. 

#### What happened instead
The new note had a blank title.

#### OS version
Mac

**Comment by dmsnell** [comment] 2017-08-23 01:43
Oops, I addressed #581 which should have been marked as a duplicate of this one. Regardless, this should be resolved in #609. Closing as a duplicate (sorry for the wrong-order in which I addressed these).

**Closed by dmsnell** 2017-08-23 01:43 UTC
Labels: enhancement
