### ISSUE TITLE
Ghost typing

### ISSUE THREAD

**Issue by moniuch** [Automattic/simplenote-electron#1787] opened 2019-12-17 08:23 UTC
Following this [tweet](https://twitter.com/Muscogulus/status/1206650529985814528) I confirm random occurrences of "ghost typing", observed for the past 2-3 days

### Expected
Note text remains unchanged, as typed by user.

### Observed
Some ghost typing alters user text by inserting random substrings of text, usually glued together.

### Reproduced
This is not 100% reproducible.

I managed to reproduce it today with my first two attempts. In both cases I typed the following

newnote[linebreak]
asd[linebreak][wait a few seconds]
[arrowup]

Here are the results

![image](https://user-images.githubusercontent.com/681956/70977186-b49f6f00-20ad-11ea-96b9-cbe56eee66f2.png)

repeated _n_

![image](https://user-images.githubusercontent.com/681956/70977129-98033700-20ad-11ea-8dbd-128e2db8ce48.png)

repeated _a_

Chrome Version 78.0.3904.108 (Official Build) (64-bit), macOS 10.15
Console clear.

In both cases it was a single char that got inserted repeated, but I have seen several character long substrings yesterday.
 
Then I switched to app.simplenote.com/old as advised on twitter, where I repeated same text drill and could not reproduce the behavior, neither in a normal nor incognito window.

I will add more findings as they come, until you can confirm the issue.

**Comment by belcherj** [comment] 2019-12-17 16:00
Thanks for the bug report!!

**Comment by michaelwexler** [comment] 2019-12-22 17:19
I'm seeing this too. Chrome Version 79.0.3945.88 (Official Build) (64-bit) on Windows.  Becoming a problem, as notes become very corrupted.   I've had to go back to day-1's notes and try to recreate what I was trying to add.  Seems like a sync error; looks like edits I made in iOS (and potentially other desktops) are lagged and then flying in, while I'm editing/cutting/pasting and working with a note.

**Comment by moniuch** [comment] 2019-12-30 15:12
@belcherj But have you been able to reproduce it? Any clue on resolving this bug? Rollback to /old ?

**Comment by bummytime** [comment] 2020-01-02 20:15
Bumping this. Ghost typing issues reported on Windows on Chrome Version 79.0.3945.88 (with videos).

**Comment by Dare2python** [comment] 2020-01-04 08:01
Google Chrome on Mac Version 79.0.3945.88

**Comment by Dare2python** [comment] 2020-01-04 08:04
and the same behavior on Mac desktop 1.12.0 and Android 2.2.

Chrome version reported Unsynched changes and the Ghost typing started on all clients.

**Comment by moniuch** [comment] 2020-01-04 11:57
I have just encountered an extreme case on Android 9, three lines of text multiplied by thousands! Need to stop using SN and migrate my notes somewhere else until this gets fixed/rolled back.

**Comment by felixding** [comment] 2020-01-06 04:27
This has been happening to me for months!

The bug occurs on Firefox on Mac and Windows, as well as on mobile apps on Android and iOS.

**Comment by dmsnell** [comment] 2020-01-06 16:25
Hi all. For everyone following this issue I wanted to let y'all know we're focusing in on it. A couple months ago when we fixed one issue this sprang up and we thought we fixed this one as well, but it appears like there's even a rarer set of circumstances where it can happen that we didn't find.

**Comment by rezzap** [comment] 2020-01-11 08:52
Reported again in 2610995-zen 

Example notes available in the ticket, "The text scrambles of its own accord, and does version after version with random variations and gobbledygook on the page" 

Happens on web app only using latest version of Chrome on WIndows 10 PC.

**Comment by rezzap** [comment] 2020-01-25 09:34
There is a report of this same behaviour in the iOS app in 2651500-zen

"for an unknown reason the text "Simplenote email addr" was changed to Simplenosssssste eeeeeeeil addr"

IPhone uses Simplenote ver 4.14.2
iPhone 11 Pro iOS 13.3

**Comment by sarahfg** [comment] 2020-01-26 20:49
Once user sees that it happens when searching. The text is found and highlighted, but it's is not really at the actual location, and if you subsequently try to edit that text, or text close by, the cursor jumps to a different point in the note. #2651500-zen

**Comment by rezzap** [comment] 2020-02-11 12:17
Another report but for iOS in 2702786-zen. User reports: "I _think_ (can’t be sure) that the weirdness occurs when I cut and paste. Just typing text _seems_ to be more reliable (again, I can’t be sure)."

In Safari on MacBook Pro app.simplenote.com behaves properly.

However, app.simplenote.com in Safari.ipa on my iPhone and I see the same sort of crazy editing problems I see in Simplenote.ipa. Actually, even worse – long strings of random characters automatically appearing in the middle of a note.

iPhone X, iOS 12.4.1, Simplenote 4.15.

**Comment by rezzap** [comment] 2020-02-21 10:34
A report in 2687570-zen. 

> If I type "I have a meeting tomorrow." As soon as I hit period, it shows like "I have a meeting meeting." It happens in English and Japanese typing.

Version 79.0.3945.130 (Official Build) (64-bit)
Mac OS Catalina

**Comment by michaelwexler** [comment] 2020-03-18 12:52
Wow, was it terrible today.  Flooded a note with so many changes of random text, I'm scared to use the site now.  Kind of worried; hoping my history is still safe so I can undo.

**Comment by japong** [comment] 2020-03-30 13:18
Yes I've been getting this behaviour as well, and it destroyed an incredibly important note that I can no longer recover. 

Happening in OSX Chrome, Win10 Firefox and Chrome, and on Android app at least. 

https://www.youtube.com/watch?v=guyz1v-cSjQ (error happening on both simplenote and simplenote/old , no input needed, it's just typing on its own)

The revisions on this note flip between Mar 27 at 9:04 and 12:36,  each time some new text strings are pasted in, and the note becomes more and more corrupt.  This quickly fills up the entire history buffer, so I can't revert the note back to its un-corrupted state.  I do not believe this information can be recovered. 

https://www.youtube.com/watch?v=BrGjZmOdX_4

**Comment by moniuch** [comment] 2020-03-30 13:51
Could we perhaps have an update on the progress in resolving this issue?
This ticket is over three months old now, new reports of this behavior and data loss coming in. 
Except for tagging the ticket as a bug, nothing really happened here.
Do you have any plans to resolve the issue?

**Comment by dmsnell** [comment] 2020-03-30 22:40
@japong please reach out to support as we have had at least one case where we were able to restore a note where this happened. can't promise any results but we'll try.

@moniuch nothing may have happened here in this issue but we're still trying to reproduce this bug and figure out what's happening. it would be woefully silly for us to plan on neglecting this issue wouldn't it? our whole thing is simple and reliable note-taking across devices. so if it matters to you or to others please know that GitHub issues here aren't very good indicators of the work going on behind the scenes.

---

As a general update we're still trying to understand how this happens and if it's related to any specific devices. We seem to have seen it now on cases where we are pretty sure it's _just_ the web app (this repository) and also when it's _just_ the android app.

Just last week I caught one "in the act" and was able to do more diagnostic investigation. One aspect that has made this challenging for us is that usually we only catch wind of the bug after it has occurred and so we can't see the mechanism causing it. Well I found one small quirk in the messages between the app and the server which explained _how_ it's ghost writing but didn't explain _why_. I made a test to try and recreate the circumstances and could not trigger the bug.

In short, on a technical level, in some rare and yet-unknown circumstances, when the application gets a confirmation back from the server that its changes applied properly, but that they were transformed due to changes having come in from another device, then the app gets confused and thinks that it failed to get its changes in. Therefore it transforms its own change against the change it just made and resubmits.

So we continue to hunt this bug and why it's happening. In most of these cases the actual bug occurs in some collision of messages that only occur in millisecond timeframes when the right sequence of edits and network conditions is present.

**If you find yourself seeing the ghost-writing please quit the application immediately if you can and contact support. The ghost-writing I _think_ should be interrupted with a restart of the app.**

@japong thanks for sharing your videos. I haven't seen it "bounce" back and forth like that before - I've only seen it repeat a sequence of events like adding the same text or deleting the same text. Was there copy/pasting involved in that?

**Comment by moniuch** [comment] 2020-03-31 10:09
@dmsnell 

> GitHub issues here aren't very good indicators of the work going on behind the scenes.
I realize it very well, and this is exactly why I appreciate some first-hand update every once in a while. Thanks for the info!

> it would be woefully silly for us to plan on neglecting this issue wouldn't it?
Absolutely, this is exactly how I feel. Speaking of which: have you considered rolling back to the last known good version until you have nailed the bug?

> As a general update we're still trying to understand how this happens and if it's related to any specific devices.
I can only add to that that when I started to discover the bug, I was typing on Mac/Chrome, but with 99% certainty I had my Android app open in the background on my phone at the same time.

**Comment by dmsnell** [comment] 2020-03-31 21:15
> I appreciate some first-hand update every once in a while. Thanks for the info!

@moniuch it's not bad to remind us to communicate - no offense taken, none intended.

> have you considered rolling back to the last known good version until you have nailed the bug?

We don't know when this started. It's probably been here at least for a year and it may have been here for many years and only recently started exposing itself as a side-effect of fixing other problems.

> with 99% certainty I had my Android app open in the background on my phone at the same time

We've definitely seen this on Android and on the Web/Electron clients. I don't know with certainty that I've seen it on iOS or macOS.

**Comment by w3sip** [comment] 2020-08-03 06:35
Happened twice in the last few months, both times with critical notes that I haven't been able to fully restore. Disappointing.

**Comment by belcherj** [comment] 2020-08-04 17:10
@w3sip Please try https://staging.simplenote.com where we have the latest beta we are testing.  The issue should be fully be resolved there.

**Comment by rossanafmenezes** [comment] 2020-08-10 17:52
Reported here 3188098-zen

Desktop

Vivaldi 2.6.1566.44 (Stable channel) (32-bit)
Revision b104196d10e5b12a2690fe28e511909c2f4dcf4b
OS Windows 10 OS Version 2004 (Build 19041.388)

User reported the same behaviour on Android as well, but I'm still confirming if they actually saw it happening on Android it if it was just synced.

**Comment by azollafox** [comment] 2020-08-12 14:23
> User reported the same behaviour on Android as well, but I'm still confirming if they actually saw it happening on Android it if it was just synced.

In a follow up the user said:

>the screenshot I sent you occurred on Android. 

confirming the behavior on Android

**Comment by rossanafmenezes** [comment] 2020-08-21 13:36
User reported the same behaviour on  Ipad Pro App (ios 13.6.1) as well 3188098-zen

**Closed** 2020-09-21 20:30 UTC
Labels: [priority] high, bug
