### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable.

### ISSUE THREAD

**Issue by Jed28** [Automattic/simplenote-electron#3044] opened 2021-11-12 05:07 UTC
### Issue
Simplenote-linux-2.21.0-x86_64.rpm
```
$ /opt/Simplenote/simplenote %U
[93440:1112/150906.643603:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    93440 trace trap (core dumped)  /opt/Simplenote/simplenote %U
```
Simplenote-linux-2.21.0-x86_64.AppImage
```
$ ./Simplenote-linux-2.21.0-x86_64.AppImage
[144480:1112/160306.085970:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    144480 trace trap (core dumped)  ./Simplenote-linux-2.21.0-x86_64.AppImage %U
```
### Expected
I expected the program to start

### Observed
I made a fresh VM of Fedora 35 and tested the same rpm/appimage of Simplenote. I got the same results as [this bug report](https://github.com/Automattic/simplenote-electron/issues/3039). I don't know why mine is different or if it related.

### Reproduced
1. Start simplenote within the terminal

### Where did you see the bug
- System Make: AMD Ryzen 5 2600, AMD Radeon RX 470, 32gb ram
- OS: Fedora 35 + Cinnamon DE
- Simplenote app version: 2.21.0-x86_64 RPM & appimage
- [my neofetch](https://i.imgur.com/ZQCn01H.png)

**Comment by brajevicm** [comment] 2021-11-17 07:44
I can confirm that this issue also happens on Fedora 35 + Gnome (Both Xorg and Wayland). It happens regardless if you started via terminal or via desktop shortcut.

EDIT:
Intel i7-10510U 
UHD Graphics 620

**Comment by binary-data** [comment] 2021-11-17 07:52
Fedora 35 KDE - same issue (5.14.17-301.fc35.x86_64)

**Comment by brajevicm** [comment] 2021-11-25 15:08
Temporary workaround would be to edit desktop shortcut, and make the following change:
`Exec=/opt/Simplenote/simplenote %U` -> `Exec=/opt/Simplenote/simplenote --no-sandbox %U`

On Fedora 35 + Gnome, the shortuct is located at `/usr/share/applications/simplenote.desktop`

**Comment by Jed28** [comment] 2021-11-26 06:25
The workaround works, thanks.

**Comment by PinkFrosty** [comment] 2021-12-07 15:56
Thank you for the workaround. It's now working for me on F35 xfce4 spin.

**Comment by coderGambit** [comment] 2022-01-28 14:35
Thanks @brajevicm , this workaround works for ClickUp in F35 KDE

**Comment by erricgunawan** [comment] 2022-02-03 03:49
Probably related/similar problem from 4695050-zen:

> ... at the moment simplenote will not run on the latest version of Fedora 35. It generates a gpu_data_manager_impl_private error. I also have seen this error report in another place that has nothing to do with your great program, so it is likely a Fedora issue. I see the same problem with both the rpm and AppImage versions, and I do not see any problems on my KDE Neon system which is based on an older Ubuntu LTS base. Also the Windows version works fine, but it pains me to have to run Windows! Apple and Android versions are also good.

> Simple-linux-2.21.0-x86_64.rpm is installed and produces this output:

> al@xvb:/home/al $/opt/Simplenote/simplenote
[12257:0124/112406.809083:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
al@xvb:/home/al $

> I am running Fedora 35, which while it is not completely bleeding edge stuff is one of the more advanced and progressive distributions of Linux:

> Linux xvb 5.15.16-200.fc35.x86_64 #1 SMP Thu Jan 20 15:38:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> As previously stated, this version runs OK on an Ubuntu LTS based system (KDE Neon, older kernel and libs) and Windows. I also tried the AppImage here, and it fails exactly the same as the rpm version. I found that interesting as I thought an AppImage had all the required libs included as part of the image, thus removing various dependencies.

> The same gpu error has been reported for another program on other distributions, so I do not think the error is specific to SimpleNote, but rather a Linux problem, possibly a change (update) in a lib package. See this error report:

> https://github.com/LedgerHQ/ledger-live-desktop/issues/4253

**Comment by xiborg** [comment] 2022-04-13 08:00
Same issue on Ubuntu Jammy Jellyfish 22.04 Beta
5.15.0-25-generic #25-Ubuntu SMP
Gnome 42
System: Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz, CometLake-S GT2 [UHD Graphics 630]
Workaroud with --no-sandbox works.

**Comment by vpn12out** [comment] 2022-04-27 20:13
Same issue on Kubuntu 22.04 LTS x86_64

> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [8241:0428/011336.872765:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
> Chrome_IOThread[8271] trap int3 ip:5637a021fc68 sp:7f31a0182320 error:0 in simplenote[56379fff0000+626b000]
> app-simplenote-eb17703a6a8541a199c387521da71481.scope: Consumed 3.188s CPU time.

**Comment by phodamentals** [comment] 2022-05-06 22:28
Workaround 'works' on 5.17.5-76051705-generic Pop!_OS 22.04...

**Comment by ghostry** [comment] 2022-05-09 04:15
-no-sandbox works on ubuntu 22.04

**Comment by vpicavet** [comment] 2022-05-10 10:45
I had the same error with the Linux Zoom client, and launching it with `--no-sandbox` allows the program to run. No idea why though, but thanks for the workaround ;-)

**Comment by worldomonation** [comment] 2022-05-10 20:47
Similar bug but for WordPress.com Desktop app: https://github.com/Automattic/wp-calypso/issues/62088

**Comment by brennmat** [comment] 2022-08-15 15:18
Can confirm this issue on Debian bookworm/sid with Gnome 42.2. The workaround described by @brajevicm works for me.

**Comment by jsvnsk** [comment] 2022-08-15 21:29
Able to reproduce on the following configuration:

Intel Core i5-4590T (2.00 GHz, quad-core)
8GB RAM
Intel HD graphics 4600 (HSW GT2)
Ubuntu 22.04.1 LTS + Gnome DE + 5.15.0-46-generic
Simplenote: 2.21.0

Also can verify the --no-sandbox workaround resolves the error

**Comment by ghost** [comment] 2022-08-16 23:23
Getting the same error on Linux Mint 21.0 (which is based on Ubuntu 22.04); on 20.3 (based on Ubuntu 20.04) I was not having this problem.

**Comment by akwala** [comment] 2022-08-22 00:53
+1
Operating System: Ubuntu 22.04.1 LTS              
Kernel: Linux 5.15.0-46-generic
plasmashell 5.24.6
Qt: 5.15.3
KDE Frameworks: 5.95.0

**Comment by nowave7** [comment] 2022-09-16 18:21
+1 on Zoho email client
OS: Linux Min 21.0 (based off of Ubuntu 22.04 LTS)
Cinnamon: 5.4.12
Kernel: 5.15.0-47-generic
Video Card: NVIDIA GeForce GTX 1050 Ti; 515.65.01-0ubuntu0.22.04.1

Workaround works.

**Comment by DocBretti** [comment] 2022-09-25 03:40
@brajevicm 
This workaround is still needed and also works on manjaro atm im typing this. Thnx a lot for pointing this out.

**Comment by trizdev** [comment] 2022-09-29 17:29
Thanks for the workaround. Same problem using Kubuntu 22.04 but adding `--no-sandbox %U` helps.

**Comment by jozsefk9** [comment] 2022-10-11 13:24
Still the same issue on Fedora 36 XFCE. Workaround works.

**Comment by kinton** [comment] 2022-10-16 13:06
Got the problem today, thanks for the workaround. Manjaro 22.0.0 Sikaris, KDE 5.98.0 / Plasma 5.25.5

**Comment by irfaanz** [comment] 2022-10-26 09:20
no sandbox workaround is working fine so far. I am on Simplenote 2.21, and i have added simplenote -no-sandbox as my start up application in linux mint vanessa. However, i want it to get started headless. Any paramaters that i can pass to start it headless.

**Comment by Flashwalker** [comment] 2022-12-01 14:58
It is Electron issue, when Electron-libs don't match your system

`--in-process-gpu` option helps as workaround.
Also `--disable-gpu-sandbox` or `--no-sandbox` helps too

**Comment by ghost** [comment] 2023-01-11 15:11
Disabling sandbox is never a good option because, you know, it disables the sandbox where electron apps are supposed to run. `--in-process-gpu` is probably a better solution

**Comment by mbrennwa** [comment] 2023-01-11 16:09
I can confirm that running Simplenote using `/opt/Simplenote/simplenote --in-process-gpu` works fine on my Debian SID box. Thanks!

**Comment by deon-vector** [comment] 2023-01-14 04:54
Confirming, I have simplenote 2.21.0-25251 installed on Mint 21 (Ubuntu 22.04 based) using apt and it won't launch. I edited the /usr/share/applications/simplenote.desktop file and added "--in-process-gpu" to it, which I agree is better than disabling the sandbox, and simplenote launches now.  --no-sandbox works also but since both options work, might-as-well go with the safer one. This is strange that years later this problem still persists.

**Comment by ralyodio** [comment] 2023-04-14 05:06
will this ever get fixed on manjaro? I have to use `simplenote --no-sandbox` icon launcher won't launch it. KDE Plasma

**Comment by ghost** [comment] 2023-10-26 18:20
Same fail on Debian Trixie
Workaround ok

**Comment by Aleksandr-ru** [comment] 2023-12-11 16:02
Same on Manjaro 23.1.0, Simplenote: 2.21.0. Using workaround, waiting for solution...

**Comment by codebykat** [comment] 2024-07-23 09:43
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!

**Closed as completed by codebykat** 2024-07-23 09:43 UTC
Labels: bug, [feature] build

**Comment by mrkapqa** [comment] 2024-11-24 16:21
does not function on OpenSuse Leap with KDE Plasma for version Simplenote-linux-2.22.2-beta.5-x86_64.rpm when using amdgpu radeon linux driver?

`/opt/Simplenote/simplenote --no-sandbox %U
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
[4835:1124/171732.596605:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171732.690689:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171732.794130:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171732.865388:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171732.945652:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171733.040183:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=139
[4835:1124/171733.040202:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
`

there is however one dependency missing for Simplenote on Suse, namely libXtst
(nothing provides 'libXtst' needed by the to be installed simplenote-2.22.2~beta.5-1.x86_64)
