### ISSUE TITLE
Thin width mode cannot show note list unless already shown

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/simplenote-electron#566] opened 2017-06-05 20:25 UTC
#### Steps to reproduce
1. Open Simplenote, and set the window width to about 1430 px so that only the note list is visible.
2. Click to select a note from the list. Now the note list is replaced with the note contents.
3. Quit Simplenote. Re-open Simplenote.
4. You should see the note contents as you left it.
5. Click the back arrow to return to the note list.

#### What I expected

To return to the note list.

#### What happened instead

Nothing happens.

**Comment by dmsnell** [comment] 2017-06-06 04:10
Thanks for the report. I'm going to call this a duplicate of #552 and close it for now. Please feel free to reopen if you don't think it's the same bug.

**Closed by dmsnell** 2017-06-06 04:10 UTC
Labels: bug
