### ISSUE TITLE
Feature Request: Install Simplenote to $PATH on Linux distros such as Devuan.

### ISSUE THREAD

**Issue by cecoates** [Automattic/simplenote-electron#717] opened 2018-03-04 17:26 UTC
User reported issue when installing on Devuan Jessie:

> How can we help?: I just installed Simplenote on a Devuan Jessie i3wm minimal install, using gdebi at the cli. Dmenu can't find Simplenote, so I assume that it doesn't get installed in the $PATH as I can't find it in the usual places, such as /usr/bin, /usr/local/bin, /opt, etc. I have also looked in /home/username/.config, /home/username/.local/share/applications for a .desktop file, but nothing... I have to admit I am mystified. How do I get Simplenote in the $PATH? Alternatively, can I run it from the cli, as at this time I get the following error: 
"$ simplenote 
bash: simplenote: command not found"

#### Steps to reproduce
1. installed Simplenote on a Devuan Jessie i3wm minimal install, using gdebi at the cli
2. Dmenu can't find Simplenote
3. "$ simplenote 
bash: simplenote: command not found"

#### OS version

Devuan Jessie

986638-zen

**Comment by mirka** [comment] 2018-12-05 14:44
Closing this for now since the issue was not reproducible, and our Linux builds have changed recently.

**Closed by mirka** 2018-12-05 14:44 UTC
Labels: [OS] linux, feature request
