### ISSUE TITLE
[Feature Request] Adding Pictures to the notes

### ISSUE THREAD

**Issue by 0nvx52lt** [Automattic/simplenote-electron#3153] opened 2023-07-23 20:41 UTC
### What

I really like the features like markdown-support but what would be a great feature would be if you would be able to add pictures to the notes so you can (for example in my case) make a sort of collection with pictures to see where you want to travel and don't have to insert a link and then open it externally 

### Why

Because it would be a nice feature, a lot of people would use it and the app/program would have more usability and is more feature-rich then

### How

Simply by drag and drop so everyone could easily add pictures/photos and nobody would have to miss the feature

**Comment by codebykat** [comment] 2023-09-24 21:51
Duplicate of the oft-requested #1069. Maybe someday.

**Closed as not planned by codebykat** 2023-09-24 21:51 UTC
Labels: feature request
