### ISSUE TITLE
SimpleNote 1.6.0 under osx freezes often

### ISSUE THREAD

**Issue by spinscale** [Automattic/simplenote-electron#1457] opened 2019-07-29 11:45 UTC
### Expected
***(Required)*** A smooth and responsive application

### Observed
***(Required)*** I have about 15 notes, and the one I am experiencing this behaviour the most is about 13kb big (3k words). When going up and down with the cursor or while typing I am experiencing freezes up to 10 seconds (sometimes only three, sometimes none), where the cursor does not move and keyboard inputs are delayed - the document is still visible as usual.

### Reproduced
***(Required)*** I have not yet found a way to truly reproduce this. I am using a few checklists in that document. The debugging console does not contain any output except `Simperium Config: Production`

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
apple|osx|10.14.5|1.6.0

Is there anything else I can supply to you? Not a heavy electron debugger...

**Comment by belcherj** [comment] 2019-07-29 13:30
It appears that you are using the Electron MacOS app. We now have a native MacOS app on the app store:  https://apps.apple.com/us/app/simplenote/id692867256?mt=12

Please give that app a try.

**Comment by belcherj** [comment] 2019-08-13 14:24
This is duplicate of: #1412

This is on my radar and something I am going to look into resolving.

**Closed by belcherj** 2019-08-13 14:24 UTC
Labels: bug
