### ISSUE TITLE
Hide Menubar

### ISSUE THREAD

**Issue by ryanleesipes** [Automattic/simplenote-electron#293] opened 2016-04-11 02:25 UTC
Maybe this is Gnome-specific (Gnome desktop, Ubuntu), but I'd really love a way to hide the menu bar.

![screenshot from 2016-04-10 21-25-11](https://cloud.githubusercontent.com/assets/2141621/14415274/c7afce5c-ff62-11e5-9b2f-a3f29501a470.png)

**Comment by drw158** [comment] 2016-04-12 16:19
The File, Edit, etc. menu can't be hidden on Windows or Linux. Not sure how to solve that though.

**Comment by ebeloded** [comment] 2016-05-30 22:25
Hey @drw158,

The menu can be hidden or auto-hidden (like in Slack or VS Code - you can press Alt to show/hide the menu).

Relevant methods:
- [win.setMenu(menu)](http://electron.atom.io/docs/api/browser-window/#winsetmenumenu-linux-windows) - Sets the menu as the window’s menu bar, setting it to null will remove the menu bar.
- [win.setAutoHideMenuBar(hide)](http://electron.atom.io/docs/api/browser-window/#winsetautohidemenubarhide) - Sets whether the window menu bar should hide itself automatically. Once set the menu bar will only show when users press the single Alt key.

Hope this helps to resolve the issue. The menu is a real eyesore on Windows and Linux.

**Comment by nsrosenqvist** [comment] 2016-07-10 08:43
The implementation of this in Atom can be followed in the following issue thread: https://github.com/atom/atom/issues/2914

The support for hiding the menu bar in electron apps was added with the following pull request: https://github.com/electron/electron/pull/558

**Comment by natanielcz** [comment] 2017-10-24 19:22
Looks like someone already upgraded electron version in Simplenote and app menu is working as intended. At least on Ubuntu 17.10. I think that we may close this issue too.

**Comment by nsrosenqvist** [comment] 2017-11-24 08:06
@natanielcz  It's not working for me, are you sure you're not using Unity and that it's just moved to the global menu? I still have no control of it in 1.1.0. This can't be that hard to implement, can it? Just a menu entry and keyboard event, right?

**Comment by natanielcz** [comment] 2017-11-25 08:51
@nsrosenqvist : you are right. I don't know why I thought that it works. I'll take a look after 8th of December when I'll have more time for that.

**Comment by algiuxass** [comment] 2019-02-15 11:08
This is taking way to long to add this feature. It shouldn't be that hard to fix it. (Using Linux)

**Comment by cweagans** [comment] 2019-02-15 21:26
PR #1207 addresses this.

**Closed** 2019-10-16 17:06 UTC
Labels: FAQ, [OS] linux, [OS] windows, feature request
