### ISSUE TITLE
Spellcheck isn't active

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#312] opened 2016-05-09 09:40 UTC
Spellcheck _should_ be on in the app but it apparently isn't. This has been reported in [other](https://github.com/Automattic/simplenote-electron/issues/517) issues (#3153710-t [@Hywan]) here and with [draft-js](https://github.com/facebook/draft-js/issues/744) as well.

Spellcheck is activated in the code but not the app.

Some testing revealed that this works when running the app locally in a browser but the Electron app appears to not support it.

This issue is here to figure out _why_ spellcheck isn't on when it should be.

**Comment by drw158** [comment] 2016-06-07 14:27
Note: We should allow the user to turn off/on spellcheck like in any textarea in the browser. If that's not possible, then this will require developing a feature and adding a settings to the app.

**Comment by dmsnell** [comment] 2016-11-05 21:32
@drw158 and @rachelsquirrel this came for free when we merged in the draftjs editor (thanks @nfcampos) in #370. While it's now on-by-default, we could add an option to disable it.

@drw158 do you think an item in the menu would be best for this? add an option in both the menu and in the app settings pane? under the _Display_ settings?

**Comment by drw158** [comment] 2017-02-16 15:39
Somehow I missed this.

I think the spellcheck setting should be in the Edit menu. Nothing in the app settings pane.

@dmsnell Is spellcheck now enabled via draft.js?

We have a recent issue for spellcheck #517

**Comment by drw158** [comment] 2017-02-16 15:41
Library for adding spellcheck in the duplicate issue:

https://github.com/electron-userland/electron-spellchecker

**Comment by martynchamberlin** [comment] 2017-03-08 00:23
I'm noticing that in SimpleNote 1.0.8, we've lost spellcheck. Would love to have this back.

**Comment by Hywan** [comment] 2017-04-11 06:59
@martynchamberlin :+1:

One of our user is asking to get spellcheck back on Windows, #3153710-t.

**Comment by martynchamberlin** [comment] 2017-04-11 13:48
@Hywan Yeah. I am sending out emails with typos in them because the hassle of manually running a spellcheck is 2007. Nobody wants to have to do that. It should be automatic.

**Comment by belenos** [comment] 2017-07-24 18:26
Any news on that? I'm using the Linux version and Simplenote still doesn't have a working spell check. That's a must-have feature for any decent text editor nowadays.

**Comment by martynchamberlin** [comment] 2017-07-24 21:14
I personally switched to [Bear](bear-writer.com). An editor that doesn't have spellcheck is ridiculous.

**Comment by belenos** [comment] 2017-07-24 21:24
Bear is nice on iOS, I have tested it. I'm using Ghostwriter on Ubuntu, but it lacks a mobile app or sync between devices.

**Comment by dmsnell** [comment] 2017-07-24 21:44
> I personally switched to Bear.

Well we hope that you are happy with Bear. We'll always welcome you back; and we haven't decided to not support spell-check - it's just a problem in the code that we haven't solved yet. We'd also love to have you participate via code submissions :smile:

>  An editor that doesn't have spellcheck is ridiculous.

More like programmers who make an editor with a broken spell-checker are ridiculous. Honestly I've never made a spilling misteak so I didn't know it was broken 🙃 

---

Seriously though I mean this post with a light heart. We are committed long-term to Simplenote and to making it the best free and simple note taking app around but unfortunately don't have the time to get everything fixed or added in the schedules that everybody wants them to be.

Thanks sincerely for using it; we hope it is a tool that enriches what you do more than it hinders.

**Comment by PhiLhoSoft** [comment] 2017-09-04 11:31
Do you have an idea where this could be broken? Maybe a contributor can try and fix that, pushing in the right direction can help a lot.

Note: I am not sure if it is possible at all in an Electron app, but being able to support several languages would be a tremendous bonus!
I write lot of notes in French, my native language, but I also take technical notes in English, for example.
Ah, I see the above mentioned library handles that, apparently. As long as it doesn't block when off-line and needing a new dictionary. :smile:

**Comment by dmsnell** [comment] 2017-09-04 14:10
@PhiLhoSoft I think it's an issue with `draft-js` - theres a linked comment in the description above. It's specifically related to Electron if that's actually the case.

**Comment by m1aw** [comment] 2017-09-05 17:45
I was able to debug the problem is in electron not being properly configured.
I cloned the repo and launched the local version and had spellcheck in the browser naturally. So even if draft-js has spellcheck as true electron is not displaying spellcheck.

I did some googling and tried to hack it to force spellcheck but I wasn't able to do it since I really don't understand much electron.

I'm not sure if I will have more time to debug it today, but if I do I will post the results.

**Comment by dmsnell** [comment] 2017-09-05 18:35
That's helpful @m1aw - note too that testing locally in the browser won't match the behavior inside of Electron. To test locally though after you have installed the dependencies and built it, you can start with the following command and you will have the Chrome developer tools open for aid in debugging and testing.

`./node_modules/.bin/electron . --devtools`

**Comment by khaullen** [comment] 2018-01-08 20:42
Any updates on where this fits into the roadmap?

**Comment by deanhtid** [comment] 2018-01-12 08:04
Just came across this app recently and I love it, but it really needs a spell checker

**Comment by timypcr** [comment] 2018-01-14 06:30
I just found this app today and I agree needs spell check

**Comment by boubouhkarim** [comment] 2018-01-25 23:15
I am using this app but it's really hard to use it without a spell checker :(

**Comment by mnmami** [comment] 2018-02-26 11:31
Spell-check is needed indeed, at least with the enable/disable option.

**Comment by mdrovdahl** [comment] 2018-03-02 19:14
@drw158 @dmsnell I'm just getting caught up here...were y'all suggesting/confident that `draft-js` is already providing spell checking to the electron app, but for a configuration error? Or, is spellchecking is a gap which needs filling via something like https://github.com/electron-userland/electron-spellchecker?

I can't promise I'll fix this...but, as a daily user of the linux/electron app, I'm motivated and hope to at least help zero in on what to fix, where and how.

**Comment by mdrovdahl** [comment] 2018-03-02 19:21
Hmmm...ok, I just read https://github.com/Automattic/simplenote-electron/pull/692 and that makes me think that with `draft-js` possibly on its way out (in favor of https://github.com/Microsoft/monaco-editor), that the solution for fixing spellchecking is not going to be within the realm of fixing a configuration issue w/`draft-js`.

I'll look into https://github.com/Automattic/simplenote-electron/tree/editor/use-monaco and see what the spellcheck situation looks like on that branch...

**Comment by mengfoobar** [comment] 2018-03-04 20:42
@drw158  @dmsnell 
try using https://github.com/kwonoj/electron-hunspell
It plays well with draftjs and it's pretty easy to setup

**Comment by gwsone** [comment] 2018-04-01 14:33
What?! 3 years later and as a standalone app SimpleNote still has no spell checker?! What the heck?!

**Comment by j10sanders** [comment] 2018-04-14 14:01
I'm on linux and Simplenote would otherwise be my favorite.  Need spellcheck.

**Comment by SoIidarity** [comment] 2018-08-12 09:02
Still no way to add spellcheck to this application?

**Comment by mirka** [comment] 2018-09-22 11:57
This has been implemented (#821 #872) and will be released soon 🙂

**Closed by mirka** 2018-09-22 11:57 UTC
Labels: enhancement

**Comment by erricgunawan** [comment] 2018-11-21 21:58
I know this issue has been closed.

But just wanted to mention that a user reported they still have a problem with spellchecker on Windows: 1584054-zen

I hope this implementation will fix the user's problem when it's released.

**Comment by geezzeer** [comment] 2018-11-27 20:13
I can confirm that today, Nov 27, 2018, spellcheck is not working in Simplenote 1.2.1 on Windows 10.

**Comment by mirka** [comment] 2018-11-27 21:08
@erricgunawan @geezzeer 

Currently, the spell checker language is tied to your OS language. So for example if your OS is set to Chinese, and you typed in English in Simplenote, spell check will not work. Is this the case for you? (If not, please post a new issue with details.)

I realize this is quite limiting, so we're planning to make it more flexible (#949).

**Comment by frafor** [comment] 2020-11-21 02:10
As I type here, the browser itself is spell checking every single word I type, underlining the word with a red corrugated line if it is not correctly spelled. It is built in the browser and can check any language I may be using.

Neither the Windows 10 application nor using simplenote in a browser kicks in the spell checkers active all the time with any other text box to edit text, even formatted text.

I suppose you decided to forget about Windows and Linux as desktop operating systems.

Well, in iOS it works and even shows the offending word underlined in corrugated red, but not for long, only just after you typed the space indicated that that's the end of word.

I have a web app; I set the from for user to type in a regular plain text input. All browsers continue to be functional in its spell checking capabilities. I use a simple text-to-html js library which processes 3000 words in less than 1 second. Honestly, I can not find the problem in what this app is trying to do.

It is nice to publish the page so easily and then share in the social networks. My app can also a way to extract a book or chapters and render an HTML page at once.

It is possible! Keep trying. It is a good idea. Simple, great, but with a terrible drawback.

**Comment by codebykat** [comment] 2020-11-21 02:35
Thanks for the feedback, @frafor.  We do believe it is possible, but it is unfortunately not at all simple (technically). If you're curious about the technical limitations, it has to do with the fact that our editor component (Monaco editor) does not use text components in the browser. This trade-off is a huge performance benefit, especially for long notes (it doesn't render the entire note, only the part on your screen), but presents a challenge for a few things, including spell-checking. There's sadly no API that allows us to "hook in" to the OS-level spellcheck for what the browser perceives as non-editable components.

We do have some ideas for this, but we'll have to reinvent a few wheels along the way, so please stay tuned. 😄

**Comment by nivlac777** [comment] 2021-10-23 09:07
Any update on adding spell check to Simplenote Windows version?  Thanks!

**Comment by robsdedude** [comment] 2021-12-06 08:41
But why is the issue still marked as closed if ti's not working? (btw, also not working for me)

**Comment by dmsnell** [comment] 2021-12-06 22:09
no updates from on spellcheck unfortunately. it's on our internal feature tracker which is where we plan and prioritize and coordinate on features and bugs like this. thankfully there's no impact on a feature's timeline whether or not we have an open issue for it on GitHub. we _do_ communicate upcoming features and fixes though so if there's no update from us it's safe to assume we have nothing to report on.
