### ISSUE TITLE
Custom sorting of notes by dragging them to re-order?

### ISSUE THREAD

**Issue by sprite-1** [Automattic/simplenote-electron#1046] opened 2018-11-28 14:55 UTC
Hi, I'm requesting a feature to sort notes manually by dragging them around.

As well as keeping the sort exclusive to each view:

- Remember sorting for All Notes view
- Remember sorting for single tag view
- Remember sorting for combination tag view.

Thank you for the awesome note-taking app!

**Comment by mirka** [comment] 2019-02-20 18:42
Thanks for the request! Closing as a duplicate of #760.

**Closed by mirka** 2019-02-20 18:42 UTC
Labels: feature request
