### ISSUE TITLE
Small cursor on HiDPI display

### ISSUE THREAD

**Issue by yustnip** [Automattic/simplenote-electron#625] opened 2017-09-05 07:23 UTC
#### Steps to reproduce
1. Move the mouse cursor to the Simplenote window. My display resolution is 3840x2160.

#### What I expected
The cursor has a normal size.

#### What happened instead
The cursor has a tiny size.

#### OS version
Ubuntu GNOME 17.04

#### Screenshot / Video
![screencast_05-09-17_09_11_51](https://user-images.githubusercontent.com/9950871/30049642-1d34c7e2-9224-11e7-8b14-60be5e1333bb.gif)

**Comment by dmsnell** [comment] 2017-09-05 15:49
@yustnip thanks for reporting. While I sympathize with the frustration I could imagine that causing, I also find that video a bit funny watching the pointer shrink 🙃 We'll dig into this. I'm guessing it's related to Electron more than anything else.

**Comment by yustnip** [comment] 2017-09-11 17:18
In addition. It was when I installed Simplenote as a snap. Now I installed it via .deb and all's OK with the cursor size.

**Comment by isanchezd1988** [comment] 2018-06-04 19:43
I think it's not an application problem. It is a problem of a bug in the gnome shell itself that has ubuntu packaging

The following link follows the bug in question: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1700085

I know because in my laptop (macbook 2013) i installed ubuntu 18.04 and i have this problem with some apps

Anyway the test would be simple if we test in a different environment than gnome (KDE for example)

PD: Sorry for my english, google translate helped me xD

**Comment by justinkterry** [comment] 2019-02-03 04:53
I'm unable to reproduce this on the current version of simplenote and the current version of Ubuntu 18.04

**Comment by mirka** [comment] 2019-02-25 15:50
I'm closing this for now. But if anyone is still seeing this in current versions, please report to Electron as it is probably not something we can fix on our side.
https://github.com/electron/electron/issues

**Closed by mirka** 2019-02-25 15:50 UTC
Labels: bug
