### ISSUE TITLE
Editing a tag causes a multiple repeat changes

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1640] opened 2019-10-09 17:24 UTC
When you edit tag `xxxx` by adding `b` you get something like `xxxxbbbbbbb` after a refresh.

### Expected
edit tag `xxxx` by adding `b` you should get `xxxxb` after a refresh.

### Observed
edit tag `xxxx` by adding `b` you get something like `xxxxbbbbbbb` after a refresh.

### Reproduced
- Edit tag by adding a b to the end of a tag
- Refresh, observe that the tag is now xxxxbbbbbbbbb. It adds a bunch of extra b's

<img width="217" alt="Screen Shot 2019-10-09 at 1 13 12 PM" src="https://user-images.githubusercontent.com/6817400/66504887-2e0c5700-ea98-11e9-8b13-3ad672e053ca.png">
<img width="210" alt="Screen Shot 2019-10-09 at 1 13 19 PM" src="https://user-images.githubusercontent.com/6817400/66504889-2e0c5700-ea98-11e9-8da7-c0d3dd1dcfb2.png">

**Comment by codebykat** [comment] 2020-07-16 03:20
I can't reproduce this so I think closing for now, we can reopen if it crops up again

**Closed by codebykat** 2020-07-16 03:20 UTC
Labels: bug
