### ISSUE TITLE
Last action repeated automatically

### ISSUE THREAD

**Issue by lhakim** [Automattic/simplenote-electron#1716] opened 2019-11-13 22:47 UTC
Since yesterday anything I do on Simplenote.com web app keeps repeating. Typing anything on the page would keep adding the same word over and over again. Please view screen record attached. Thanks

![simplenote_bug](https://user-images.githubusercontent.com/7199034/68811020-84f0e780-0667-11ea-9c62-e3c4a7e5029c.gif)

**Comment by dmsnell** [comment] 2019-11-14 02:03
@lhakim I'm going to close this as a duplicate of #1690 - it's a pretty unfortunate bug!

Can you help us out by letting us know if you had Simplenote open in more than one Chrome tab/window/session at the same time when this happened?

**Closed by dmsnell** 2019-11-14 02:03 UTC

**Comment by lhakim** [comment] 2019-11-14 09:07
Hi @dmsnell , I only had one active tab open when this happened. Hope this helps. Thanks
