### ISSUE TITLE
Last modification losts when opening the application

### ISSUE THREAD

**Issue by lucamosca1** [Automattic/simplenote-electron#2275] opened 2020-08-14 12:35 UTC
Environment a bit complex
- 1 android device
- 2 windows 10 pc
- 2 linux pc (ubuntu 20.04, simplenote installed as .deb downloaded from here)

Sometimes happens that the application starts and send the current note status instead of download latest modifications first. This has the result that latest modification are lost (luckily available in history) and the current status for all device will be set as latest - 1. After detecting which notes hasn't been updated, I can look in history and set to the previous version that contains all information updated.

Pretty confusing explaination, I understand, if there are some way to help for this bug (debug, log) I can retrieve additional info when will happen again.

**Comment by cdolle** [comment] 2020-08-18 01:35
I also have this exact issue. Edits are occasionally lost but available via History. It definitely seems that it will upload the existing file before checking the server for updates, causing the new file to be overwritten by the older one. 

I'm using Simplenote across an iPhone, iPad, and two Windows PCs (both via web and the app).

**Comment by dmsnell** [comment] 2020-08-18 15:02
Thanks for reporting @lucamosca1 and @cdolle 

I'm not sure I understand the description fully so I want to share what the expectations are for how Simplenote manages notes when it starts up. Simplenote stores each revision as a set of changes/edits from the preceding revision - a "diff" of the text before and after the change. This is what allows us to merge edits from multiple devices. If instead we stored "this is the full contents of version 1" and "this is the full contents of version 2" then we wouldn't be able to merge all the changes.

Why is that relevant here? We don't perform an exchange of note content with the server when we start the app. If I'm understanding your situation right then this is what I think is happening: two of the devices start with the same note. We made edits on one of the devices while the other is offline. While still offline we make edits on the other device. At this point the note history has split into two new histories. When the second device comes back online it will try and synchronize its edits with the server.

In most cases the server will come back and say "you missed some edits from the other device but I was able to merge your changes into those and so here is the new update to the note with the combination of their changes and yours." In some rarer cases we can't cleanly merge the changes. This is like when we swap out the same word on both devices with different replacements. In that case the server says "you missed some edits and I couldn't fit them together."

In these cases Simplenote makes a decision to try to preserve what it can and so it will tell the server to replace its copy of the note with the full contents from the device making the request. That is, instead of losing all those edits made on the device that conflict with the version on the server we do a full swap of the contents knowing you can still restore the other updates from version history.

The order in which things happen won't matter because the app can't determine if its local edits occurred before or after the ones made on the other device (during the time in which it was offline). If the server is unable to merge changes we have to pick a winner and in these rarer cases we pick the local edits as the winner so that we don't lose them.

It would be better if we could indicate when those incompatible changes occur but that's not currently possible given how the application interacts with the underlying data service. It's definitely on our wish list and internal feature request list but not on our immediate roadmap.

Is this helpful?

**Comment by cdolle** [comment] 2020-08-18 16:12
Thank you for the response - this makes sense. 

It shouldn't be a connectivity (offline/online) issue - I'm always online (working from home on a very stable fiber connection). So what it seems is that Simplenote is reading the local version as edited, opting to preserve the local edits, and discarding the server's edits even when the local version is **not** new or edited. It's almost as if the application closes before registering its changes with the server and then overwrites whatever has been done on other devices once it is reopened later.

I did notice the issue seems to happen most(?) with the Windows app, so I've discontinued use and swapped over to the "Staging" web app on my PCs to see if this makes a difference.

**Comment by dmsnell** [comment] 2020-08-18 16:20
@cdolle in general the "staging" app is going to handle these things better. In a few weeks we plan on updating all versions to the staging version. Here are a couple ideas that might help explain what you're seeing:

 - if the app quits within a couple seconds of editing a note it may not synchronize the changes
 - if the app isn't open then things are the same as if the app were offline

if you think something is amiss please feel free to contact our support at support@simplenote.com where we can look at the specific note and the revisions to see if something is buggy. I'm guessing there was a small "race" between the local and remote changes at some point that put the old app into a weird state.

you can download an up-to-date copy (at the time of me posting this comment) of the Windows build for the beta at the following link:
https://15921-41199577-gh.circle-artifacts.com/0/tmp/simplenote/release/Simplenote-win-2.0.0-beta1.exe

**Comment by KshDi13** [comment] 2020-08-19 12:12
just had a similar issue.

Made changes to a Note on a Windows PC after which i closed App.
Moments later open same note on the Android App but don't see the edits made literally minutes earlier on the Windows PC.
Did not edit the note on the Android App (as i didn't want it to be latest edit). Close Android App.
Go back to Windows PC, open app and open the Note and now my previous edits on the Windows App have gone and the Note i'd only opened and not edited on the Android App have taken precedent. Look through history. Nothing at first (as if there's no history) and then in and out of the note a few times and then a few items of history appear on the slider AND importantly the note i'd most recently edited in the Windows App. Restore Note.

This is not the first time or first version i've seen this (now worrying) issue crop up. Surely just _opening_ a Note in the Android App should not stamp it with an edit. I mean what if another version out there hasn't had the opportunity to sync?

**Comment by dmsnell** [comment] 2020-08-19 14:01
@KshDi13 thanks for the detailed report. I wonder if you could recreate that same sequence of events without Android being in the picture. the history slider has some issues, a few of which we've fixed in the staging release, which might be the reason for this.

here are the issues with the history slider relevant to this issue:
 - it opens before the app loads the note's revisions, appearing as if there are none (fixed in staging)
 - it gets confused between the latest revision and the unsynchronized local copy of the note (still working on this one)

if the app was closed before it could synchronize your note it may have stored the changes in its queue and only synchronized them after a delay when you re-opened the Windows app. this is the sequence of events I think may be occurring:

 1. you reopen the Windows app
 2. the app has forgotten the local changes so it looks like the copy on Android, but it has remembered the changes in another part of the app (this has also been cleaned up in staging)
 3. when the revision slider opens it's initially empty but sends out a request to get the revisions
 4. the revisions load without your changes because those changes haven't sync'd yet
 5. after some fidgeting (time has passed) your changes are confirmed and now appear in the revision list

if all this is the case then I do think things will work better in our soon-to-be-released update. it should not wash out the changes temporarily while they sync (across app sessions), as soon as you open a note it fetches the revisions, and the history slider won't even open before it has those revisions.

want to say thanks again for the detailed report. if my response seems overly explanatory it's only because I'm working to understand what's happening so we can fix it properly.

**Comment by javier-iaa** [comment] 2020-09-07 20:21
I've also suffered this same issue but I'm using Simplenote in Ubuntu Linux and Android only.

I love simplenote but this issue is really killing me. This has happened to me multiple times in the past but I discovered that I could just go one step back in the history and I would lose just a bit of the note (often not a big pain). But today I opened a note in Android and it wasn't updated. So I was careful and I didn't make any change to the note to avoid overwriting my latest changes. Then I went to Ubuntu and open the latest version of the note to find that it had been reversed back to 8 days ago. So I waited a little bit and look again to the the history and nothing has changed, I've lost 8 days of changes in the note due to this sync issue.

Knowing that the issue might be related to a lack of synchronization with the server I think it could help a lot if you just put in the app some connection info saying whether the note has been synchronized successfully with the server and when. With that info, if there were sync problems one would know about it and could wait till the info is received in the server.

**Comment by dmsnell** [comment] 2020-09-08 17:53
@javier-iaa we're rolling out a major update to the app where we think we've resolved all these issues. as icing on the cake it shows you when the last time each note synchronized with the server.

this update is the biggest we've ever made and it was directly a result of the data-loss issues. it's rolling out slowly because we have to be careful when releasing huge changes, but you can try it at https://staging.simplenote.com

if you contact support at support@simplenote.com we can see if we can help any further with your specific case

**Comment by codebykat** [comment] 2020-09-21 21:15
Closing as stale since we just shipped the new update and much of this functionality has been completely rewritten. Please don't hesitate to reach out to support or open a new issue if you're still having trouble with syncing!

**Closed as completed by codebykat** 2020-09-21 21:15 UTC
