### ISSUE TITLE
Markdown: New list item (* or -) not appearing automatically on new line of a list

### ISSUE THREAD

**Issue by balaziks** [Automattic/simplenote-electron#371] opened 2016-08-28 13:12 UTC
When editing a Markdown list in a Android app the editor adds new list item character (\* or -) automatically when hitting enter at the end of a list item.

This doesn't happen on the Windows desktop app.

**Comment by drw158** [comment] 2016-09-13 16:46
This is expected — we have not implemented this feature yet.

**Comment by nfcampos** [comment] 2016-09-13 17:15
(this should be much easier after #370)

**Comment by dmsnell** [comment] 2016-09-21 23:27
I'm closing this issue @balaziks because it's a duplicate of #314. We will track development there, but thanks for the report!

**Comment by dmsnell** [comment] 2016-09-22 01:16
Not a duplicate. Sorry!

**Comment by drw158** [comment] 2017-01-19 17:19
I think this has been implemented.

**Closed by drw158** 2017-01-19 17:19 UTC
Labels: feature request
