### ISSUE TITLE
Duplicate tag not deleting

### ISSUE THREAD

**Issue by hom-bahrani** [Automattic/simplenote-electron#519] opened 2017-02-17 13:36 UTC
#### Steps to reproduce
1. Added a tag called "cv"
2. Then decided I wanted to use the tag "personal" instead
3. So I deleted the cv tag in the left hand menu bar
4. I went into the note and added the new tag but when I opened and closed the application there were 2 personal tags in the left hand menu

#### What I expected
I expected the cv tag to disappear and leave just the new tag

#### What happened instead
I have to duplicate tags

#### OS version
Mac OS Sierra V 10.12.2

**Comment by rachelsquirrel** [comment] 2017-02-22 10:34
Possibly related to this:

https://github.com/Automattic/simplenote-macos/issues/70

**Comment by labuboco** [comment] 2017-02-23 02:11
Windows 7 has same problem.

**Comment by carladoria** [comment] 2017-05-07 10:09
reported here: 3194884-t too

**Comment by SiobhyB** [comment] 2017-12-06 20:43
This was also reported in 830155-z

**Comment by chriscollinsboxuk** [comment] 2018-07-30 10:58
I'm also seeing duplicated tags: I'm not sure how this came about. On my Windows 10 machine, I see the duplicates. On the Android app I don't see them. On simplenote.com I see the duplicates.

**Comment by msilbers** [comment] 2018-08-28 21:37
This is also reported in #1372185-zen
They have about 5 tags duplicated. The duplicates are associated with the same notes, like there is only one tag, but it displays twice.

**Comment by mgalbritton** [comment] 2019-06-25 15:48
reported also in #2126885-zen user is using:
Android version 1.7.0 
Windows App version 1.5.0

**Comment by sarahfg** [comment] 2019-12-23 20:26
Also reported at #2575782-zen

**Comment by msilbers** [comment] 2020-01-08 19:39
reported in #2613853-zen
Windows on the web (waiting for browser and version)

**Comment by dmsnell** [comment] 2020-09-21 21:54
Should be resolved in #2148 

@hom-bahrani you can verify this and see if it's still causing a problem at https://app.simplenote.com

We'll have a release to the desktop app soon but I believe this should be fixed.

**Closed by dmsnell** 2020-09-21 21:54 UTC
Labels: [feature] tags, bug

**Comment by hom-bahrani** [comment] 2020-09-23 10:33
Thanks is working ok now

**Comment by kondratieph** [comment] 2022-12-06 00:35
Still this problem exists (web). One day you notice that there are two tags under same name. You can delete the first dublicate but can't delete another.

**Comment by phi-kit** [comment] 2024-03-15 15:49
Experiencing this as well. I noticed there were some tags that I couldn't delete. If I use that tag on a document and look at my tag list, I see a duplicate of the tag that I couldn't delete. If I try to delete the tag afterward, I can only delete one of the duplicate tag. 

Edit: Was able to clean up my tags through the mobile app.
