### ISSUE TITLE
Tag isn't automatically added when creating a new note

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2528] opened 2020-12-16 15:35 UTC
In recent Simplenote releases (Simplenote 2.0.0 and above), tag isn't automatically added when creating a new note.

This can cause certain undesired behavior for users who are used to work with one tag selected in the left sidebar menu.

For instance, if I select some tag in the left sidebar, then create a new note, after which I click on any other note in the notes list - newly created note will "disappear" (it won't be present in the list of notes on the left, since it doesn't have a selected tag). Thus, I have to switch to All Notes, tag that newly created note and then return to previously selected tag.

This is time consuming and it is not how the application worked in Simplenote 1.x.x releases.

### Steps to reproduce

1. Select some tag in the left sidebar.
2. Create a new note.
3. Observe the tag section at the bottom of the created note.

### Screenshot

![2020-12-16_16-16](https://user-images.githubusercontent.com/8862464/102368471-2c52f300-3fbb-11eb-9503-0e028adf4b3c.png)

Ubuntu 18.04
Simplenote 2.4.0-beta1
(though it behaves the same in all 2.x.x releases - 2.0.0 / 2.1.0 / 2.2.0 / 2.3.0)

**Comment by codebykat** [comment] 2020-12-16 17:55
Thanks @djordjeandrejevic, this is a duplicate of #2423.

**Closed as completed by codebykat** 2020-12-16 17:55 UTC
Labels: bug
