### ISSUE TITLE
Desktop app keeps asking to "Review You Account" even after I have

### ISSUE THREAD

**Issue by SaeedBaig** [Automattic/simplenote-electron#2683] opened 2021-02-22 01:36 UTC
### Expected

After installing 2.6.0, once I started the app, I was prompted to Review my Account, and either change or confirm my current email. After I clicked "Confirm", I followed the app's instructions of confirming my email account, clicking the link in the verification email, and the browser confirmed it was verified.

![email_verified](https://user-images.githubusercontent.com/29703429/108646217-39cfb080-7509-11eb-8add-d6cd4a05d302.png)

I thus expected that the desktop app, on restart, would stop asking me to Review My Account.

### Observed

Everytime I open the desktop app, it shows me this popup, even though I've already verified my email 3 times now.

![error](https://user-images.githubusercontent.com/29703429/108645614-887c4b00-7507-11eb-9a73-a592a961c43d.png)

### Reproduced

1. Open desktop app; you should be prompted to Review Your Account
2. Follow steps to successfully confirm email address for account
3. Restart the app as many times as you want; you will still always be prompted to Review Your Account

### Where did you see the bug

- System Make: Dell
- System Model: Dell XPS 13 9360
- OS: Kubuntu (Linux)
- OS version: Kubuntu 20.04.2 LTS
- Simplenote app version: 2.6.0 (desktop app downloaded as deb package from latest release)

**Comment by codebykat** [comment] 2021-02-22 08:57
Hi @SaeedBaig, please log out and log back in to refresh your account data and let me know if that still does not fix the issue. Thanks!

(Duplicate of: #2675)

**Comment by SaeedBaig** [comment] 2021-02-22 09:18
Oh thanks @codebykat . That fixed it.

I hope there will be a long-term fix in the works for this issue, so other Linux users don't just keep running into this same issue again and again.

**Comment by codebykat** [comment] 2021-02-22 21:22
Yes, we're looking into it, but I don't really have any theories about why it has happened to a handful of people. The vast majority of folks on Linux and Windows have been able to verify without it getting stuck. Thanks for letting us know.

**Closed as completed by codebykat** 2021-02-22 21:22 UTC
Labels: bug

**Comment by campbellmc** [comment] 2021-03-30 08:45
This happening on Windows 10 as well.
It appeared to start happening when I separately installed Simplenote on a new mobile phone.
Simplenote Windows 10 Version 2.8.0
Logout and login appears to have resolved the issue.

**Comment by davouch** [comment] 2021-04-18 15:47
Same here with Simplenote 2.9.0 at Windows 10 Pro ver: 20H2 build: 19042.928
Logging off and back in the app helped here as well.

**Comment by pothi** [comment] 2022-02-10 04:06
Happened on Linux Ubuntu 18.04 as well. Logging out and logging back in fixed it.

**Comment by buscon** [comment] 2023-02-17 14:52
> Happened on Linux Ubuntu 18.04 as well. Logging out and logging back in fixed it.

Agree, I had the same issue and it got fixed logging out and logging back in.
I am on Linux Mint 21.1 (same as Ubuntu 22.04).
