### ISSUE TITLE
Preview shortcut doesn't work with Firefox browser

### ISSUE THREAD

**Issue by heyfrancisco** [Automattic/simplenote-electron#3085] opened 2022-03-18 13:22 UTC
Would be a great feature if customizing the shortcuts was available, or changing the markdown preview shortcut.

### Expected
Once pressed, the shortcut: Ctrl + Shift + P I should be able to preview my markdown content.

### Observed
Since Firefox browser shares the same shortcut (Ctrl+Shift+P), instead of previewing the markdown opens a new a private window.

### Reproduced
Having a markdown note opened in the Firefox browser, press the shortcut Ctrl+Shift+P

### Where did you see the bug
- System Make: Thinkpad
- System Model: T14 
- OS: Windows
- OS version: 10
- Browser (if applicable): Firefox
- Browser version (if applicable): 98.0.1
- Simplenote app version: 2.19.1

**Comment by codebykat** [comment] 2022-03-22 18:34
Yes, sorry for that. Unfortunately keyboard shortcut real estate is pretty limited and we had a hard time finding a set that doesn't conflict. This issue is a duplicate of #2196 but there is no workaround yet, aside from installing the desktop app. Apps within the browser are always going to have a hard time supporting a full set of shortcuts as there are so many used by the browser itself!

**Closed as completed by codebykat** 2022-03-22 18:34 UTC
Labels: bug
