### ISSUE TITLE
Reinstall the app, and it logs me in automatically

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#191] opened 2016-02-29 20:53 UTC
Windows

I noticed that if you reinstall the app, then it logs you in with the credentials you used before you uninstall the app. It caught me off guard. Do other apps do this? Is it useful, or a security concern? Are credentials stored anywhere?

**Comment by roundhill** [comment] 2016-03-17 22:51
Just confirmed this with @drw158. We need to either:

* Delete the `C:\Users\(user)\AppData\Roaming\Simplenote` folder when the app is uninstalled.
* Somehow know when the app is starting up for the first time, and intentionally delete the existing auth token that is stored in localStorage.

**Comment by roundhill** [comment] 2016-03-21 18:39
I've just tried this with Slack, if you delete the app and install it again you are still signed in. 

I don't see an immediate solution for this, so I guess I'm thinking that if Slack can't solve it maybe we shouldn't worry about this for now. Thoughts?

**Comment by dmsnell** [comment] 2016-03-21 19:00
@roundhill I see this as a pretty big issue, but also have trouble thinking that there might be a feasible solution. Maybe it's not so bad as it sounds: designed to make updates or accidental uninstalls easier to deal with. I personally agree with the wipe-everything side of the debate around Atom than the view the maintainers hold.

If we roll this out, we at least have this as a place to discuss.

**Comment by dmsnell** [comment] 2016-03-21 19:02
> Somehow know when the app is starting up for the first time, and intentionally delete the existing auth token that is stored in localStorage.

do we get an easy place to do this in the install script? It would seem like the most likely place to accomplish this. I wonder if there's a way to do it securely, associating some file or state with the individual install.

**Comment by drw158** [comment] 2016-06-10 17:17
This could be a non-issue, but we should make a decision. There is some controversy over this in Electron I believe. This also happens in Slack, and I assume WP Desktop? We could decide to not fix this.

I think it's only really a problem for us, because notes can be personal, and might even contain passwords. The problem would be alleviated if we had password-protected notes.

**Comment by dmsnell** [comment] 2016-11-05 21:45
I propose that we close this issue as `won't-fix` since the prevailing behavior with Electron apps is what we have.

there's a point to be made about preserving app data on uninstall and if Simplenote users want to clear it out then we could add some note in the documentation to make that easy to do just that.

otherwise we can probably consider this the expected behavior.

for prudence I will go ahead and close this, but feel free to reopen if you disagree.

cc: @drw158 @roundhill

**Closed by dmsnell** 2016-11-05 21:45 UTC
