### ISSUE TITLE
App won't launch if it is ever set as a favorite

### ISSUE THREAD

**Issue by gchochla** [Automattic/simplenote-electron#1943] opened 2020-03-04 22:30 UTC
If and when I set the Simplenote app as a favorite within Ubuntu (even if I later remove it from that list), the app seizes to launch (the UI won't launch, to be more precise, there has been an instance where 4 Simplenote processes were launched on my computer despite no UI, and in fact consumed way too much CPU, though I haven't been able to reproduce that)

### Expected
App to launch normally even after it has been selected to be a favorite.

### Observed
Once selected as a favorite, even if later removed from the list, the app's UI fails to launch.

### Reproduced
> 1. Select "Add to favorites" within Ubuntu.
> 2. Try to launch.

Make|Model|OS Version|App Version
-|-|-|-
Custom|-|Ubuntu 18.04|Electron 1.14.0

**Comment by codebykat** [comment] 2020-03-04 23:00
Hi @gchochla, thanks for the report! Just to clarify, are you referring to the "Add to favorites" function within Ubuntu (https://help.ubuntu.com/stable/ubuntu-help/shell-apps-favorites.html.en), or is this in the web browser?

**Comment by gchochla** [comment] 2020-03-04 23:48
I am referring to the utility within Ubuntu

**Comment by JorgeQuintanaL** [comment] 2020-03-06 02:21
I am facing the same issue but using Pop OS 19.10. The UI never appears even if I retry many times.

**Comment by codebykat** [comment] 2020-06-04 20:48
I can't reproduce this in Simplenote 1.16.0 on a VM (Ubuntu 18.04.4 LTS on Parallels). @gchochla and @JorgeQuintanaL can you confirm if this still happens with the latest version of Simplenote?

The steps I followed on a fresh Ubuntu install:
1. Install Simplenote from Software
2. Launch the app
3. Quit the app and add to Favorites
4. Launch again

<img width="1023" alt="Screen Shot 2020-06-04 at 1 46 07 PM" src="https://user-images.githubusercontent.com/52152/83808610-f0cd8880-a669-11ea-8854-ad1ebedbc711.png">

**Comment by gchochla** [comment] 2020-06-04 21:11
1.16.0 does indeed work properly (so far)

**Comment by codebykat** [comment] 2020-06-08 20:17
Okay, I'm going to close this as hopefully fixed then, let's reopen if it comes up again.

**Closed by codebykat** 2020-06-08 20:17 UTC
Labels: bug
