### ISSUE TITLE
Missing gconf2 dependency in new version cause install on Ubuntu 18.04 to fail

### ISSUE THREAD

**Issue by justinkterry** [Automattic/simplenote-electron#1178] opened 2019-01-29 18:15 UTC
See below for specifics of errors, you just need to add a dependency. Ubuntu 18.04 is the current LTS and the main version of Linux you should be testing on and is by far the most use. Can you please add a test for this to make sure dpkg -i actually works for new releases? This is the second time where you've released something that's broken this (#727 ).

justinkterry@Epsilon:~/Downloads$ sudo dpkg -i Simplenote-linux-1.4.0-amd64.deb [sudo] password for justinkterry: 
Selecting previously unselected package simplenote.
(Reading database ... 149338 files and directories currently installed.)
Preparing to unpack Simplenote-linux-1.4.0-amd64.deb ...
Unpacking simplenote (1.4.0-2882) ...
dpkg: dependency problems prevent configuration of simplenote:
 simplenote depends on gconf2; however:
  Package gconf2 is not installed.

dpkg: error processing package simplenote (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 simplenote
justinkterry@Epsilon:~/Downloads$ sudo apt install gconf2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gconf2 : Depends: gconf-service
          Depends: libgconf-2-4 (>= 3.2.6-4ubuntu1) but it is not going to be installed
          Depends: gconf-service-backend (= 3.2.6-4ubuntu1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
justinkterry@Epsilon:~/Downloads$ apt --fix-broken install
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
justinkterry@Epsilon:~/Downloads$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  gconf-service gconf-service-backend gconf2 gconf2-common libgconf-2-4
Suggested packages:
  gconf-defaults-service
The following NEW packages will be installed:
  gconf-service gconf-service-backend gconf2 gconf2-common libgconf-2-4
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 911 kB of archives.
After this operation, 8,654 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 gconf2-common all 3.2.6-4ubuntu1 [700 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 libgconf-2-4 amd64 3.2.6-4ubuntu1 [84.8 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 gconf-service-backend amd64 3.2.6-4ubuntu1 [58.1 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 gconf-service amd64 3.2.6-4ubuntu1 [2,036 B]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 gconf2 amd64 3.2.6-4ubuntu1 [66.9 kB]
Fetched 911 kB in 0s (3,062 kB/s) 
Selecting previously unselected package gconf2-common.
(Reading database ... 149422 files and directories currently installed.)
Preparing to unpack .../gconf2-common_3.2.6-4ubuntu1_all.deb ...
Unpacking gconf2-common (3.2.6-4ubuntu1) ...
Selecting previously unselected package libgconf-2-4:amd64.
Preparing to unpack .../libgconf-2-4_3.2.6-4ubuntu1_amd64.deb ...
Unpacking libgconf-2-4:amd64 (3.2.6-4ubuntu1) ...
Selecting previously unselected package gconf-service-backend.
Preparing to unpack .../gconf-service-backend_3.2.6-4ubuntu1_amd64.deb ...
Unpacking gconf-service-backend (3.2.6-4ubuntu1) ...
Selecting previously unselected package gconf-service.
Preparing to unpack .../gconf-service_3.2.6-4ubuntu1_amd64.deb ...
Unpacking gconf-service (3.2.6-4ubuntu1) ...
Selecting previously unselected package gconf2.
Preparing to unpack .../gconf2_3.2.6-4ubuntu1_amd64.deb ...
Unpacking gconf2 (3.2.6-4ubuntu1) ...
Setting up gconf2-common (3.2.6-4ubuntu1) ...

Creating config file /etc/gconf/2/path with new version
Setting up libgconf-2-4:amd64 (3.2.6-4ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up gconf-service-backend (3.2.6-4ubuntu1) ...
Setting up gconf-service (3.2.6-4ubuntu1) ...
Setting up gconf2 (3.2.6-4ubuntu1) ...
Setting up simplenote (1.4.0-2882) ...
justinkterry@Epsilon:~/Downloads$ sudo dpkg -i Simplenote-linux-1.4.0-amd64.deb (Reading database ... 149596 files and directories currently installed.)
Preparing to unpack Simplenote-linux-1.4.0-amd64.deb ...
Unpacking simplenote (1.4.0-2882) over (1.4.0-2882) ...
Setting up simplenote (1.4.0-2882) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

**Comment by mirka** [comment] 2019-01-29 20:12
gconf2 is [set as a dependency](https://github.com/Automattic/simplenote-electron/blob/136216cd58a6fa926325ade88fc36d7845049e6a/electron-builder.json#L102) and we do test on Ubuntu 18.

As far as I know, `dpkg` [does not install dependencies](https://stackoverflow.com/questions/7170657/) for you. You could instead do something like `apt-get -f install`. Or [gdebi](https://stackoverflow.com/a/8477437/636796).

If `dpkg -i` had been working for you in the previous version, it's probably because you already had gconf2 installed.

(I'm not a Linux expert, so correct me if I'm mistaken)

**Comment by justinkterry** [comment] 2019-02-03 05:37
dpkg -i had been working with the previous version without gconf2 installed is the thing. This is issue very is closely related to #727, where you fixed this without having to install anything. It may have something to do with gconf-2-4 vs gconf2.

**Comment by justinkterry** [comment] 2019-02-03 05:38
Also, I encourage you to take a look at what I outlined in #1191, I think that's the correct long term solution to all the problems like this that keep popping up.

**Comment by mirka** [comment] 2019-02-25 13:19
> dpkg -i had been working with the previous version without gconf2 installed is the thing.

Are you saying that this works?

```
sudo dpkg -r gconf2
sudo dpkg -i Simplenote-linux-1.3.0-amd64.deb
```

Because it doesn't work for me, for example with Simplenote v1.3.0. Which is expected, because `dpkg` literally cannot fetch dependencies by itself. That's what APT is for.

I'm going to close this particular issue since it is expected behavior with dpkg.

**Closed by mirka** 2019-02-25 13:19 UTC
Labels: [OS] linux
