### ISSUE TITLE
Can you support Korean?

### ISSUE THREAD

**Issue by leejongyoung** [Automattic/simplenote-electron#1571] opened 2019-09-13 08:48 UTC
Can you support Korean? I like this software very much, but this software does not support Korean very well, Korean typesetting is very bad, and the text is too crowded.
In addition, can you achieve instant display of Markdown? Like Typora.

**Comment by codebykat** [comment] 2019-09-30 20:10
Hi @leejongyoung, would it be possible for you add some screenshots? What do you mean by "typesetting is very bad, and the text is too crowded"? I tested with some sample text in Chinese, Korean and Japanese and the typography looks okay to me, but I am not a native speaker of any of those languages. It would be helpful if you could explain more about why it is bad and what you would expect to see instead.

Also, what browser and OS are you using?

**Comment by codebykat** [comment] 2019-11-19 04:37
Closing as a dupe of #1569, which has more information.

**Closed by codebykat** 2019-11-19 04:37 UTC
