### ISSUE TITLE
Character Duplication Issues in Japanese

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2385] opened 2020-10-05 14:50 UTC
User reported issue:

>When I type the Japanese symbols "■" and "→", two characters appear that are the same as "■■" and "→→". This problem does not occur in other applications. 

### Where did you see the bug

・Windows10 Home 1909
・Firefox 81.0.1 64bits
・IME ATOK 31.3.10.0 (the most famous IME in Japan)

#3376771-zen

**Comment by dmsnell** [comment] 2020-10-05 18:01
Closing as a duplicate of #2327, which is upstream in Monaco and we have a potential fix for

**Closed as completed by dmsnell** 2020-10-05 18:01 UTC
Labels: bug
