### ISSUE TITLE
Is it possible to bring typora.io like live markdown preview when we write any markdown notes in simplenote-electron?

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1734] opened 2019-11-21 12:04 UTC
### What
***Today I discovered [Typora.io](http://typora.io) which has seamless live preview function when we write markdown notes; there is no separate window or syntax highlighting then check the preview stuff. Is it possible to bring this feature in simplenote-electron?***

### Why
***Because it's distraction free, fluid and very productive; what you see is what you get***

### How
***Just add an option for live preview in preference.*** 

Already I know that it's in your feature list, but is it like typora's like seamless live preview?

@dmsnell

**Comment by belcherj** [comment] 2019-11-21 15:48
Duplicate of https://github.com/Automattic/simplenote-electron/issues/1711

Please do not open duplicate tickets as it takes more time away from development.

> Already I know that it's in your feature list, but is it like typora's like seamless live preview?

We have not planned this feature. We would not know any specifics of what we would want to do until we start planning.

**Closed by belcherj** 2019-11-21 15:48 UTC
Labels: feature request
