### ISSUE TITLE
Linux accent usage sometimes blocks further input

### ISSUE THREAD

**Issue by jroedel** [Automattic/simplenote-electron#2577] opened 2021-01-13 14:08 UTC
I'm using Simplenote 2.4.0 on Ubuntu 20.04 with the latam DBus keyboard. Frequently (but not every time), when I hit the "accent" key on my keyboard (my physical keyboard is the US layout, but I have to use the latin american keyboard to type in Spanish, so on mine it's the '[' to put an accent, then I press 'o' to form ó), I can no longer type anything or use the backspace (for some reason the delete key does work) on the current note. If I switch to a different note, I can type again. Although I can't type anything the interface is not locked up and I can move the cursor.

I've used Simplenote for years and this problem just started happening a few weeks ago. I think it coincided with the release to create links between notes. Maybe it has something to do with the fact that the latam accent key corresponds to the open square bracket on the US layout.

### Expected
The accent key should just produce an accented vowel.

### Observed
Sometimes the accent key blocks all further input.

### Reproduced
1. Open Simplenote installed with snap and login on Ubuntu 20.04 with latam keyboard installed (in order to add that locale, first add the Spanish (Chile) OS interface, then when you try to add a Spanish keyboard it will give you the Latin American keyboard option).
2. Create a new note
3. Type a few lines, with accented characters in them. Sometimes it happens more with bulleted lists '-'. Eventually, for me it locks further input. In the following example, it happened on the third line. You'll notice I was typing with markdown syntax, but I didn't have the feature enabled for this note.

![Screenshot from 2021-01-13 10-47-43](https://user-images.githubusercontent.com/3315281/104462605-b4bbb800-55a8-11eb-93a3-6d8083d0fa7b.png)

### Where did you see the bug

- System Make: Dell
- System Model: Inspiron 5400 2n1
- OS: Ubuntu
- OS version: 20.04 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.4.0

**Comment by jbouchery** [comment] 2021-01-15 08:04
Same for me with a French keyboard trying to use "^" to use letters like "ê" ("^" + "e"), get stuck after typing "^". 

I have to switch to another note and back to continue typing but can't find a solution to type "ê".

- OS: Pop_OS
- OS version: 20.10
- Simplenote app version: 2.4.0

**Comment by pascaldaniela** [comment] 2021-01-28 17:44
Same here, using Debian testing with KDE using US Intl. keyboard layout and the ibus daemon. The problem started with version 2.4.0 and is still present in 2.5.0. Any accent ' ` ^ ~ blocks the keyboard until leaving the note and coming back. 
Exiting the ibus daemon makes the accents work again. Starting the ibus daemon again doesn't change - it still works.

**Comment by codebykat** [comment] 2021-01-28 21:19
@pascaldaniela It started in 2.4.0? That's surprising... I haven't dug into this yet but the release that added links between notes was 2.1.0. I wonder if that's a red herring. 🤔 

We have a number of problems with IME inputs (see #2522) which I am still trying to find a fix for, I wonder if this is related. I'm sorry for the annoyance. It seems to be caused by some horrible interaction between two different upstream packages but I hope to know more soon.

Do either of you have issues in the browser as well, or only on the standalone app?

**Comment by jroedel** [comment] 2021-01-28 22:39
I just tested the browser version (in FF 84.0.2) and it has a similar, but not identical, issue with accents. In the browser version, the accented character is duplicated:
![Screenshot_2021-01-28 Simplenote](https://user-images.githubusercontent.com/3315281/106207339-80a3e200-61b9-11eb-8a27-5bbf00eded7d.png)

**Comment by codebykat** [comment] 2021-01-28 23:21
@jroedel Thanks for that test. Is that in Firefox only? We have a known issue for that which has been patched upstream but not yet released 😭 (#2327)

Do the accents work without blocking input though?

**Comment by jroedel** [comment] 2021-01-29 03:22
1. Correct, FF doesn't block input, it just duplicates characters
2. I just tested the web app in Chrome and it has no problems with accents
![Screenshot from 2021-01-28 21-20-24](https://user-images.githubusercontent.com/3315281/106227474-2454b880-61e1-11eb-9300-3813d77e9f1d.png)

I guess this problem is unique to electron

**Comment by codebykat** [comment] 2021-01-29 09:04
Thanks @jroedel, that matches my findings so far. The good news is the fix for that Firefox bug was actually released yesterday, which means we'll be able to get a fix out for that soon! (#2611) The bad news is I'm still trying to figure **this** one out, but I hope to get somewhere with it soon. Thanks for your patience and for helping me out with additional info. 🙇

**Comment by pascaldaniela** [comment] 2021-01-29 20:32
> @pascaldaniela It started in 2.4.0? That's surprising... I haven't dug into this yet but the release that added links between notes was 2.1.0. I wonder if that's a red herring. thinking

Hi Kat, sorry for this, it might have started before. I'm not logging my upgrade history, just know that it is a recent issue ;)

> Do either of you have issues in the browser as well, or only on the standalone app?

I have the same duplicating issue in Firefox mentioned by jroedel. And both issues go away when I shut down the ibus daemon. 
Btw, I'm using 2.6 now ...

**Comment by pascaldaniela** [comment] 2021-02-08 13:20
The issue has disappeared here with Simplenote 2.7 beta on Debian testing.

**Comment by codebykat** [comment] 2021-02-08 20:01
Ooh that is great news. @jroedel and @jbouchery, are either of you able to confirm if this is still happening for you on the 2.7 beta?

**Comment by jroedel** [comment] 2021-02-09 01:47
I just installed the 2.7 beta and it seems to be working fine now! Thanks a lot Kat. I know you put a lot of work into the project. I love simplenote!

**Comment by codebykat** [comment] 2021-02-09 05:45
Aw thanks! I do, because I love it too. 😄 

Closing this as fixed, please feel free to comment or open a new issue if there are still problems. (I mean, with the app. Not the world in general. I can only do so much.)

**Closed as completed by codebykat** 2021-02-09 05:45 UTC
Labels: bug
