### ISSUE TITLE
Can something be done about the narrow maximum width?

### ISSUE THREAD

**Issue by Hubro** [Automattic/simplenote-electron#373] opened 2016-08-31 08:09 UTC
I find it quite frustrating that with this much free space I still have to scroll to see the contents of my code block:

![image](https://cloud.githubusercontent.com/assets/597206/18120852/15302144-6f62-11e6-8f9f-130ac68b666d.png)

The same note viewed on the web app doesn't look as good, but doesn't restrict the width of the note either:

![image](https://cloud.githubusercontent.com/assets/597206/18120935/72eb179e-6f62-11e6-8bf0-24faaa67d2a9.png)

I request that the width restriction be configurable in the app settings, or removed altogether.

Perhaps a setting like: "Editor size": "Small", "Big" or "Full width"

**Comment by tkuraku** [comment] 2016-08-31 13:55
This is a must

**Comment by drw158** [comment] 2016-09-13 16:41
Duplicate of #349

**Closed by drw158** 2016-09-13 16:41 UTC
Labels: duplicate, FAQ
