### ISSUE TITLE
All fonts are bold

### ISSUE THREAD

**Issue by RasitAyaz** [Automattic/simplenote-electron#1978] opened 2020-03-24 12:59 UTC
I am using Ubuntu 18.04 and just started to use Simplenote. As far as I see, there is no switch font family or font weight option in app's preferences. All fonts on app are bold including preferences menu. It is not quite readable.  I installed Simplenote on android also, but it is working fine. I also tried to disable all gnome themes etc. still same.

### Expected
Even if I can't change font family, I want to set a decent font weight to the app.

### Observed
![Screenshot from 2020-03-24 15-16-09](https://user-images.githubusercontent.com/45076094/77427747-f6942b80-6de7-11ea-97b4-9c6f6d77d4a8.png)

Make|Model|OS Version|App Version
-|-|-|-
Monster Notebook|T7 16.1|Ubuntu 18.04|1.15.1

**Comment by dmsnell** [comment] 2020-03-24 19:40
Thanks for reporting this @RasitAyaz. I'm going to close it as a duplicate of #1970 since we're already tracking it there.

**Closed by dmsnell** 2020-03-24 19:40 UTC
Labels: bug
