### ISSUE TITLE
Restore cursor location when note is updated

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-electron#36] opened 2015-10-20 22:23 UTC
When a change is applied from Simperium, the cursor position should be updated to account for the new content.

For example, if I'm typing at the end of the note and a change comes in that modifies the beginning of the note by adding six characters, the cursor should be advanced six characters so that as I continue typing I'll be in the correct location.

**Reported In**:
 - #2642910-t
 - #864118-zen
 - #958281-zen
 - #757894-zen
 - #808817-zen
 - #1193660-zen

**Comment by dmsnell** [comment] 2018-02-19 04:45
While working on the Monaco interface I built this so that we wouldn't have to destroy the editor context the way we have been. Many issues will be simultaneously solved: wonky cursors, losing the undo history, accidentally undoing remote changes, etc…

I felt like [having access to the patch itself](https://github.com/Automattic/simplenote-electron/pull/692/files#diff-a4e7d231ffbd43ffee4a46bf0854cb1bR443) would be highly valuable and I'd like to expose more deeply the underlying data changes to the notes. For example, there are good ideas to show activity based on what segments of a note have been recently changed.

Getting the [cursor shift](https://github.com/Automattic/simplenote-electron/pull/692/files#diff-6646bac18aa042ee2a7fb3cc0a5f669cR41) introduced from a patch then became trivial after having the parsed form in app state.

**Comment by cecilerainon** [comment] 2018-06-07 09:32
Another report in #1193660-zen (they actually thought it was intended and wanted to know how to have it work on other notes...)

**Comment by jessestu** [comment] 2018-12-13 22:37
I think this is related in 1637228-zen. A Linux user writes,

> I've been using Simplenote for 8 months and I noticed that the cursor don't follow on page scroll.

> It means that if I have a long note, if the cursor is set at the bottom of the page then I hit enter. The page didn't scroll. It hard for me to just continue typing and be not able to see the latest update of my note.

**Comment by WolfyLPDC** [comment] 2018-12-20 08:37
I have been doing testing and, although the problem persists after reinstall the software, it seems to not appear anymore after deleting the folder `~/.config/Simplenote/`. Of course, you have to login again but the application turns useful, which is nice. 

If another user can report this as a solution, perhaps it can help focusing the debugging.

**Comment by logTom** [comment] 2018-12-20 09:02
Can confirm.
Deleting the folder ~/.config/Simplenote/ makes the app usable again. Thanks for pointing out this workaround.

**Comment by BackSeat** [comment] 2019-01-30 11:35
Seeing the same (just started for me with 1.4). Above fix also worked.

**Comment by rob-01** [comment] 2019-01-31 17:38
I'm also seeing this on v1.4.0 on linux mint 18.3, however deleting the folder ~/.config/Simplenote/ did not fix the issue.

**Comment by roundhill** [comment] 2019-01-31 17:39
Strange that this only happens on Linux, as far as I can tell. Maybe our bump to Electron 4 that we're working on will help with this.

**Comment by denismcdonald** [comment] 2019-02-01 07:48
Following the most recent update for Simplenote on Windows, I'm regularly encountering the cursor issue described in [#292](https://github.com/Automattic/simplenote-electron/issues/292):  "Cursor jumps to bottom of the note while editing".

I'd experienced this bug previously (many months ago, in 2018, and perhaps even prior to then), before it seemed to resolve for a good time, only to now arise again.

**Comment by KokkieH** [comment] 2019-02-01 13:03
Another report of this happening in Windows 10 received [via Twitter](https://twitter.com/aghoshal/status/1091246433720848384) today.

**Comment by ehremington** [comment] 2019-02-01 20:34
I am also having this problem on linux. Deleting .config/Simplnote seemed to work until I edited a note on the ios app, and then came back to editing it on the linux app. I add text to the top to keep a daily journal of my classes so this jumping to the bottom is very annoying. Seemed to start upon update to 1.4. Hope the note about switching between iOS and linux apps helps.

**Comment by roundhill** [comment] 2019-02-01 20:56
Thanks @ehremington, I was able to reproduce by:

* Opening up the same note on two different apps, one of them being Electron.
* Place the cursor somewhere in the note in the Electron app.
* Make a change to the note on the other app.
* The cursor jumps to the bottom in Electron.

So this could happen easily with shared notes, or any other scenario where you can receive a remote change.

**Comment by ehremington** [comment] 2019-02-05 03:07
Does this look to be the same issue as #1185?

**Comment by marianoju** [comment] 2019-07-12 08:37
More than three years later the cursor issue described in #292 ("Cursor jumps to bottom of the note while editing") still exists and impairs users. Is there any progress in resolving this bug?

**Comment by ehremington** [comment] 2019-07-12 15:22
This was fixed some time ago for me.

**Comment by marianoju** [comment] 2019-07-13 11:54
The issue #292 persists, even after removing `~/.config/Simplenote` (folder is recreated at next start of simplenote-electron).  I was able to reproduce by:

1. Creating and closing a note with simplenote-electron (on Ubuntu 18.04.2), then closing the application.  
2. Opening and editing the note with simplenote-android (on Android 8.0.0), then closing the application. 
3. Opening and editing the note with siplenote-electron (on Ubuntu 18.04.2) → the cursor jumps to the bottom while editing.

**Comment by belcherj** [comment] 2019-08-08 19:39
Closing as reported as fixed

**Closed by belcherj** 2019-08-08 19:39 UTC
Labels: FAQ, [feature] editor, bug, enhancement
